ANIMA: animaDTIProbabilisticTractography.cxx File Reference
animaDTIProbabilisticTractography.cxx File Reference
#include <animaDTIProbabilisticTractographyImageFilter.h>
#include <animaGradientFileReader.h>
#include <itkTimeProbe.h>
#include <tclap/CmdLine.h>
#include <itkImageFileReader.h>
#include <itkCommand.h>
#include <animaFibersWriter.h>
Functions
void ComputeKappaPolynomialCoefficients (std::vector< double > &resVal)
void eventCallback (itk::Object *caller, const itk::EventObject &event, void *clientData)
int main (int argc, char *argv[])
Function Documentation
void ComputeKappaPolynomialCoefficients (std::vector< double > & resVal)
Definition at line 12 of file animaDTIProbabilisticTractography.cxx.
Referenced by main().
void eventCallback (itk::Object * caller, const itk::EventObject & event, void * clientData)
Definition at line 21 of file animaDTIProbabilisticTractography.cxx.
int main (int argc, char * argv[])
Definition at line 27 of file animaDTIProbabilisticTractography.cxx.
References ComputeKappaPolynomialCoefficients(), eventCallback(), anima::FibersWriter::SetFileName(), anima::GradientFileReader< GradientType, BValueScalarType >::SetGradientFileName(), anima::FibersWriter::SetInputData(), and anima::FibersWriter::Update().