ANIMA: anima::ZeppelinCompartment Class Reference
anima::ZeppelinCompartment Class Reference
#include <animaZeppelinCompartment.h>
Public Types
typedef Superclass::Pointer BasePointer
typedef itk::SmartPointer
< const Self > ConstPointer
typedef Superclass::Matrix3DType Matrix3DType
typedef
Superclass::ModelOutputVectorType ModelOutputVectorType
typedef itk::SmartPointer< Self > Pointer
typedef ZeppelinCompartment Self
typedef BaseCompartment Superclass
typedef Superclass::Vector3DType Vector3DType
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
unsigned int GetCompartmentSize () ITK_OVERRIDE
Number of parameters to describe the model, these parameters will be self-contained, i.e. include fixed parameters for example.
DiffusionModelCompartmentType GetCompartmentType () ITK_OVERRIDE
Utility function to return compartment type without needing dynamic casts.
ModelOutputVectorType & GetCompartmentVector () ITK_OVERRIDE
Get compartment overall description vector, mainly for writing, should be self-contained.
const Matrix3DType & GetDiffusionTensor () ITK_OVERRIDE
Get compartment as a 3D tensor (default behavior: throw exception if not supported by the compartment model)
virtual double GetFourierTransformedDiffusionProfile (double bValue, const Vector3DType &gradient) ITK_OVERRIDE
double GetFractionalAnisotropy () ITK_OVERRIDE
virtual double GetLogDiffusionProfile (const Vector3DType &sample) ITK_OVERRIDE
virtual const char * GetNameOfClass () const
unsigned int GetNumberOfParameters () ITK_OVERRIDE
Number of optimized parameters: smaller than total number of parameters.
virtual ListType GetParameterLowerBounds () ITK_OVERRIDE
virtual ListType GetParametersAsVector () ITK_OVERRIDE
virtual ListType GetParameterUpperBounds () ITK_OVERRIDE
virtual ListType GetSignalAttenuationJacobian (double bValue, const Vector3DType &gradient) ITK_OVERRIDE
void SetCompartmentVector (ModelOutputVectorType &compartmentVector) ITK_OVERRIDE
Set compartment overall description vector, for setting automatically the individual parameters when reading from disk.
void SetEstimateDiffusivities (bool arg)
virtual void SetParametersFromVector (const ListType &params) ITK_OVERRIDE
Various methods for optimization parameters setting and getting.
void SetRadialDiffusivity1 (double num) ITK_OVERRIDE
Static Public Member Functions
static Pointer New ()
Protected Member Functions
virtual ListType BoundParameters (const ListType &params) ITK_OVERRIDE
virtual void UnboundParameters (ListType &params) ITK_OVERRIDE
ZeppelinCompartment ()
virtual ~ZeppelinCompartment ()
Detailed Description
Definition at line 10 of file animaZeppelinCompartment.h.
Member Typedef Documentation
typedef Superclass::Pointer anima::ZeppelinCompartment::BasePointer
Definition at line 16 of file animaZeppelinCompartment.h.
typedef itk::SmartPointer<const Self> anima::ZeppelinCompartment::ConstPointer
Reimplemented from anima::BaseCompartment.
Definition at line 18 of file animaZeppelinCompartment.h.
typedef Superclass::Matrix3DType anima::ZeppelinCompartment::Matrix3DType
Reimplemented from anima::BaseCompartment.
Definition at line 21 of file animaZeppelinCompartment.h.
typedef Superclass::ModelOutputVectorType anima::ZeppelinCompartment::ModelOutputVectorType
Reimplemented from anima::BaseCompartment.
Definition at line 19 of file animaZeppelinCompartment.h.
typedef itk::SmartPointer<Self> anima::ZeppelinCompartment::Pointer
Reimplemented from anima::BaseCompartment.
Definition at line 17 of file animaZeppelinCompartment.h.
typedef ZeppelinCompartment anima::ZeppelinCompartment::Self
Reimplemented from anima::BaseCompartment.
Definition at line 14 of file animaZeppelinCompartment.h.
typedef BaseCompartment anima::ZeppelinCompartment::Superclass
Reimplemented from anima::BaseCompartment.
Definition at line 15 of file animaZeppelinCompartment.h.
typedef Superclass::Vector3DType anima::ZeppelinCompartment::Vector3DType
Reimplemented from anima::BaseCompartment.
Definition at line 20 of file animaZeppelinCompartment.h.
Constructor & Destructor Documentation
anima::ZeppelinCompartment::ZeppelinCompartment () [inline, protected]
Definition at line 55 of file animaZeppelinCompartment.h.
virtual anima::ZeppelinCompartment::~ZeppelinCompartment () [inline, protected, virtual]
Definition at line 62 of file animaZeppelinCompartment.h.
Member Function Documentation
ZeppelinCompartment::ListType anima::ZeppelinCompartment::BoundParameters (const ListType & params) [protected, virtual]
Implements anima::BaseCompartment.
Definition at line 162 of file animaZeppelinCompartment.cxx.
References anima::mcm_utilities::ComputeBoundedValue(), anima::BaseCompartment::m_AzimuthAngleUpperBound, anima::BaseCompartment::m_DiffusivityLowerBound, anima::BaseCompartment::m_DiffusivityUpperBound, anima::BaseCompartment::m_PolarAngleUpperBound, anima::BaseCompartment::m_RadialDiffusivityUpperBound, anima::BaseCompartment::m_ZeroLowerBound, and anima::BaseCompartment::SetBoundedSignVectorValue().
Referenced by SetParametersFromVector().
virtual::itk::LightObject::Pointer anima::ZeppelinCompartment::CreateAnother (void) const
unsigned int anima::ZeppelinCompartment::GetCompartmentSize () [virtual]
Number of parameters to describe the model, these parameters will be self-contained, i.e. include fixed parameters for example.
Implements anima::BaseCompartment.
Definition at line 242 of file animaZeppelinCompartment.cxx.
Referenced by GetCompartmentVector(), GetNumberOfParameters(), and SetCompartmentVector().
DiffusionModelCompartmentType anima::ZeppelinCompartment::GetCompartmentType () [inline, virtual]
Utility function to return compartment type without needing dynamic casts.
Implements anima::BaseCompartment.
Definition at line 29 of file animaZeppelinCompartment.h.
References anima::Zeppelin.
ZeppelinCompartment::ModelOutputVectorType & anima::ZeppelinCompartment::GetCompartmentVector () [virtual]
Get compartment overall description vector, mainly for writing, should be self-contained.
Implements anima::BaseCompartment.
Definition at line 262 of file animaZeppelinCompartment.cxx.
References anima::BaseCompartment::GetAxialDiffusivity(), GetCompartmentSize(), anima::BaseCompartment::GetOrientationPhi(), anima::BaseCompartment::GetOrientationTheta(), anima::BaseCompartment::GetRadialDiffusivity1(), anima::BaseCompartment::m_CompartmentVector, anima::BaseCompartment::m_SpaceDimension, and anima::TransformSphericalToCartesianCoordinates().
const ZeppelinCompartment::Matrix3DType & anima::ZeppelinCompartment::GetDiffusionTensor () [virtual]
Get compartment as a 3D tensor (default behavior: throw exception if not supported by the compartment model)
Reimplemented from anima::BaseCompartment.
Definition at line 287 of file animaZeppelinCompartment.cxx.
References anima::BaseCompartment::GetAxialDiffusivity(), anima::BaseCompartment::GetOrientationPhi(), anima::BaseCompartment::GetOrientationTheta(), anima::BaseCompartment::GetRadialDiffusivity1(), anima::BaseCompartment::m_DiffusionTensor, anima::BaseCompartment::m_SpaceDimension, and anima::TransformSphericalToCartesianCoordinates().
double anima::ZeppelinCompartment::GetFourierTransformedDiffusionProfile (double bValue, const Vector3DType & gradient) [virtual]
Implements anima::BaseCompartment.
Definition at line 9 of file animaZeppelinCompartment.cxx.
References anima::BaseCompartment::GetAxialDiffusivity(), anima::BaseCompartment::GetOrientationPhi(), anima::BaseCompartment::GetOrientationTheta(), and anima::BaseCompartment::GetRadialDiffusivity1().
Referenced by GetSignalAttenuationJacobian().
double anima::ZeppelinCompartment::GetFractionalAnisotropy () [virtual]
Reimplemented from anima::BaseCompartment.
Definition at line 308 of file animaZeppelinCompartment.cxx.
References anima::BaseCompartment::GetAxialDiffusivity(), and anima::BaseCompartment::GetRadialDiffusivity1().
double anima::ZeppelinCompartment::GetLogDiffusionProfile (const Vector3DType & sample) [virtual]
Implements anima::BaseCompartment.
Definition at line 71 of file animaZeppelinCompartment.cxx.
References anima::ComputeScalarProduct(), anima::BaseCompartment::GetAxialDiffusivity(), anima::BaseCompartment::GetOrientationPhi(), anima::BaseCompartment::GetOrientationTheta(), anima::BaseCompartment::GetRadialDiffusivity1(), and anima::TransformSphericalToCartesianCoordinates().
virtual const char* anima::ZeppelinCompartment::GetNameOfClass () const [virtual]
Run-time type information (and related methods)
Reimplemented from anima::BaseCompartment.
unsigned int anima::ZeppelinCompartment::GetNumberOfParameters () [virtual]
Number of optimized parameters: smaller than total number of parameters.
Implements anima::BaseCompartment.
Definition at line 247 of file animaZeppelinCompartment.cxx.
References GetCompartmentSize().
Referenced by GetParameterLowerBounds(), GetParametersAsVector(), GetParameterUpperBounds(), GetSignalAttenuationJacobian(), and SetParametersFromVector().
ZeppelinCompartment::ListType anima::ZeppelinCompartment::GetParameterLowerBounds () [virtual]
Implements anima::BaseCompartment.
Definition at line 136 of file animaZeppelinCompartment.cxx.
References GetNumberOfParameters(), anima::BaseCompartment::m_DiffusivityLowerBound, and anima::BaseCompartment::m_ZeroLowerBound.
ZeppelinCompartment::ListType anima::ZeppelinCompartment::GetParametersAsVector () [virtual]
Implements anima::BaseCompartment.
Definition at line 117 of file animaZeppelinCompartment.cxx.
References anima::BaseCompartment::GetAxialDiffusivity(), GetNumberOfParameters(), anima::BaseCompartment::GetOrientationPhi(), anima::BaseCompartment::GetOrientationTheta(), anima::BaseCompartment::GetRadialDiffusivity1(), anima::BaseCompartment::GetUseBoundedOptimization(), and UnboundParameters().
ZeppelinCompartment::ListType anima::ZeppelinCompartment::GetParameterUpperBounds () [virtual]
Implements anima::BaseCompartment.
Definition at line 146 of file animaZeppelinCompartment.cxx.
References GetNumberOfParameters(), anima::BaseCompartment::m_AzimuthAngleUpperBound, anima::BaseCompartment::m_DiffusivityUpperBound, anima::BaseCompartment::m_PolarAngleUpperBound, and anima::BaseCompartment::m_RadialDiffusivityUpperBound.
ZeppelinCompartment::ListType anima::ZeppelinCompartment::GetSignalAttenuationJacobian (double bValue, const Vector3DType & gradient) [virtual]
Implements anima::BaseCompartment.
Definition at line 20 of file animaZeppelinCompartment.cxx.
References anima::mcm_utilities::BoundedDerivativeAddOn(), anima::BaseCompartment::GetAxialDiffusivity(), anima::BaseCompartment::GetBoundedSignVectorValue(), GetFourierTransformedDiffusionProfile(), GetNumberOfParameters(), anima::BaseCompartment::GetOrientationPhi(), anima::BaseCompartment::GetOrientationTheta(), anima::BaseCompartment::GetRadialDiffusivity1(), anima::BaseCompartment::GetUseBoundedOptimization(), anima::BaseCompartment::m_AzimuthAngleUpperBound, anima::BaseCompartment::m_DiffusivityLowerBound, anima::BaseCompartment::m_DiffusivityUpperBound, anima::BaseCompartment::m_PolarAngleUpperBound, anima::BaseCompartment::m_RadialDiffusivityUpperBound, and anima::BaseCompartment::m_ZeroLowerBound.
static Pointer anima::ZeppelinCompartment::New () [static]
Referenced by anima::MCMFileReader< PixelType, ImageDimension >::CreateCompartmentForType().
void anima::ZeppelinCompartment::SetCompartmentVector (ModelOutputVectorType & compartmentVector) [virtual]
Set compartment overall description vector, for setting automatically the individual parameters when reading from disk.
Implements anima::BaseCompartment.
Definition at line 204 of file animaZeppelinCompartment.cxx.
References GetCompartmentSize(), anima::BaseCompartment::m_SpaceDimension, anima::BaseCompartment::SetAxialDiffusivity(), anima::BaseCompartment::SetOrientationPhi(), anima::BaseCompartment::SetOrientationTheta(), SetRadialDiffusivity1(), and anima::TransformCartesianToSphericalCoordinates().
void anima::ZeppelinCompartment::SetEstimateDiffusivities (bool arg)
Definition at line 195 of file animaZeppelinCompartment.cxx.
void anima::ZeppelinCompartment::SetParametersFromVector (const ListType & params) [virtual]
Various methods for optimization parameters setting and getting.
Implements anima::BaseCompartment.
Definition at line 91 of file animaZeppelinCompartment.cxx.
References BoundParameters(), anima::BaseCompartment::GetBoundedSignVector(), GetNumberOfParameters(), anima::BaseCompartment::GetUseBoundedOptimization(), anima::BaseCompartment::SetAxialDiffusivity(), anima::BaseCompartment::SetOrientationPhi(), anima::BaseCompartment::SetOrientationTheta(), and SetRadialDiffusivity1().
void anima::ZeppelinCompartment::SetRadialDiffusivity1 (double num) [virtual]
Reimplemented from anima::BaseCompartment.
Definition at line 85 of file animaZeppelinCompartment.cxx.
References anima::BaseCompartment::SetRadialDiffusivity1(), and anima::BaseCompartment::SetRadialDiffusivity2().
Referenced by SetCompartmentVector(), and SetParametersFromVector().
void anima::ZeppelinCompartment::UnboundParameters (ListType & params) [protected, virtual]
Implements anima::BaseCompartment.
Definition at line 183 of file animaZeppelinCompartment.cxx.
References anima::BaseCompartment::m_AzimuthAngleUpperBound, anima::BaseCompartment::m_DiffusivityLowerBound, anima::BaseCompartment::m_DiffusivityUpperBound, anima::BaseCompartment::m_PolarAngleUpperBound, anima::BaseCompartment::m_RadialDiffusivityUpperBound, anima::BaseCompartment::m_ZeroLowerBound, and anima::mcm_utilities::UnboundValue().
Referenced by GetParametersAsVector().
The documentation for this class was generated from the following files:
animaZeppelinCompartment.h
animaZeppelinCompartment.cxx