ANIMA: anima::IsotropicRestrictedWaterCompartment Class Reference
anima::IsotropicRestrictedWaterCompartment Class Reference
#include <animaIsotropicRestrictedWaterCompartment.h>
Public Types
typedef Superclass::Pointer BasePointer
typedef itk::SmartPointer
< const Self > ConstPointer
typedef itk::SmartPointer< Self > Pointer
typedef
IsotropicRestrictedWaterCompartment Self
typedef BaseIsotropicCompartment Superclass
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
DiffusionModelCompartmentType GetCompartmentType () ITK_OVERRIDE
Utility function to return compartment type without needing dynamic casts.
virtual const char * GetNameOfClass () const
virtual ListType GetParameterLowerBounds () ITK_OVERRIDE
virtual ListType GetParameterUpperBounds () ITK_OVERRIDE
Static Public Member Functions
static Pointer New ()
Protected Member Functions
virtual ListType BoundParameters (const ListType &params) ITK_OVERRIDE
double GetAxialDiffusivityDerivativeFactor () ITK_OVERRIDE
IsotropicRestrictedWaterCompartment ()
virtual void UnboundParameters (ListType &params) ITK_OVERRIDE
virtual ~IsotropicRestrictedWaterCompartment ()
Detailed Description
Definition at line 9 of file animaIsotropicRestrictedWaterCompartment.h.
Member Typedef Documentation
typedef Superclass::Pointer anima::IsotropicRestrictedWaterCompartment::BasePointer
Reimplemented from anima::BaseIsotropicCompartment.
Definition at line 15 of file animaIsotropicRestrictedWaterCompartment.h.
typedef itk::SmartPointer<const Self> anima::IsotropicRestrictedWaterCompartment::ConstPointer
Reimplemented from anima::BaseIsotropicCompartment.
Definition at line 17 of file animaIsotropicRestrictedWaterCompartment.h.
typedef itk::SmartPointer<Self> anima::IsotropicRestrictedWaterCompartment::Pointer
Reimplemented from anima::BaseIsotropicCompartment.
Definition at line 16 of file animaIsotropicRestrictedWaterCompartment.h.
typedef IsotropicRestrictedWaterCompartment anima::IsotropicRestrictedWaterCompartment::Self
Reimplemented from anima::BaseIsotropicCompartment.
Definition at line 13 of file animaIsotropicRestrictedWaterCompartment.h.
typedef BaseIsotropicCompartment anima::IsotropicRestrictedWaterCompartment::Superclass
Reimplemented from anima::BaseIsotropicCompartment.
Definition at line 14 of file animaIsotropicRestrictedWaterCompartment.h.
Constructor & Destructor Documentation
anima::IsotropicRestrictedWaterCompartment::IsotropicRestrictedWaterCompartment () [inline, protected]
Definition at line 31 of file animaIsotropicRestrictedWaterCompartment.h.
virtual anima::IsotropicRestrictedWaterCompartment::~IsotropicRestrictedWaterCompartment () [inline, protected, virtual]
Definition at line 36 of file animaIsotropicRestrictedWaterCompartment.h.
Member Function Documentation
IsotropicRestrictedWaterCompartment::ListType anima::IsotropicRestrictedWaterCompartment::BoundParameters (const ListType & params) [protected, virtual]
Implements anima::BaseCompartment.
Definition at line 36 of file animaIsotropicRestrictedWaterCompartment.cxx.
References anima::mcm_utilities::ComputeBoundedValue(), anima::BaseIsotropicCompartment::GetEstimateAxialDiffusivity(), and anima::BaseCompartment::SetBoundedSignVectorValue().
virtual::itk::LightObject::Pointer anima::IsotropicRestrictedWaterCompartment::CreateAnother (void) const
double anima::IsotropicRestrictedWaterCompartment::GetAxialDiffusivityDerivativeFactor () [protected, virtual]
Reimplemented from anima::BaseIsotropicCompartment.
Definition at line 51 of file animaIsotropicRestrictedWaterCompartment.cxx.
References anima::mcm_utilities::BoundedDerivativeAddOn(), anima::BaseCompartment::GetAxialDiffusivity(), and anima::BaseCompartment::GetBoundedSignVectorValue().
DiffusionModelCompartmentType anima::IsotropicRestrictedWaterCompartment::GetCompartmentType () [inline, virtual]
Utility function to return compartment type without needing dynamic casts.
Implements anima::BaseCompartment.
Definition at line 25 of file animaIsotropicRestrictedWaterCompartment.h.
References anima::IsotropicRestrictedWater.
virtual const char* anima::IsotropicRestrictedWaterCompartment::GetNameOfClass () const [virtual]
Run-time type information (and related methods)
Reimplemented from anima::BaseIsotropicCompartment.
IsotropicRestrictedWaterCompartment::ListType anima::IsotropicRestrictedWaterCompartment::GetParameterLowerBounds () [virtual]
Implements anima::BaseCompartment.
Definition at line 9 of file animaIsotropicRestrictedWaterCompartment.cxx.
References anima::BaseIsotropicCompartment::GetEstimateAxialDiffusivity(), and anima::BaseIsotropicCompartment::GetNumberOfParameters().
IsotropicRestrictedWaterCompartment::ListType anima::IsotropicRestrictedWaterCompartment::GetParameterUpperBounds () [virtual]
Implements anima::BaseCompartment.
Definition at line 19 of file animaIsotropicRestrictedWaterCompartment.cxx.
References anima::BaseIsotropicCompartment::GetEstimateAxialDiffusivity(), and anima::BaseIsotropicCompartment::GetNumberOfParameters().
static Pointer anima::IsotropicRestrictedWaterCompartment::New () [static]
Referenced by anima::MCMFileReader< PixelType, ImageDimension >::CreateCompartmentForType().
void anima::IsotropicRestrictedWaterCompartment::UnboundParameters (ListType & params) [protected, virtual]
Implements anima::BaseCompartment.
Definition at line 29 of file animaIsotropicRestrictedWaterCompartment.cxx.
References anima::BaseIsotropicCompartment::GetEstimateAxialDiffusivity(), and anima::mcm_utilities::UnboundValue().
The documentation for this class was generated from the following files:
animaIsotropicRestrictedWaterCompartment.h
animaIsotropicRestrictedWaterCompartment.cxx