ANIMA: anima::BaseProbabilisticTractographyImageFilter Class Reference
anima::BaseProbabilisticTractographyImageFilter Class Reference
#include <animaBaseProbabilisticTractographyImageFilter.h>
Classes
struct FiberWorkType
struct pair_comparator
struct trackerArguments
Public Types
enum ColinearityDirectionType {
Center = 0,
Outward,
Top,
Bottom,
Left,
Right,
Front,
Back
}
Which direction should the very first direction point to? (used in conjunction with InitialDirectionMode) Center: towards gravity center Outward: outward from gravity center Top: Image top (z axis) Bottom: Image bottom (reverse z axis) ...
typedef itk::SmartPointer
< const Self > ConstPointer
typedef
InterpolatorType::ContinuousIndexType ContinuousIndexType
typedef std::vector< Vector3DType > DirectionVectorType
typedef std::vector
< InterpolatorPointerType > DWIInterpolatorPointerVectorType
typedef std::vector< FiberType > FiberProcessVectorType
typedef std::vector< PointType > FiberType
typedef float ImageScalarType
typedef MaskImageType::IndexType IndexType
enum InitialDirectionModeType {
Colinear = 0,
Weight
}
Tells how to choose the very first direction of each particle Colinear: Most colinear to colinear direction specified (ColinearityDirectionType) Weight: Model direction with the highest weight.
typedef itk::Image
< ImageScalarType, 4 > Input4DImageType
typedef InputImageType::Pointer InputImagePointerType
typedef std::vector
< InputImagePointerType > InputImagePointerVectorType
typedef itk::Image
< ImageScalarType, 3 > InputImageType
typedef InterpolatorType::Pointer InterpolatorPointerType
typedef
itk::LinearInterpolateImageFunction
< InputImageType > InterpolatorType
typedef std::vector
< MathScalarType > ListType
typedef MaskImageType::Pointer MaskImagePointer
typedef itk::Image< unsigned
short, 3 > MaskImageType
typedef double MathScalarType
typedef itk::Matrix
< MathScalarType, 3, 3 > Matrix3DType
typedef std::vector< unsigned int > MembershipType
typedef itk::SmartPointer< Self > Pointer
typedef MaskImageType::PointType PointType
typedef
BaseProbabilisticTractographyImageFilter Self
typedef itk::ProcessObject Superclass
typedef itk::Vector
< MathScalarType, 3 > Vector3DType
typedef
itk::VariableLengthVector
< MathScalarType > VectorType
Public Member Functions
void AddGradientDirection (unsigned int i, Vector3DType &grad)
void createVTKOutput (FiberProcessVectorType &filteredFibers, ListType &filteredWeights)
MathScalarType GetBValueItem (unsigned int i)
Vector3DType & GetDiffusionGradient (unsigned int i)
DirectionVectorType & GetDiffusionGradients ()
virtual InitialDirectionModeType GetInitialDirectionMode ()
InputImageType * GetInputImage (unsigned int i)
InputImagePointerVectorType GetInputImages ()
virtual double GetKappaOfPriorDistribution ()
virtual unsigned int GetModelDimension ()
virtual const char * GetNameOfClass () const
vtkPolyData * GetOutput ()
void SetBValuesList (ListType bValuesList)
virtual void SetClusterDistance (unsigned int _arg)
virtual void SetComputeLocalColors (bool _arg)
virtual void SetCutMask (MaskImageType *_arg)
virtual void SetFiberTrashThreshold (double _arg)
virtual void SetFilterMask (MaskImageType *_arg)
virtual void SetForbiddenMask (MaskImageType *_arg)
void SetInitialColinearityDirection (const ColinearityDirectionType &colDir)
void SetInitialDirectionMode (const InitialDirectionModeType &dir)
void SetInputImagesFrom4DImage (Input4DImageType *in4DImage)
virtual void SetKappaOfPriorDistribution (double _arg)
virtual void SetKappaSplitThreshold (double _arg)
virtual void SetMAPMergeFibers (bool _arg)
virtual void SetMaxLengthFiber (double _arg)
virtual void SetMinimalNumberOfParticlesPerClass (unsigned int _arg)
virtual void SetMinLengthFiber (double _arg)
virtual void SetModelDimension (unsigned int _arg)
virtual void SetNumberOfFibersPerPixel (unsigned int _arg)
virtual void SetNumberOfParticles (unsigned int _arg)
virtual void SetPositionDistanceFuseThreshold (double _arg)
virtual void SetResamplingThreshold (double _arg)
virtual void SetSeedMask (MaskImageType *_arg)
virtual void SetStepProgression (double _arg)
void Update () ITK_OVERRIDE
Protected Member Functions
BaseProbabilisticTractographyImageFilter ()
virtual bool CheckModelProperties (double estimatedB0Value, double estimatedNoiseValue, VectorType &modelValue, unsigned int threadId)=0
Check stopping criterions to stop a particle (model dependent, not implemented here)
virtual void ComputeAdditionalScalarMaps ()
Computes additional scalar maps that are model dependent to add to the output.
FiberProcessVectorType ComputeFiber (FiberType &fiber, DWIInterpolatorPointerVectorType &dwiInterpolators, unsigned int numThread, ListType &resultWeights)
This little guy is the one handling probabilistic tracking.
virtual double ComputeLogWeightUpdate (double b0Value, double noiseValue, Vector3DType &newDirection, Vector3DType &sampling_direction, VectorType &modelValue, VectorType &dwiValue, double &log_prior, double &log_proposal, unsigned int threadId)=0
Update particle weight based on an underlying model and the chosen direction (model dependent, not implemented here)
virtual double ComputeModelEstimation (DWIInterpolatorPointerVectorType &dwiInterpolators, ContinuousIndexType &index, VectorType &dwiValue, double &noiseValue, VectorType &modelValue)=0
Estimate model from raw diffusion data (model dependent, not implemented here)
FiberProcessVectorType FilterOutputFibers (FiberProcessVectorType &fibers, ListType &weights)
Filter output fibers by ROIs and compute local colors.
virtual Vector3DType InitializeFirstIterationFromModel (Vector3DType &colinearDir, VectorType &modelValue, unsigned int threadId)=0
Initialize first direction from user input (model dependent, not implemented here)
bool MergeParticleClassFibers (FiberWorkType &fiberData, FiberProcessVectorType &outputMerged, unsigned int classNumber)
This guy takes the result of computefiber and merges the classes, each one becomes one fiber.
virtual void PrepareTractography ()
Generate seed points (can be re-implemented but this one has to be called)
virtual Vector3DType ProposeNewDirection (Vector3DType &oldDirection, VectorType &modelValue, Vector3DType &sampling_direction, double &log_prior, double &log_proposal, std::mt19937 &random_generator, unsigned int threadId)=0
Propose new direction for a particle, given the old direction, and a model (model dependent, not implemented here)
void ThreadedTrackComputer (unsigned int numThread, FiberProcessVectorType &resultFibers, ListType &resultWeights, unsigned int startSeedIndex, unsigned int endSeedIndex)
Doing the real tracking by calling ComputeFiber and merging its results.
void ThreadTrack (unsigned int numThread, FiberProcessVectorType &resultFibers, ListType &resultWeights)
Doing the thread work dispatch.
unsigned int UpdateClassesMemberships (FiberWorkType &fiberData, DirectionVectorType &directions, std::mt19937 &random_generator)
This ugly guy is the heart of multi-modal probabilistic tractography, making decisions on split and merges of particles.
virtual ~BaseProbabilisticTractographyImageFilter ()
Static Protected Member Functions
static ITK_THREAD_RETURN_TYPE ThreadTracker (void *arg)
Multithread util function.
Detailed Description
Definition at line 21 of file animaBaseProbabilisticTractographyImageFilter.h.
Member Typedef Documentation
typedef itk::SmartPointer<const Self> anima::BaseProbabilisticTractographyImageFilter::ConstPointer
Reimplemented in anima::DTIProbabilisticTractographyImageFilter, and anima::ODFProbabilisticTractographyImageFilter.
Definition at line 29 of file animaBaseProbabilisticTractographyImageFilter.h.
typedef InterpolatorType::ContinuousIndexType anima::BaseProbabilisticTractographyImageFilter::ContinuousIndexType
Definition at line 60 of file animaBaseProbabilisticTractographyImageFilter.h.
typedef std::vector<Vector3DType> anima::BaseProbabilisticTractographyImageFilter::DirectionVectorType
Definition at line 54 of file animaBaseProbabilisticTractographyImageFilter.h.
typedef std::vector< InterpolatorPointerType > anima::BaseProbabilisticTractographyImageFilter::DWIInterpolatorPointerVectorType
Definition at line 59 of file animaBaseProbabilisticTractographyImageFilter.h.
typedef std::vector<FiberType> anima::BaseProbabilisticTractographyImageFilter::FiberProcessVectorType
Definition at line 64 of file animaBaseProbabilisticTractographyImageFilter.h.
typedef std::vector<PointType> anima::BaseProbabilisticTractographyImageFilter::FiberType
Definition at line 63 of file animaBaseProbabilisticTractographyImageFilter.h.
typedef float anima::BaseProbabilisticTractographyImageFilter::ImageScalarType
Definition at line 34 of file animaBaseProbabilisticTractographyImageFilter.h.
typedef MaskImageType::IndexType anima::BaseProbabilisticTractographyImageFilter::IndexType
Definition at line 47 of file animaBaseProbabilisticTractographyImageFilter.h.
typedef itk::Image<ImageScalarType,4> anima::BaseProbabilisticTractographyImageFilter::Input4DImageType
Definition at line 38 of file animaBaseProbabilisticTractographyImageFilter.h.
typedef InputImageType::Pointer anima::BaseProbabilisticTractographyImageFilter::InputImagePointerType
Definition at line 40 of file animaBaseProbabilisticTractographyImageFilter.h.
typedef std::vector<InputImagePointerType> anima::BaseProbabilisticTractographyImageFilter::InputImagePointerVectorType
Definition at line 41 of file animaBaseProbabilisticTractographyImageFilter.h.
typedef itk::Image<ImageScalarType,3> anima::BaseProbabilisticTractographyImageFilter::InputImageType
Definition at line 39 of file animaBaseProbabilisticTractographyImageFilter.h.
typedef InterpolatorType::Pointer anima::BaseProbabilisticTractographyImageFilter::InterpolatorPointerType
Definition at line 58 of file animaBaseProbabilisticTractographyImageFilter.h.
typedef itk::LinearInterpolateImageFunction<InputImageType> anima::BaseProbabilisticTractographyImageFilter::InterpolatorType
Definition at line 57 of file animaBaseProbabilisticTractographyImageFilter.h.
typedef std::vector<MathScalarType> anima::BaseProbabilisticTractographyImageFilter::ListType
Definition at line 53 of file animaBaseProbabilisticTractographyImageFilter.h.
typedef MaskImageType::Pointer anima::BaseProbabilisticTractographyImageFilter::MaskImagePointer
Definition at line 45 of file animaBaseProbabilisticTractographyImageFilter.h.
typedef itk::Image<unsigned short, 3> anima::BaseProbabilisticTractographyImageFilter::MaskImageType
Definition at line 44 of file animaBaseProbabilisticTractographyImageFilter.h.
typedef double anima::BaseProbabilisticTractographyImageFilter::MathScalarType
Definition at line 35 of file animaBaseProbabilisticTractographyImageFilter.h.
typedef itk::Matrix<MathScalarType,3,3> anima::BaseProbabilisticTractographyImageFilter::Matrix3DType
Definition at line 50 of file animaBaseProbabilisticTractographyImageFilter.h.
typedef std::vector<unsigned int> anima::BaseProbabilisticTractographyImageFilter::MembershipType
Definition at line 65 of file animaBaseProbabilisticTractographyImageFilter.h.
typedef itk::SmartPointer<Self> anima::BaseProbabilisticTractographyImageFilter::Pointer
Reimplemented in anima::DTIProbabilisticTractographyImageFilter, and anima::ODFProbabilisticTractographyImageFilter.
Definition at line 28 of file animaBaseProbabilisticTractographyImageFilter.h.
typedef MaskImageType::PointType anima::BaseProbabilisticTractographyImageFilter::PointType
Definition at line 46 of file animaBaseProbabilisticTractographyImageFilter.h.
typedef BaseProbabilisticTractographyImageFilter anima::BaseProbabilisticTractographyImageFilter::Self
SmartPointer typedef support
Reimplemented in anima::DTIProbabilisticTractographyImageFilter, and anima::ODFProbabilisticTractographyImageFilter.
Definition at line 25 of file animaBaseProbabilisticTractographyImageFilter.h.
typedef itk::ProcessObject anima::BaseProbabilisticTractographyImageFilter::Superclass
Reimplemented in anima::DTIProbabilisticTractographyImageFilter, and anima::ODFProbabilisticTractographyImageFilter.
Definition at line 26 of file animaBaseProbabilisticTractographyImageFilter.h.
typedef itk::Vector<MathScalarType,3> anima::BaseProbabilisticTractographyImageFilter::Vector3DType
Definition at line 51 of file animaBaseProbabilisticTractographyImageFilter.h.
typedef itk::VariableLengthVector<MathScalarType> anima::BaseProbabilisticTractographyImageFilter::VectorType
Definition at line 52 of file animaBaseProbabilisticTractographyImageFilter.h.
Member Enumeration Documentation
enum anima::BaseProbabilisticTractographyImageFilter::ColinearityDirectionType
Which direction should the very first direction point to? (used in conjunction with InitialDirectionMode) Center: towards gravity center Outward: outward from gravity center Top: Image top (z axis) Bottom: Image bottom (reverse z axis) ...
Enumerator:
Center
Outward
Top
Bottom
Left
Right
Front
Back
Definition at line 87 of file animaBaseProbabilisticTractographyImageFilter.h.
enum anima::BaseProbabilisticTractographyImageFilter::InitialDirectionModeType
Tells how to choose the very first direction of each particle Colinear: Most colinear to colinear direction specified (ColinearityDirectionType) Weight: Model direction with the highest weight.
Enumerator:
Colinear
Weight
Definition at line 104 of file animaBaseProbabilisticTractographyImageFilter.h.
Constructor & Destructor Documentation
anima::BaseProbabilisticTractographyImageFilter::BaseProbabilisticTractographyImageFilter () [protected]
Definition at line 36 of file animaBaseProbabilisticTractographyImageFilter.cxx.
References Center, and Weight.
anima::BaseProbabilisticTractographyImageFilter::~BaseProbabilisticTractographyImageFilter () [protected, virtual]
Definition at line 70 of file animaBaseProbabilisticTractographyImageFilter.cxx.
Member Function Documentation
void anima::BaseProbabilisticTractographyImageFilter::AddGradientDirection (unsigned int i, Vector3DType & grad)
Definition at line 26 of file animaBaseProbabilisticTractographyImageFilter.cxx.
virtual bool anima::BaseProbabilisticTractographyImageFilter::CheckModelProperties (double estimatedB0Value, double estimatedNoiseValue, VectorType & modelValue, unsigned int threadId) [protected, pure virtual]
Check stopping criterions to stop a particle (model dependent, not implemented here)
Implemented in anima::DTIProbabilisticTractographyImageFilter, and anima::ODFProbabilisticTractographyImageFilter.
Referenced by ComputeFiber().
virtual void anima::BaseProbabilisticTractographyImageFilter::ComputeAdditionalScalarMaps () [inline, protected, virtual]
Computes additional scalar maps that are model dependent to add to the output.
Reimplemented in anima::DTIProbabilisticTractographyImageFilter.
Definition at line 233 of file animaBaseProbabilisticTractographyImageFilter.h.
Referenced by createVTKOutput().
BaseProbabilisticTractographyImageFilter::FiberProcessVectorType anima::BaseProbabilisticTractographyImageFilter::ComputeFiber (FiberType & fiber, DWIInterpolatorPointerVectorType & dwiInterpolators, unsigned int numThread, ListType & resultWeights) [protected]
This little guy is the one handling probabilistic tracking.
Definition at line 477 of file animaBaseProbabilisticTractographyImageFilter.cxx.
References Back, Bottom, Center, CheckModelProperties(), anima::BaseProbabilisticTractographyImageFilter::FiberWorkType::classMemberships, anima::BaseProbabilisticTractographyImageFilter::FiberWorkType::classSizes, anima::BaseProbabilisticTractographyImageFilter::FiberWorkType::classWeights, ComputeLogWeightUpdate(), ComputeModelEstimation(), anima::ExponentialSum(), anima::BaseProbabilisticTractographyImageFilter::FiberWorkType::fiberParticles, Front, InitializeFirstIterationFromModel(), Left, MergeParticleClassFibers(), Outward, anima::BaseProbabilisticTractographyImageFilter::FiberWorkType::particleWeights, ProposeNewDirection(), anima::BaseProbabilisticTractographyImageFilter::FiberWorkType::reverseClassMemberships, Right, anima::safe_log(), anima::BaseProbabilisticTractographyImageFilter::FiberWorkType::stoppedParticles, Top, and UpdateClassesMemberships().
Referenced by ThreadedTrackComputer().
virtual double anima::BaseProbabilisticTractographyImageFilter::ComputeLogWeightUpdate (double b0Value, double noiseValue, Vector3DType & newDirection, Vector3DType & sampling_direction, VectorType & modelValue, VectorType & dwiValue, double & log_prior, double & log_proposal, unsigned int threadId) [protected, pure virtual]
Update particle weight based on an underlying model and the chosen direction (model dependent, not implemented here)
Implemented in anima::DTIProbabilisticTractographyImageFilter, and anima::ODFProbabilisticTractographyImageFilter.
Referenced by ComputeFiber().
virtual double anima::BaseProbabilisticTractographyImageFilter::ComputeModelEstimation (DWIInterpolatorPointerVectorType & dwiInterpolators, ContinuousIndexType & index, VectorType & dwiValue, double & noiseValue, VectorType & modelValue) [protected, pure virtual]
Estimate model from raw diffusion data (model dependent, not implemented here)
Implemented in anima::DTIProbabilisticTractographyImageFilter, and anima::ODFProbabilisticTractographyImageFilter.
Referenced by ComputeFiber(), and ThreadedTrackComputer().
void anima::BaseProbabilisticTractographyImageFilter::createVTKOutput (FiberProcessVectorType & filteredFibers, ListType & filteredWeights)
Definition at line 407 of file animaBaseProbabilisticTractographyImageFilter.cxx.
References ComputeAdditionalScalarMaps().
Referenced by Update().
BaseProbabilisticTractographyImageFilter::FiberProcessVectorType anima::BaseProbabilisticTractographyImageFilter::FilterOutputFibers (FiberProcessVectorType & fibers, ListType & weights) [protected]
Filter output fibers by ROIs and compute local colors.
Definition at line 334 of file animaBaseProbabilisticTractographyImageFilter.cxx.
Referenced by ThreadedTrackComputer().
MathScalarType anima::BaseProbabilisticTractographyImageFilter::GetBValueItem (unsigned int i) [inline]
Definition at line 140 of file animaBaseProbabilisticTractographyImageFilter.h.
Referenced by anima::DTIProbabilisticTractographyImageFilter::ComputeLogWeightUpdate(), anima::DTIProbabilisticTractographyImageFilter::ComputeModelEstimation(), and anima::DTIProbabilisticTractographyImageFilter::SetDesignMatrix().
Vector3DType& anima::BaseProbabilisticTractographyImageFilter::GetDiffusionGradient (unsigned int i) [inline]
Definition at line 137 of file animaBaseProbabilisticTractographyImageFilter.h.
Referenced by anima::ODFProbabilisticTractographyImageFilter::ComputeLogWeightUpdate(), anima::DTIProbabilisticTractographyImageFilter::ComputeLogWeightUpdate(), anima::ODFProbabilisticTractographyImageFilter::ComputeModelEstimation(), anima::ODFProbabilisticTractographyImageFilter::PrepareTractography(), and anima::DTIProbabilisticTractographyImageFilter::SetDesignMatrix().
DirectionVectorType& anima::BaseProbabilisticTractographyImageFilter::GetDiffusionGradients () [inline]
Definition at line 136 of file animaBaseProbabilisticTractographyImageFilter.h.
Referenced by anima::ODFProbabilisticTractographyImageFilter::ComputeLogWeightUpdate(), anima::DTIProbabilisticTractographyImageFilter::ComputeLogWeightUpdate(), anima::ODFProbabilisticTractographyImageFilter::PrepareTractography(), and anima::DTIProbabilisticTractographyImageFilter::SetDesignMatrix().
virtual InitialDirectionModeType anima::BaseProbabilisticTractographyImageFilter::GetInitialDirectionMode () [virtual]
Referenced by anima::ODFProbabilisticTractographyImageFilter::InitializeFirstIterationFromModel(), and anima::DTIProbabilisticTractographyImageFilter::InitializeFirstIterationFromModel().
InputImageType* anima::BaseProbabilisticTractographyImageFilter::GetInputImage (unsigned int i) [inline]
Definition at line 127 of file animaBaseProbabilisticTractographyImageFilter.h.
Referenced by anima::DTIProbabilisticTractographyImageFilter::ComputeAdditionalScalarMaps(), anima::DTIProbabilisticTractographyImageFilter::ComputeLogWeightUpdate(), anima::ODFProbabilisticTractographyImageFilter::InitializeFirstIterationFromModel(), anima::DTIProbabilisticTractographyImageFilter::InitializeFirstIterationFromModel(), anima::ODFProbabilisticTractographyImageFilter::ProposeNewDirection(), and anima::DTIProbabilisticTractographyImageFilter::ProposeNewDirection().
InputImagePointerVectorType anima::BaseProbabilisticTractographyImageFilter::GetInputImages () [inline]
Definition at line 126 of file animaBaseProbabilisticTractographyImageFilter.h.
Referenced by anima::DTIProbabilisticTractographyImageFilter::ComputeAdditionalScalarMaps().
virtual double anima::BaseProbabilisticTractographyImageFilter::GetKappaOfPriorDistribution () [virtual]
Referenced by anima::ODFProbabilisticTractographyImageFilter::ProposeNewDirection(), and anima::DTIProbabilisticTractographyImageFilter::ProposeNewDirection().
virtual unsigned int anima::BaseProbabilisticTractographyImageFilter::GetModelDimension () [virtual]
Referenced by anima::ODFProbabilisticTractographyImageFilter::CheckModelProperties(), anima::DTIProbabilisticTractographyImageFilter::CheckModelProperties(), anima::DTIProbabilisticTractographyImageFilter::ComputeAdditionalScalarMaps(), anima::ODFProbabilisticTractographyImageFilter::ComputeLogWeightUpdate(), anima::ODFProbabilisticTractographyImageFilter::ComputeModelEstimation(), anima::DTIProbabilisticTractographyImageFilter::ComputeModelEstimation(), anima::ODFProbabilisticTractographyImageFilter::GetGeneralizedFractionalAnisotropy(), anima::ODFProbabilisticTractographyImageFilter::PrepareTractography(), and anima::DTIProbabilisticTractographyImageFilter::SetDesignMatrix().
virtual const char* anima::BaseProbabilisticTractographyImageFilter::GetNameOfClass () const [virtual]
Reimplemented in anima::DTIProbabilisticTractographyImageFilter, and anima::ODFProbabilisticTractographyImageFilter.
vtkPolyData* anima::BaseProbabilisticTractographyImageFilter::GetOutput () [inline]
Definition at line 177 of file animaBaseProbabilisticTractographyImageFilter.h.
Referenced by anima::DTIProbabilisticTractographyImageFilter::ComputeAdditionalScalarMaps().
virtual Vector3DType anima::BaseProbabilisticTractographyImageFilter::InitializeFirstIterationFromModel (Vector3DType & colinearDir, VectorType & modelValue, unsigned int threadId) [protected, pure virtual]
Initialize first direction from user input (model dependent, not implemented here)
Implemented in anima::DTIProbabilisticTractographyImageFilter, and anima::ODFProbabilisticTractographyImageFilter.
Referenced by ComputeFiber().
bool anima::BaseProbabilisticTractographyImageFilter::MergeParticleClassFibers (FiberWorkType & fiberData, FiberProcessVectorType & outputMerged, unsigned int classNumber) [protected]
This guy takes the result of computefiber and merges the classes, each one becomes one fiber.
Definition at line 1218 of file animaBaseProbabilisticTractographyImageFilter.cxx.
References anima::BaseProbabilisticTractographyImageFilter::FiberWorkType::classSizes, anima::BaseProbabilisticTractographyImageFilter::FiberWorkType::fiberParticles, anima::BaseProbabilisticTractographyImageFilter::FiberWorkType::particleWeights, anima::BaseProbabilisticTractographyImageFilter::FiberWorkType::reverseClassMemberships, and anima::BaseProbabilisticTractographyImageFilter::FiberWorkType::stoppedParticles.
Referenced by ComputeFiber(), and UpdateClassesMemberships().
void anima::BaseProbabilisticTractographyImageFilter::PrepareTractography () [protected, virtual]
Generate seed points (can be re-implemented but this one has to be called)
Reimplemented in anima::ODFProbabilisticTractographyImageFilter, and anima::DTIProbabilisticTractographyImageFilter.
Definition at line 122 of file animaBaseProbabilisticTractographyImageFilter.cxx.
References Back, Bottom, Center, Front, Outward, and Top.
Referenced by Update().
virtual Vector3DType anima::BaseProbabilisticTractographyImageFilter::ProposeNewDirection (Vector3DType & oldDirection, VectorType & modelValue, Vector3DType & sampling_direction, double & log_prior, double & log_proposal, std::mt19937 & random_generator, unsigned int threadId) [protected, pure virtual]
Propose new direction for a particle, given the old direction, and a model (model dependent, not implemented here)
Implemented in anima::DTIProbabilisticTractographyImageFilter, and anima::ODFProbabilisticTractographyImageFilter.
Referenced by ComputeFiber().
void anima::BaseProbabilisticTractographyImageFilter::SetBValuesList (ListType bValuesList) [inline]
Definition at line 139 of file animaBaseProbabilisticTractographyImageFilter.h.
virtual void anima::BaseProbabilisticTractographyImageFilter::SetClusterDistance (unsigned int _arg) [virtual]
virtual void anima::BaseProbabilisticTractographyImageFilter::SetComputeLocalColors (bool _arg) [virtual]
virtual void anima::BaseProbabilisticTractographyImageFilter::SetCutMask (MaskImageType * _arg) [virtual]
virtual void anima::BaseProbabilisticTractographyImageFilter::SetFiberTrashThreshold (double _arg) [virtual]
virtual void anima::BaseProbabilisticTractographyImageFilter::SetFilterMask (MaskImageType * _arg) [virtual]
virtual void anima::BaseProbabilisticTractographyImageFilter::SetForbiddenMask (MaskImageType * _arg) [virtual]
void anima::BaseProbabilisticTractographyImageFilter::SetInitialColinearityDirection (const ColinearityDirectionType & colDir) [inline]
Definition at line 121 of file animaBaseProbabilisticTractographyImageFilter.h.
void anima::BaseProbabilisticTractographyImageFilter::SetInitialDirectionMode (const InitialDirectionModeType & dir) [inline]
Definition at line 122 of file animaBaseProbabilisticTractographyImageFilter.h.
void anima::BaseProbabilisticTractographyImageFilter::SetInputImagesFrom4DImage (Input4DImageType * in4DImage)
Definition at line 1349 of file animaBaseProbabilisticTractographyImageFilter.cxx.
virtual void anima::BaseProbabilisticTractographyImageFilter::SetKappaOfPriorDistribution (double _arg) [virtual]
virtual void anima::BaseProbabilisticTractographyImageFilter::SetKappaSplitThreshold (double _arg) [virtual]
virtual void anima::BaseProbabilisticTractographyImageFilter::SetMAPMergeFibers (bool _arg) [virtual]
virtual void anima::BaseProbabilisticTractographyImageFilter::SetMaxLengthFiber (double _arg) [virtual]
virtual void anima::BaseProbabilisticTractographyImageFilter::SetMinimalNumberOfParticlesPerClass (unsigned int _arg) [virtual]
virtual void anima::BaseProbabilisticTractographyImageFilter::SetMinLengthFiber (double _arg) [virtual]
virtual void anima::BaseProbabilisticTractographyImageFilter::SetModelDimension (unsigned int _arg) [virtual]
Referenced by anima::DTIProbabilisticTractographyImageFilter::DTIProbabilisticTractographyImageFilter(), anima::ODFProbabilisticTractographyImageFilter::ODFProbabilisticTractographyImageFilter(), and anima::ODFProbabilisticTractographyImageFilter::SetODFSHOrder().
virtual void anima::BaseProbabilisticTractographyImageFilter::SetNumberOfFibersPerPixel (unsigned int _arg) [virtual]
virtual void anima::BaseProbabilisticTractographyImageFilter::SetNumberOfParticles (unsigned int _arg) [virtual]
virtual void anima::BaseProbabilisticTractographyImageFilter::SetPositionDistanceFuseThreshold (double _arg) [virtual]
virtual void anima::BaseProbabilisticTractographyImageFilter::SetResamplingThreshold (double _arg) [virtual]
virtual void anima::BaseProbabilisticTractographyImageFilter::SetSeedMask (MaskImageType * _arg) [virtual]
virtual void anima::BaseProbabilisticTractographyImageFilter::SetStepProgression (double _arg) [virtual]
void anima::BaseProbabilisticTractographyImageFilter::ThreadedTrackComputer (unsigned int numThread, FiberProcessVectorType & resultFibers, ListType & resultWeights, unsigned int startSeedIndex, unsigned int endSeedIndex) [protected]
Doing the real tracking by calling ComputeFiber and merging its results.
Definition at line 289 of file animaBaseProbabilisticTractographyImageFilter.cxx.
References ComputeFiber(), ComputeModelEstimation(), and FilterOutputFibers().
Referenced by ThreadTrack().
void anima::BaseProbabilisticTractographyImageFilter::ThreadTrack (unsigned int numThread, FiberProcessVectorType & resultFibers, ListType & resultWeights) [protected]
Doing the thread work dispatch.
Definition at line 251 of file animaBaseProbabilisticTractographyImageFilter.cxx.
References ThreadedTrackComputer().
Referenced by ThreadTracker().
ITK_THREAD_RETURN_TYPE anima::BaseProbabilisticTractographyImageFilter::ThreadTracker (void * arg) [static, protected]
Multithread util function.
Definition at line 240 of file animaBaseProbabilisticTractographyImageFilter.cxx.
References anima::BaseProbabilisticTractographyImageFilter::trackerArguments::resultFibersFromThreads, anima::BaseProbabilisticTractographyImageFilter::trackerArguments::resultWeightsFromThreads, ThreadTrack(), and anima::BaseProbabilisticTractographyImageFilter::trackerArguments::trackerPtr.
Referenced by Update().
void anima::BaseProbabilisticTractographyImageFilter::Update ()
Definition at line 76 of file animaBaseProbabilisticTractographyImageFilter.cxx.
References createVTKOutput(), PrepareTractography(), anima::BaseProbabilisticTractographyImageFilter::trackerArguments::resultFibersFromThreads, anima::BaseProbabilisticTractographyImageFilter::trackerArguments::resultWeightsFromThreads, ThreadTracker(), and anima::BaseProbabilisticTractographyImageFilter::trackerArguments::trackerPtr.
unsigned int anima::BaseProbabilisticTractographyImageFilter::UpdateClassesMemberships (FiberWorkType & fiberData, DirectionVectorType & directions, std::mt19937 & random_generator) [protected]
This ugly guy is the heart of multi-modal probabilistic tractography, making decisions on split and merges of particles.
Definition at line 851 of file animaBaseProbabilisticTractographyImageFilter.cxx.
References anima::BaseProbabilisticTractographyImageFilter::FiberWorkType::classMemberships, anima::BaseProbabilisticTractographyImageFilter::FiberWorkType::classSizes, anima::BaseProbabilisticTractographyImageFilter::FiberWorkType::classWeights, anima::ComputeEuclideanDistance(), anima::ComputeModifiedDirectedHausdorffDistance(), anima::ComputePointToSetDistance(), anima::BaseProbabilisticTractographyImageFilter::FiberWorkType::fiberParticles, MergeParticleClassFibers(), anima::BaseProbabilisticTractographyImageFilter::FiberWorkType::particleWeights, anima::BaseProbabilisticTractographyImageFilter::FiberWorkType::reverseClassMemberships, and anima::safe_log().
Referenced by ComputeFiber().
The documentation for this class was generated from the following files:
animaBaseProbabilisticTractographyImageFilter.h
animaBaseProbabilisticTractographyImageFilter.cxx