ANIMA: anima::BaseOrientedModelImageToImageMetric< TFixedImage, TMovingImage > Class Template Reference
anima::BaseOrientedModelImageToImageMetric< TFixedImage, TMovingImage > Class Template Reference
#include <animaBaseOrientedModelImageToImageMetric.h>
Public Types
typedef itk::SmartPointer
< const Self > ConstPointer
typedef
Superclass::ParametersValueType CoordinateRepresentationType
typedef Superclass::DerivativeType DerivativeType
typedef
FixedImageType::ConstPointer FixedImageConstPointer
typedef
FixedImageMaskType::ConstPointer FixedImageMaskConstPointer
typedef FixedImageMaskType::Pointer FixedImageMaskPointer
typedef itk::SpatialObject
< itkGetStaticConstMacro(FixedImageDimension) > FixedImageMaskType
typedef FixedImageType::RegionType FixedImageRegionType
typedef TFixedImage FixedImageType
typedef
TransformType::InputPointType InputPointType
typedef InterpolatorType::Pointer InterpolatorPointer
typedef
itk::InterpolateImageFunction
< MovingImageType,
CoordinateRepresentationType > InterpolatorType
typedef Superclass::MeasureType MeasureType
enum ModelReorientationType {
NONE = 0,
FINITE_STRAIN,
PPD
}
typedef
MovingImageType::ConstPointer MovingImageConstPointer
typedef
MovingImageMaskType::ConstPointer MovingImageMaskConstPointer
typedef
MovingImageMaskType::Pointer MovingImageMaskPointer
typedef itk::SpatialObject
< itkGetStaticConstMacro(MovingImageDimension) > MovingImageMaskType
typedef TMovingImage::PixelType MovingImagePixelType
typedef TMovingImage MovingImageType
typedef
TransformType::OutputPointType OutputPointType
typedef Superclass::ParametersType ParametersType
typedef itk::SmartPointer< Self > Pointer
typedef double RealType
typedef
BaseOrientedModelImageToImageMetric Self
typedef
itk::SingleValuedCostFunction Superclass
typedef TransformType::JacobianType TransformJacobianType
typedef
TransformType::ParametersType TransformParametersType
typedef TransformType::Pointer TransformPointer
typedef itk::Transform
< CoordinateRepresentationType,
itkGetStaticConstMacro(MovingImageDimension),
itkGetStaticConstMacro(FixedImageDimension)> TransformType
Public Member Functions
void GetDerivative (const ParametersType &parameters, DerivativeType &derivative) const ITK_OVERRIDE
Should not be used.
virtual const FixedImageType * GetFixedImage () const
virtual const FixedImageMaskType * GetFixedImageMask () const
virtual const
FixedImageRegionType & GetFixedImageRegion () const
virtual const InterpolatorType * GetInterpolator () const
virtual ModelReorientationType GetModelRotation () const
virtual const MovingImageType * GetMovingImage () const
virtual const MovingImageMaskType * GetMovingImageMask () const
virtual const char * GetNameOfClass () const
unsigned int GetNumberOfParameters (void) const ITK_OVERRIDE
virtual const unsigned long & GetNumberOfPixelsCounted () const
virtual const TransformType * GetTransform () const
void GetValueAndDerivative (const TransformParametersType &parameters, MeasureType &value, DerivativeType &derivative) const ITK_OVERRIDE
virtual void Initialize () throw (itk::ExceptionObject)
virtual void SetFixedImage (const FixedImageType *_arg)
virtual void SetFixedImageMask (FixedImageMaskType *_arg)
virtual void SetFixedImageMask (const FixedImageMaskType *_arg)
virtual void SetFixedImageRegion (FixedImageRegionType _arg)
virtual void SetInterpolator (InterpolatorType *_arg)
virtual void SetModelRotation (ModelReorientationType _arg)
virtual void SetMovingImage (const MovingImageType *_arg)
virtual void SetMovingImageMask (MovingImageMaskType *_arg)
virtual void SetMovingImageMask (const MovingImageMaskType *_arg)
virtual void SetTransform (TransformType *_arg)
void SetTransformParameters (const ParametersType &parameters) const
Static Public Attributes
static const unsigned int FixedImageDimension = TFixedImage::ImageDimension
static const unsigned int MovingImageDimension = TMovingImage::ImageDimension
Protected Member Functions
BaseOrientedModelImageToImageMetric ()
void PrintSelf (std::ostream &os, itk::Indent indent) const ITK_OVERRIDE
virtual ~BaseOrientedModelImageToImageMetric ()
Protected Attributes
FixedImageConstPointer m_FixedImage
FixedImageMaskConstPointer m_FixedImageMask
InterpolatorPointer m_Interpolator
MovingImageConstPointer m_MovingImage
MovingImageMaskConstPointer m_MovingImageMask
unsigned long m_NumberOfPixelsCounted
vnl_matrix< double > m_OrientationMatrix
TransformPointer m_Transform
Detailed Description
template<class TFixedImage, class TMovingImage>
class anima::BaseOrientedModelImageToImageMetric< TFixedImage, TMovingImage >
Definition at line 13 of file animaBaseOrientedModelImageToImageMetric.h.
Member Typedef Documentation
template<class TFixedImage, class TMovingImage> typedef itk::SmartPointer<const Self> anima::BaseOrientedModelImageToImageMetric< TFixedImage, TMovingImage >::ConstPointer
Reimplemented in anima::TensorCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >, anima::TensorGeneralizedCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >, and anima::TensorMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >.
Definition at line 20 of file animaBaseOrientedModelImageToImageMetric.h.
template<class TFixedImage, class TMovingImage> typedef Superclass::ParametersValueType anima::BaseOrientedModelImageToImageMetric< TFixedImage, TMovingImage >::CoordinateRepresentationType
Type used for representing point components
Reimplemented in anima::TensorMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >, anima::TensorCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >, and anima::TensorGeneralizedCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >.
Definition at line 23 of file animaBaseOrientedModelImageToImageMetric.h.
template<class TFixedImage, class TMovingImage> typedef Superclass::DerivativeType anima::BaseOrientedModelImageToImageMetric< TFixedImage, TMovingImage >::DerivativeType
Type of the derivative.
Definition at line 82 of file animaBaseOrientedModelImageToImageMetric.h.
template<class TFixedImage, class TMovingImage> typedef FixedImageType::ConstPointer anima::BaseOrientedModelImageToImageMetric< TFixedImage, TMovingImage >::FixedImageConstPointer
Reimplemented in anima::TensorCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >, anima::TensorGeneralizedCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >, and anima::TensorMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >.
Definition at line 35 of file animaBaseOrientedModelImageToImageMetric.h.
template<class TFixedImage, class TMovingImage> typedef FixedImageMaskType::ConstPointer anima::BaseOrientedModelImageToImageMetric< TFixedImage, TMovingImage >::FixedImageMaskConstPointer
Definition at line 66 of file animaBaseOrientedModelImageToImageMetric.h.
template<class TFixedImage, class TMovingImage> typedef FixedImageMaskType::Pointer anima::BaseOrientedModelImageToImageMetric< TFixedImage, TMovingImage >::FixedImageMaskPointer
Definition at line 65 of file animaBaseOrientedModelImageToImageMetric.h.
template<class TFixedImage, class TMovingImage> typedef itk::SpatialObject< itkGetStaticConstMacro(FixedImageDimension) > anima::BaseOrientedModelImageToImageMetric< TFixedImage, TMovingImage >::FixedImageMaskType
Type for the mask of the fixed image. Only pixels that are "inside" this mask will be considered for the computation of the metric
Definition at line 64 of file animaBaseOrientedModelImageToImageMetric.h.
template<class TFixedImage, class TMovingImage> typedef FixedImageType::RegionType anima::BaseOrientedModelImageToImageMetric< TFixedImage, TMovingImage >::FixedImageRegionType
Definition at line 36 of file animaBaseOrientedModelImageToImageMetric.h.
template<class TFixedImage, class TMovingImage> typedef TFixedImage anima::BaseOrientedModelImageToImageMetric< TFixedImage, TMovingImage >::FixedImageType
Type of the fixed Image.
Reimplemented in anima::TensorCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >, anima::TensorGeneralizedCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >, and anima::TensorMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >.
Definition at line 34 of file animaBaseOrientedModelImageToImageMetric.h.
template<class TFixedImage, class TMovingImage> typedef TransformType::InputPointType anima::BaseOrientedModelImageToImageMetric< TFixedImage, TMovingImage >::InputPointType
Reimplemented in anima::TensorCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >, anima::TensorGeneralizedCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >, and anima::TensorMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >.
Definition at line 49 of file animaBaseOrientedModelImageToImageMetric.h.
template<class TFixedImage, class TMovingImage> typedef InterpolatorType::Pointer anima::BaseOrientedModelImageToImageMetric< TFixedImage, TMovingImage >::InterpolatorPointer
Definition at line 59 of file animaBaseOrientedModelImageToImageMetric.h.
template<class TFixedImage, class TMovingImage> typedef itk::InterpolateImageFunction< MovingImageType, CoordinateRepresentationType > anima::BaseOrientedModelImageToImageMetric< TFixedImage, TMovingImage >::InterpolatorType
Type of the Interpolator Base class
Definition at line 57 of file animaBaseOrientedModelImageToImageMetric.h.
template<class TFixedImage, class TMovingImage> typedef Superclass::MeasureType anima::BaseOrientedModelImageToImageMetric< TFixedImage, TMovingImage >::MeasureType
Type of the measure.
Reimplemented in anima::TensorCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >, anima::TensorGeneralizedCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >, and anima::TensorMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >.
Definition at line 79 of file animaBaseOrientedModelImageToImageMetric.h.
template<class TFixedImage, class TMovingImage> typedef MovingImageType::ConstPointer anima::BaseOrientedModelImageToImageMetric< TFixedImage, TMovingImage >::MovingImageConstPointer
Reimplemented in anima::TensorCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >, anima::TensorGeneralizedCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >, and anima::TensorMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >.
Definition at line 31 of file animaBaseOrientedModelImageToImageMetric.h.
template<class TFixedImage, class TMovingImage> typedef MovingImageMaskType::ConstPointer anima::BaseOrientedModelImageToImageMetric< TFixedImage, TMovingImage >::MovingImageMaskConstPointer
Definition at line 74 of file animaBaseOrientedModelImageToImageMetric.h.
template<class TFixedImage, class TMovingImage> typedef MovingImageMaskType::Pointer anima::BaseOrientedModelImageToImageMetric< TFixedImage, TMovingImage >::MovingImageMaskPointer
Definition at line 73 of file animaBaseOrientedModelImageToImageMetric.h.
template<class TFixedImage, class TMovingImage> typedef itk::SpatialObject< itkGetStaticConstMacro(MovingImageDimension) > anima::BaseOrientedModelImageToImageMetric< TFixedImage, TMovingImage >::MovingImageMaskType
Type for the mask of the moving image. Only pixels that are "inside" this mask will be considered for the computation of the metric
Definition at line 72 of file animaBaseOrientedModelImageToImageMetric.h.
template<class TFixedImage, class TMovingImage> typedef TMovingImage::PixelType anima::BaseOrientedModelImageToImageMetric< TFixedImage, TMovingImage >::MovingImagePixelType
Definition at line 30 of file animaBaseOrientedModelImageToImageMetric.h.
template<class TFixedImage, class TMovingImage> typedef TMovingImage anima::BaseOrientedModelImageToImageMetric< TFixedImage, TMovingImage >::MovingImageType
Type of the moving Image.
Reimplemented in anima::TensorCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >, anima::TensorGeneralizedCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >, and anima::TensorMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >.
Definition at line 29 of file animaBaseOrientedModelImageToImageMetric.h.
template<class TFixedImage, class TMovingImage> typedef TransformType::OutputPointType anima::BaseOrientedModelImageToImageMetric< TFixedImage, TMovingImage >::OutputPointType
Reimplemented in anima::TensorCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >, anima::TensorGeneralizedCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >, and anima::TensorMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >.
Definition at line 50 of file animaBaseOrientedModelImageToImageMetric.h.
template<class TFixedImage, class TMovingImage> typedef Superclass::ParametersType anima::BaseOrientedModelImageToImageMetric< TFixedImage, TMovingImage >::ParametersType
Type of the parameters.
Definition at line 85 of file animaBaseOrientedModelImageToImageMetric.h.
template<class TFixedImage, class TMovingImage> typedef itk::SmartPointer<Self> anima::BaseOrientedModelImageToImageMetric< TFixedImage, TMovingImage >::Pointer
Reimplemented in anima::TensorCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >, anima::TensorGeneralizedCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >, and anima::TensorMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >.
Definition at line 19 of file animaBaseOrientedModelImageToImageMetric.h.
template<class TFixedImage, class TMovingImage> typedef double anima::BaseOrientedModelImageToImageMetric< TFixedImage, TMovingImage >::RealType
Definition at line 76 of file animaBaseOrientedModelImageToImageMetric.h.
template<class TFixedImage, class TMovingImage> typedef BaseOrientedModelImageToImageMetric anima::BaseOrientedModelImageToImageMetric< TFixedImage, TMovingImage >::Self
Standard class typedefs.
Reimplemented in anima::TensorCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >, anima::TensorGeneralizedCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >, and anima::TensorMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >.
Definition at line 17 of file animaBaseOrientedModelImageToImageMetric.h.
template<class TFixedImage, class TMovingImage> typedef itk::SingleValuedCostFunction anima::BaseOrientedModelImageToImageMetric< TFixedImage, TMovingImage >::Superclass
Reimplemented in anima::TensorCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >, anima::TensorGeneralizedCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >, and anima::TensorMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >.
Definition at line 18 of file animaBaseOrientedModelImageToImageMetric.h.
template<class TFixedImage, class TMovingImage> typedef TransformType::JacobianType anima::BaseOrientedModelImageToImageMetric< TFixedImage, TMovingImage >::TransformJacobianType
Definition at line 52 of file animaBaseOrientedModelImageToImageMetric.h.
template<class TFixedImage, class TMovingImage> typedef TransformType::ParametersType anima::BaseOrientedModelImageToImageMetric< TFixedImage, TMovingImage >::TransformParametersType
Reimplemented in anima::TensorCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >, anima::TensorGeneralizedCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >, and anima::TensorMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >.
Definition at line 51 of file animaBaseOrientedModelImageToImageMetric.h.
template<class TFixedImage, class TMovingImage> typedef TransformType::Pointer anima::BaseOrientedModelImageToImageMetric< TFixedImage, TMovingImage >::TransformPointer
Reimplemented in anima::TensorCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >, anima::TensorGeneralizedCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >, and anima::TensorMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >.
Definition at line 48 of file animaBaseOrientedModelImageToImageMetric.h.
template<class TFixedImage, class TMovingImage> typedef itk::Transform<CoordinateRepresentationType, itkGetStaticConstMacro(MovingImageDimension), itkGetStaticConstMacro(FixedImageDimension)> anima::BaseOrientedModelImageToImageMetric< TFixedImage, TMovingImage >::TransformType
Type of the Transform Base class
Reimplemented in anima::TensorCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >, anima::TensorGeneralizedCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >, and anima::TensorMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >.
Definition at line 46 of file animaBaseOrientedModelImageToImageMetric.h.
Member Enumeration Documentation
template<class TFixedImage, class TMovingImage> enum anima::BaseOrientedModelImageToImageMetric::ModelReorientationType
Enumerator:
NONE
FINITE_STRAIN
PPD
Definition at line 154 of file animaBaseOrientedModelImageToImageMetric.h.
Constructor & Destructor Documentation
template<class TFixedImage , class TMovingImage > anima::BaseOrientedModelImageToImageMetric< TFixedImage, TMovingImage >::BaseOrientedModelImageToImageMetric () [protected]
Constructor
Definition at line 14 of file animaBaseOrientedModelImageToImageMetric.hxx.
template<class TFixedImage , class TMovingImage > anima::BaseOrientedModelImageToImageMetric< TFixedImage, TMovingImage >::~BaseOrientedModelImageToImageMetric () [protected, virtual]
Destructor
Definition at line 31 of file animaBaseOrientedModelImageToImageMetric.hxx.
Member Function Documentation
template<class TFixedImage, class TMovingImage> void anima::BaseOrientedModelImageToImageMetric< TFixedImage, TMovingImage >::GetDerivative (const ParametersType & parameters, DerivativeType & derivative) const [inline]
Should not be used.
Definition at line 142 of file animaBaseOrientedModelImageToImageMetric.h.
template<class TFixedImage, class TMovingImage> virtual const FixedImageType* anima::BaseOrientedModelImageToImageMetric< TFixedImage, TMovingImage >::GetFixedImage () const [virtual]
Get the Fixed Image.
template<class TFixedImage, class TMovingImage> virtual const FixedImageMaskType* anima::BaseOrientedModelImageToImageMetric< TFixedImage, TMovingImage >::GetFixedImageMask () const [virtual]
template<class TFixedImage, class TMovingImage> virtual const FixedImageRegionType& anima::BaseOrientedModelImageToImageMetric< TFixedImage, TMovingImage >::GetFixedImageRegion () const [virtual]
Get the region over which the metric will be computed
template<class TFixedImage, class TMovingImage> virtual const InterpolatorType* anima::BaseOrientedModelImageToImageMetric< TFixedImage, TMovingImage >::GetInterpolator () const [virtual]
Get a pointer to the Interpolator.
template<class TFixedImage, class TMovingImage> virtual ModelReorientationType anima::BaseOrientedModelImageToImageMetric< TFixedImage, TMovingImage >::GetModelRotation () const [virtual]
template<class TFixedImage, class TMovingImage> virtual const MovingImageType* anima::BaseOrientedModelImageToImageMetric< TFixedImage, TMovingImage >::GetMovingImage () const [virtual]
Get the Moving Image.
template<class TFixedImage, class TMovingImage> virtual const MovingImageMaskType* anima::BaseOrientedModelImageToImageMetric< TFixedImage, TMovingImage >::GetMovingImageMask () const [virtual]
template<class TFixedImage, class TMovingImage> virtual const char* anima::BaseOrientedModelImageToImageMetric< TFixedImage, TMovingImage >::GetNameOfClass () const [virtual]
Run-time type information (and related methods).
Reimplemented in anima::TensorCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >, anima::TensorGeneralizedCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >, and anima::TensorMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >.
template<class TFixedImage, class TMovingImage> unsigned int anima::BaseOrientedModelImageToImageMetric< TFixedImage, TMovingImage >::GetNumberOfParameters (void) const [inline]
Return the number of parameters required by the Transform
Definition at line 134 of file animaBaseOrientedModelImageToImageMetric.h.
template<class TFixedImage, class TMovingImage> virtual const unsigned long& anima::BaseOrientedModelImageToImageMetric< TFixedImage, TMovingImage >::GetNumberOfPixelsCounted () const [virtual]
Get the number of pixels considered in the computation.
template<class TFixedImage, class TMovingImage> virtual const TransformType* anima::BaseOrientedModelImageToImageMetric< TFixedImage, TMovingImage >::GetTransform () const [virtual]
Get a pointer to the Transform.
template<class TFixedImage, class TMovingImage> void anima::BaseOrientedModelImageToImageMetric< TFixedImage, TMovingImage >::GetValueAndDerivative (const TransformParametersType & parameters, MeasureType & value, DerivativeType & derivative) const [inline]
Definition at line 148 of file animaBaseOrientedModelImageToImageMetric.h.
template<class TFixedImage , class TMovingImage > void anima::BaseOrientedModelImageToImageMetric< TFixedImage, TMovingImage >::Initialize (void) throw (itk::ExceptionObject) [virtual]
Initialize the Metric by making sure that all the components are present and plugged together correctly
Initialize
Definition at line 74 of file animaBaseOrientedModelImageToImageMetric.hxx.
template<class TFixedImage , class TMovingImage > void anima::BaseOrientedModelImageToImageMetric< TFixedImage, TMovingImage >::PrintSelf (std::ostream & os, itk::Indent indent) const [protected]
PrintSelf
Reimplemented in anima::TensorGeneralizedCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >, and anima::TensorCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >.
Definition at line 135 of file animaBaseOrientedModelImageToImageMetric.hxx.
template<class TFixedImage, class TMovingImage> virtual void anima::BaseOrientedModelImageToImageMetric< TFixedImage, TMovingImage >::SetFixedImage (const FixedImageType * _arg) [virtual]
Connect the Fixed Image.
template<class TFixedImage, class TMovingImage> virtual void anima::BaseOrientedModelImageToImageMetric< TFixedImage, TMovingImage >::SetFixedImageMask (FixedImageMaskType * _arg) [virtual]
Set/Get the fixed image mask.
template<class TFixedImage, class TMovingImage> virtual void anima::BaseOrientedModelImageToImageMetric< TFixedImage, TMovingImage >::SetFixedImageMask (const FixedImageMaskType * _arg) [virtual]
template<class TFixedImage, class TMovingImage> virtual void anima::BaseOrientedModelImageToImageMetric< TFixedImage, TMovingImage >::SetFixedImageRegion (FixedImageRegionType _arg) [virtual]
Set the region over which the metric will be computed
Referenced by anima::TensorBlockMatcher< TInputImageType >::BlockMatchingSetup().
template<class TFixedImage, class TMovingImage> virtual void anima::BaseOrientedModelImageToImageMetric< TFixedImage, TMovingImage >::SetInterpolator (InterpolatorType * _arg) [virtual]
Connect the Interpolator.
template<class TFixedImage, class TMovingImage> virtual void anima::BaseOrientedModelImageToImageMetric< TFixedImage, TMovingImage >::SetModelRotation (ModelReorientationType _arg) [virtual]
Referenced by anima::TensorBlockMatcher< TInputImageType >::SetupMetric().
template<class TFixedImage, class TMovingImage> virtual void anima::BaseOrientedModelImageToImageMetric< TFixedImage, TMovingImage >::SetMovingImage (const MovingImageType * _arg) [virtual]
Connect the Moving Image.
template<class TFixedImage, class TMovingImage> virtual void anima::BaseOrientedModelImageToImageMetric< TFixedImage, TMovingImage >::SetMovingImageMask (MovingImageMaskType * _arg) [virtual]
Set/Get the moving image mask.
template<class TFixedImage, class TMovingImage> virtual void anima::BaseOrientedModelImageToImageMetric< TFixedImage, TMovingImage >::SetMovingImageMask (const MovingImageMaskType * _arg) [virtual]
template<class TFixedImage, class TMovingImage> virtual void anima::BaseOrientedModelImageToImageMetric< TFixedImage, TMovingImage >::SetTransform (TransformType * _arg) [virtual]
Connect the Transform.
template<class TFixedImage , class TMovingImage > void anima::BaseOrientedModelImageToImageMetric< TFixedImage, TMovingImage >::SetTransformParameters (const ParametersType & parameters) const
Set the parameters defining the Transform.
Set the parameters that define a unique transform
Definition at line 43 of file animaBaseOrientedModelImageToImageMetric.hxx.
References anima::ExtractRotationFromJacobianMatrix().
Member Data Documentation
template<class TFixedImage, class TMovingImage> const unsigned int anima::BaseOrientedModelImageToImageMetric< TFixedImage, TMovingImage >::FixedImageDimension = TFixedImage::ImageDimension [static]
Definition at line 40 of file animaBaseOrientedModelImageToImageMetric.h.
template<class TFixedImage, class TMovingImage> FixedImageConstPointer anima::BaseOrientedModelImageToImageMetric< TFixedImage, TMovingImage >::m_FixedImage [protected]
Definition at line 171 of file animaBaseOrientedModelImageToImageMetric.h.
template<class TFixedImage, class TMovingImage> FixedImageMaskConstPointer anima::BaseOrientedModelImageToImageMetric< TFixedImage, TMovingImage >::m_FixedImageMask [protected]
Definition at line 178 of file animaBaseOrientedModelImageToImageMetric.h.
template<class TFixedImage, class TMovingImage> InterpolatorPointer anima::BaseOrientedModelImageToImageMetric< TFixedImage, TMovingImage >::m_Interpolator [protected]
Definition at line 176 of file animaBaseOrientedModelImageToImageMetric.h.
template<class TFixedImage, class TMovingImage> MovingImageConstPointer anima::BaseOrientedModelImageToImageMetric< TFixedImage, TMovingImage >::m_MovingImage [protected]
Definition at line 172 of file animaBaseOrientedModelImageToImageMetric.h.
template<class TFixedImage, class TMovingImage> MovingImageMaskConstPointer anima::BaseOrientedModelImageToImageMetric< TFixedImage, TMovingImage >::m_MovingImageMask [protected]
Definition at line 179 of file animaBaseOrientedModelImageToImageMetric.h.
template<class TFixedImage, class TMovingImage> unsigned long anima::BaseOrientedModelImageToImageMetric< TFixedImage, TMovingImage >::m_NumberOfPixelsCounted [mutable, protected]
Definition at line 169 of file animaBaseOrientedModelImageToImageMetric.h.
template<class TFixedImage, class TMovingImage> vnl_matrix<double> anima::BaseOrientedModelImageToImageMetric< TFixedImage, TMovingImage >::m_OrientationMatrix [mutable, protected]
Definition at line 175 of file animaBaseOrientedModelImageToImageMetric.h.
template<class TFixedImage, class TMovingImage> TransformPointer anima::BaseOrientedModelImageToImageMetric< TFixedImage, TMovingImage >::m_Transform [mutable, protected]
Definition at line 174 of file animaBaseOrientedModelImageToImageMetric.h.
Referenced by anima::BaseOrientedModelImageToImageMetric< itk::VectorImage< TFixedImagePixelType, ImageDimension >, itk::VectorImage< TMovingImagePixelType, ImageDimension > >::GetNumberOfParameters().
template<class TFixedImage, class TMovingImage> const unsigned int anima::BaseOrientedModelImageToImageMetric< TFixedImage, TMovingImage >::MovingImageDimension = TMovingImage::ImageDimension [static]
Constants for the image dimensions
Definition at line 39 of file animaBaseOrientedModelImageToImageMetric.h.
The documentation for this class was generated from the following files:
animaBaseOrientedModelImageToImageMetric.h
animaBaseOrientedModelImageToImageMetric.hxx