ANIMA: anima::GcStremMsLesionsSegmentationFilter< TInputImage > Class Template Reference
anima::GcStremMsLesionsSegmentationFilter< TInputImage > Class Template Reference
#include <animaGcStremMsLesionsSegmentationFilter.h>
Public Types
typedef
itk::BinaryThresholdImageFilter
< ImageTypeD, ImageTypeUC > BinaryThresholdImageFilterType_F_UC
typedef
itk::BinaryThresholdImageFilter
< ImageTypeUC, ImageTypeUC > BinaryThresholdImageFilterType_UC_UC
typedef
anima::CheckStructureNeighborFilter
< ImageTypeUC, ImageTypeUC > CheckStructureNeighborFilterFilterType
typedef
anima::ComputeMahalanobisImagesFilter
< ImageTypeUC, ImageTypeUC,
ImageTypeD > ComputeMahalanobisImagesFilterType
typedef anima::ComputeSolution
< ImageTypeUC, ImageTypeUC,
ImageTypeD > ComputeSolutionType
typedef
itk::ConnectedComponentImageFilter
< ImageTypeUC, ImageTypeInt > ConnectedComponentType
typedef itk::SmartPointer
< const Self > ConstPointer
typedef
itk::Statistics::GaussianMembershipFunction
< MeasurementVectorType > GaussianFunctionType
typedef anima::GraphCutFilter
< TInputImage, ImageTypeUC > GraphCutFilterType
typedef
itk::ImageRegionConstIterator
< InputImageType > ImageIteratorTypeConstInput
typedef
itk::ImageRegionConstIterator
< ImageTypeUC > ImageIteratorTypeConstUC
typedef
itk::ImageRegionIterator
< ImageTypeD > ImageIteratorTypeD
typedef
itk::ImageRegionIterator
< ImageTypeInt > ImageIteratorTypeInt
typedef
itk::ImageRegionIterator
< ImageTypeUC > ImageIteratorTypeUC
typedef itk::Image< PixelTypeD, 3 > ImageTypeD
typedef itk::Image
< PixelTypeInt, 3 > ImageTypeInt
typedef itk::Image
< PixelTypeUC, 3 > ImageTypeUC
typedef TInputImage InputImageType
typedef
itk::IntensityWindowingImageFilter
< ImageTypeUC, ImageTypeD > IntensityWindowingImageFilterType
typedef itk::MaskImageFilter
< ImageTypeD, ImageTypeUC > MaskFilterType_F_UC
typedef itk::MaskImageFilter
< ImageTypeUC, ImageTypeUC > MaskFilterType_UC_UC
typedef
itk::MaximumImageFilter
< ImageTypeD, ImageTypeD,
ImageTypeD > MaximumFilterType
typedef
itk::VariableLengthVector
< double > MeasurementVectorType
typedef
itk::MinimumImageFilter
< ImageTypeD, ImageTypeD,
ImageTypeD > MinimumFilterTypeF
typedef
itk::MinimumImageFilter
< ImageTypeUC, ImageTypeUC,
ImageTypeUC > MinimumFilterTypeUC
typedef OutputImageType::Pointer OutputImagePointer
typedef TOutputImage OutputImageType
typedef
itk::ImageRegionIterator
< OutputImageType > OutputIteratorType
typedef OutputImageType::PixelType OutputPixelType
typedef double PixelTypeD
typedef int PixelTypeInt
typedef unsigned char PixelTypeUC
typedef itk::SmartPointer< Self > Pointer
typedef
itk::RelabelComponentImageFilter
< ImageTypeInt, ImageTypeInt > RelabelComponentType
typedef
anima::RemoveTouchingBorderFilter
< ImageTypeUC, ImageTypeUC,
ImageTypeUC > RemoveTouchingBorderFilterType
typedef
itk::RescaleIntensityImageFilter
< TInputImage, ImageTypeUC > RescaleFilterType
typedef
GcStremMsLesionsSegmentationFilter Self
typedef
itk::ImageToImageFilter
< TInputImage, TOutputImage > Superclass
typedef anima::TLinksFilter
< TInputImage, ImageTypeD > TLinksFilterType
typedef itk::Image< unsigned
char, 3 > TOutputImage
Public Member Functions
void ApplyHeuristicRules ()
void CheckInputImages ()
void ComputeAutomaticInitialization ()
void ComputeNABT ()
virtual ::itk::LightObject::Pointer CreateAnother (void) const
void CreateFuzzyRuleImage ()
void GenerateData () ITK_OVERRIDE
virtual double GetAlpha ()
virtual bool GetEM_before_concentration ()
virtual int GetEmIter ()
virtual int GetEmIter_concentration ()
std::string GetFuzzyOutputObjectFilename ()
virtual double GetFuzzyRuleMax ()
virtual double GetFuzzyRuleMin ()
virtual unsigned int GetInitMethodType ()
virtual double GetIntensityDPFactor ()
virtual double GetIntensityFLAIRFactor ()
virtual double GetIntensityT2Factor ()
LesionSegmentationType GetLesionSegmentationType ()
virtual double GetMahalanobisThCSF ()
virtual double GetMahalanobisThGM ()
virtual double GetMahalanobisThWM ()
std::string GetMatrixGradFilename ()
virtual double GetMinDistance ()
virtual double GetMinLesionsSize ()
virtual double GetMultiVarSinks ()
virtual double GetMultiVarSources ()
virtual const char * GetNameOfClass () const
TOutputImage * GetOutputCSF ()
std::string GetOutputCSFFilename ()
itk::Image< double, 3 > * GetOutputFuzzyObjectImage ()
std::string GetOutputGCFilename ()
TOutputImage * GetOutputGM ()
std::string GetOutputGMFilename ()
TOutputImage * GetOutputGraphCut ()
TOutputImage * GetOutputIntensityImage1 ()
std::string GetOutputIntensityImage1Filename ()
TOutputImage * GetOutputIntensityImage2 ()
std::string GetOutputIntensityImage2Filename ()
std::string GetOutputLesionFile ()
TOutputImage * GetOutputLesions ()
std::string GetOutputMahaCSFFilename ()
itk::Image< double, 3 > * GetOutputMahaCSFImage ()
std::string GetOutputMahaGMFilename ()
itk::Image< double, 3 > * GetOutputMahaGMImage ()
std::string GetOutputMahaMaximumFilename ()
itk::Image< double, 3 > * GetOutputMahaMaximumImage ()
std::string GetOutputMahaMinimumFilename ()
itk::Image< double, 3 > * GetOutputMahaMinimumImage ()
std::string GetOutputMahaWMFilename ()
itk::Image< double, 3 > * GetOutputMahaWMImage ()
TOutputImage * GetOutputStrem ()
TOutputImage * GetOutputStremCSF ()
std::string GetOutputStremCSFFilename ()
std::string GetOutputStremFilename ()
TOutputImage * GetOutputStremGM ()
std::string GetOutputStremGMFilename ()
TOutputImage * GetOutputStremWM ()
std::string GetOutputStremWMFilename ()
std::string GetOutputWholeFilename ()
TOutputImage * GetOutputWholeSeg ()
TOutputImage * GetOutputWM ()
std::string GetOutputWMFilename ()
virtual double GetRatioContourWM ()
virtual double GetRejRatio ()
virtual double GetRejRatioHierar ()
virtual bool GetRemoveBorder ()
virtual double GetSigma ()
std::vector
< GaussianFunctionType::Pointer > GetSolution ()
virtual double GetThresoldWMmap ()
virtual bool GetUseDP ()
virtual bool GetUseFLAIR ()
virtual bool GetUseSpecGrad ()
virtual bool GetUseT2 ()
virtual bool GetVerbose ()
void GraphCut ()
void RescaleImages ()
virtual void SetAlpha (double _arg)
virtual void SetEM_before_concentration (bool _arg)
virtual void SetEmIter (int _arg)
virtual void SetEmIter_concentration (int _arg)
virtual void SetFuzzyRuleMax (double _arg)
virtual void SetFuzzyRuleMin (double _arg)
void SetGaussianModel (std::vector< GaussianFunctionType::Pointer > solution)
virtual void SetInitMethodType (unsigned int _arg)
void SetInputCSFAtlas (const ImageTypeD *image)
void SetInputGMAtlas (const ImageTypeD *image)
void SetInputImageDP (const InputImageType *image)
void SetInputImageFLAIR (const InputImageType *image)
void SetInputImageT1 (const InputImageType *image)
void SetInputImageT1Gd (const InputImageType *image)
void SetInputImageT2 (const InputImageType *image)
void SetInputWMAtlas (const ImageTypeD *image)
virtual void SetIntensityDPFactor (double _arg)
virtual void SetIntensityFLAIRFactor (double _arg)
virtual void SetIntensityT2Factor (double _arg)
void SetLesionSegmentationType (LesionSegmentationType type)
virtual void SetMahalanobisThCSF (double _arg)
virtual void SetMahalanobisThGM (double _arg)
virtual void SetMahalanobisThWM (double _arg)
void SetMask (const TInputImage *MaskImage)
void SetMatrixGradFilename (std::string fn)
virtual void SetMinDistance (double _arg)
virtual void SetMinLesionsSize (double _arg)
virtual void SetMultiVarSinks (double _arg)
virtual void SetMultiVarSources (double _arg)
void SetOutputCSFFilename (std::string fn)
void SetOutputFuzzyObjectFilename (std::string fn)
void SetOutputGCFilename (std::string fn)
void SetOutputGMFilename (std::string fn)
void SetOutputIntensityImage1Filename (std::string fn)
void SetOutputIntensityImage2Filename (std::string fn)
void SetOutputLesionFilename (std::string fn)
void SetOutputMahaCSFFilename (std::string fn)
void SetOutputMahaGMFilename (std::string fn)
void SetOutputMahaMaximumFilename (std::string fn)
void SetOutputMahaMinimumFilename (std::string fn)
void SetOutputMahaWMFilename (std::string fn)
void SetOutputStremCSFFilename (std::string fn)
void SetOutputStremFilename (std::string fn)
void SetOutputStremGMFilename (std::string fn)
void SetOutputStremWMFilename (std::string fn)
void SetOutputWholeFilename (std::string fn)
void SetOutputWMFilename (std::string fn)
virtual void SetRatioContourWM (double _arg)
virtual void SetRejRatio (double _arg)
virtual void SetRejRatioHierar (double _arg)
virtual void SetRemoveBorder (bool _arg)
virtual void SetSigma (double _arg)
void SetSinksMask (const ImageTypeUC *MaskImage)
void SetSolutionReadFilename (std::string fn)
void SetSolutionWriteFilename (std::string fn)
void SetSourcesMask (const ImageTypeUC *MaskImage)
virtual void SetThresoldWMmap (double _arg)
void SetTol (const double tol)
virtual void SetUseDP (bool _arg)
virtual void SetUseFLAIR (bool _arg)
virtual void SetUseSpecGrad (bool _arg)
virtual void SetUseT2 (bool _arg)
virtual void SetVerbose (bool _arg)
void StremThreshold ()
void WriteOutputs ()
Static Public Member Functions
static Pointer New ()
Protected Member Functions
void EmitProgress (int prog)
GcStremMsLesionsSegmentationFilter ()
ImageTypeD::ConstPointer GetInputCSFAtlas ()
ImageTypeD::ConstPointer GetInputGMAtlas ()
InputImageType::ConstPointer GetInputImageDP ()
InputImageType::ConstPointer GetInputImageFLAIR ()
InputImageType::ConstPointer GetInputImageT1 ()
InputImageType::ConstPointer GetInputImageT1Gd ()
InputImageType::ConstPointer GetInputImageT2 ()
ImageTypeD::ConstPointer GetInputWMAtlas ()
InputImageType::ConstPointer GetMask ()
ImageTypeUC::ConstPointer GetSinksMask ()
ImageTypeUC::ConstPointer GetSourcesMask ()
itk::DataObject::Pointer MakeOutput (unsigned int idx)
~GcStremMsLesionsSegmentationFilter ()
Static Protected Member Functions
static void ManageProgress (itk::Object *caller, const itk::EventObject &event, void *clientData)
Protected Attributes
MaximumFilterType::Pointer m_FilterMaxSinks
MaximumFilterType::Pointer m_FilterMaxSources
GraphCutFilterType::Pointer m_GraphCutFilter
ComputeMahalanobisImagesFilterType::Pointer m_MahalanobisFilter
TLinksFilterType::Pointer m_TLinksFilter
Detailed Description
template<typename TInputImage>
class anima::GcStremMsLesionsSegmentationFilter< TInputImage >
Definition at line 72 of file animaGcStremMsLesionsSegmentationFilter.h.
Member Typedef Documentation
template<typename TInputImage > typedef itk::BinaryThresholdImageFilter<ImageTypeD, ImageTypeUC> anima::GcStremMsLesionsSegmentationFilter< TInputImage >::BinaryThresholdImageFilterType_F_UC
Definition at line 127 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > typedef itk::BinaryThresholdImageFilter<ImageTypeUC, ImageTypeUC> anima::GcStremMsLesionsSegmentationFilter< TInputImage >::BinaryThresholdImageFilterType_UC_UC
Definition at line 128 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > typedef anima::CheckStructureNeighborFilter< ImageTypeUC,ImageTypeUC > anima::GcStremMsLesionsSegmentationFilter< TInputImage >::CheckStructureNeighborFilterFilterType
Definition at line 117 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > typedef anima::ComputeMahalanobisImagesFilter<ImageTypeUC,ImageTypeUC,ImageTypeD> anima::GcStremMsLesionsSegmentationFilter< TInputImage >::ComputeMahalanobisImagesFilterType
Definition at line 120 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > typedef anima::ComputeSolution<ImageTypeUC,ImageTypeUC, ImageTypeD> anima::GcStremMsLesionsSegmentationFilter< TInputImage >::ComputeSolutionType
Definition at line 121 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > typedef itk::ConnectedComponentImageFilter<ImageTypeUC,ImageTypeInt> anima::GcStremMsLesionsSegmentationFilter< TInputImage >::ConnectedComponentType
Definition at line 132 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > typedef itk::SmartPointer<const Self> anima::GcStremMsLesionsSegmentationFilter< TInputImage >::ConstPointer
Definition at line 81 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > typedef itk::Statistics::GaussianMembershipFunction< MeasurementVectorType > anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GaussianFunctionType
Definition at line 113 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > typedef anima::GraphCutFilter< TInputImage, ImageTypeUC > anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GraphCutFilterType
Define filters.
Definition at line 116 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > typedef itk::ImageRegionConstIterator<InputImageType> anima::GcStremMsLesionsSegmentationFilter< TInputImage >::ImageIteratorTypeConstInput
Definition at line 91 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > typedef itk::ImageRegionConstIterator<ImageTypeUC> anima::GcStremMsLesionsSegmentationFilter< TInputImage >::ImageIteratorTypeConstUC
Definition at line 102 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > typedef itk::ImageRegionIterator<ImageTypeD> anima::GcStremMsLesionsSegmentationFilter< TInputImage >::ImageIteratorTypeD
Definition at line 106 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > typedef itk::ImageRegionIterator<ImageTypeInt> anima::GcStremMsLesionsSegmentationFilter< TInputImage >::ImageIteratorTypeInt
Definition at line 110 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > typedef itk::ImageRegionIterator<ImageTypeUC> anima::GcStremMsLesionsSegmentationFilter< TInputImage >::ImageIteratorTypeUC
Definition at line 101 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > typedef itk::Image<PixelTypeD,3> anima::GcStremMsLesionsSegmentationFilter< TInputImage >::ImageTypeD
Definition at line 105 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > typedef itk::Image<PixelTypeInt,3> anima::GcStremMsLesionsSegmentationFilter< TInputImage >::ImageTypeInt
Definition at line 109 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > typedef itk::Image<PixelTypeUC,3> anima::GcStremMsLesionsSegmentationFilter< TInputImage >::ImageTypeUC
Definition at line 100 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > typedef TInputImage anima::GcStremMsLesionsSegmentationFilter< TInputImage >::InputImageType
Type of the input images.
Definition at line 87 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > typedef itk::IntensityWindowingImageFilter<ImageTypeUC, ImageTypeD> anima::GcStremMsLesionsSegmentationFilter< TInputImage >::IntensityWindowingImageFilterType
Definition at line 129 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > typedef itk::MaskImageFilter< ImageTypeD, ImageTypeUC > anima::GcStremMsLesionsSegmentationFilter< TInputImage >::MaskFilterType_F_UC
Definition at line 131 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > typedef itk::MaskImageFilter< ImageTypeUC, ImageTypeUC > anima::GcStremMsLesionsSegmentationFilter< TInputImage >::MaskFilterType_UC_UC
Definition at line 130 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > typedef itk::MaximumImageFilter<ImageTypeD,ImageTypeD,ImageTypeD> anima::GcStremMsLesionsSegmentationFilter< TInputImage >::MaximumFilterType
Definition at line 124 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > typedef itk::VariableLengthVector<double> anima::GcStremMsLesionsSegmentationFilter< TInputImage >::MeasurementVectorType
Definition at line 112 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > typedef itk::MinimumImageFilter<ImageTypeD,ImageTypeD,ImageTypeD> anima::GcStremMsLesionsSegmentationFilter< TInputImage >::MinimumFilterTypeF
Definition at line 125 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > typedef itk::MinimumImageFilter<ImageTypeUC,ImageTypeUC,ImageTypeUC> anima::GcStremMsLesionsSegmentationFilter< TInputImage >::MinimumFilterTypeUC
Definition at line 126 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > typedef OutputImageType::Pointer anima::GcStremMsLesionsSegmentationFilter< TInputImage >::OutputImagePointer
Definition at line 95 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > typedef TOutputImage anima::GcStremMsLesionsSegmentationFilter< TInputImage >::OutputImageType
Type of the output images.
Definition at line 94 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > typedef itk::ImageRegionIterator< OutputImageType > anima::GcStremMsLesionsSegmentationFilter< TInputImage >::OutputIteratorType
Definition at line 96 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > typedef OutputImageType::PixelType anima::GcStremMsLesionsSegmentationFilter< TInputImage >::OutputPixelType
Definition at line 97 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > typedef double anima::GcStremMsLesionsSegmentationFilter< TInputImage >::PixelTypeD
Definition at line 104 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > typedef int anima::GcStremMsLesionsSegmentationFilter< TInputImage >::PixelTypeInt
Definition at line 108 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > typedef unsigned char anima::GcStremMsLesionsSegmentationFilter< TInputImage >::PixelTypeUC
Definition at line 99 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > typedef itk::SmartPointer<Self> anima::GcStremMsLesionsSegmentationFilter< TInputImage >::Pointer
Definition at line 80 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > typedef itk::RelabelComponentImageFilter< ImageTypeInt, ImageTypeInt > anima::GcStremMsLesionsSegmentationFilter< TInputImage >::RelabelComponentType
Definition at line 133 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > typedef anima::RemoveTouchingBorderFilter<ImageTypeUC,ImageTypeUC,ImageTypeUC> anima::GcStremMsLesionsSegmentationFilter< TInputImage >::RemoveTouchingBorderFilterType
Definition at line 118 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > typedef itk::RescaleIntensityImageFilter<TInputImage,ImageTypeUC> anima::GcStremMsLesionsSegmentationFilter< TInputImage >::RescaleFilterType
Definition at line 123 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > typedef GcStremMsLesionsSegmentationFilter anima::GcStremMsLesionsSegmentationFilter< TInputImage >::Self
Standard class typedefs.
Definition at line 77 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > typedef itk::ImageToImageFilter< TInputImage, TOutputImage > anima::GcStremMsLesionsSegmentationFilter< TInputImage >::Superclass
Definition at line 79 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > typedef anima::TLinksFilter<TInputImage,ImageTypeD> anima::GcStremMsLesionsSegmentationFilter< TInputImage >::TLinksFilterType
Definition at line 119 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > typedef itk::Image<unsigned char, 3> anima::GcStremMsLesionsSegmentationFilter< TInputImage >::TOutputImage
Definition at line 78 of file animaGcStremMsLesionsSegmentationFilter.h.
Constructor & Destructor Documentation
template<typename TInputImage > anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GcStremMsLesionsSegmentationFilter () [inline, protected]
Definition at line 353 of file animaGcStremMsLesionsSegmentationFilter.h.
References anima::GcStremMsLesionsSegmentationFilter< TInputImage >::m_FilterMaxSinks, anima::GcStremMsLesionsSegmentationFilter< TInputImage >::m_FilterMaxSources, anima::GcStremMsLesionsSegmentationFilter< TInputImage >::m_GraphCutFilter, anima::GcStremMsLesionsSegmentationFilter< TInputImage >::m_MahalanobisFilter, anima::GcStremMsLesionsSegmentationFilter< TInputImage >::m_TLinksFilter, anima::GcStremMsLesionsSegmentationFilter< TInputImage >::MakeOutput(), anima::GraphCutFilter< TInput, TOutput >::New(), anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::New(), anima::TLinksFilter< TInput, TOutput >::New(), anima::GcStremMsLesionsSegmentationFilter< TInputImage >::New(), and strem.
template<typename TInputImage > anima::GcStremMsLesionsSegmentationFilter< TInputImage >::~GcStremMsLesionsSegmentationFilter () [inline, protected]
Definition at line 447 of file animaGcStremMsLesionsSegmentationFilter.h.
Member Function Documentation
template<typename TInputImage > void anima::GcStremMsLesionsSegmentationFilter< TInputImage >::ApplyHeuristicRules ()
Intensity Rule: MS lesions are known to be hyperintense compared to the WM intensity on T2-w and PD-w and FLAIR sequences. We use the information given by the NABT model to define hyper-intensity. A voxel is considered to be hyper-intense for a given sequence if its intensity y is greater than a threshold T that is defined by the probability of the Gaussian distribution and an intensity factor intensityFactor: For example the hyperintensity threshold T in T2 is defined as: T = meanT2 + intensityFactor * stdT2 meanT2 and stdT2 being the mean and standard deviation of the white matter in the sequence T2. If the voxel is not considered hyper-intense on T2-w, PD and FLAIR, it is discarded as a lesion voxel.
Size Rule: In order to avoid false positives, candidate lesions smaller than 9 mm3 in size are rejected. These small candidate lesions are usually produced by noise or flow artifacts. In clinical practice, lesions must have a radius of 3 mm on one image slice to be considered as such.
Definition at line 856 of file animaGcStremMsLesionsSegmentationFilter.hxx.
References HierarchicalDP, and manualGC.
template<typename TInputImage > void anima::GcStremMsLesionsSegmentationFilter< TInputImage >::CheckInputImages ()
Definition at line 377 of file animaGcStremMsLesionsSegmentationFilter.hxx.
References manualGC.
template<typename TInputImage > void anima::GcStremMsLesionsSegmentationFilter< TInputImage >::ComputeAutomaticInitialization ()
Definition at line 532 of file animaGcStremMsLesionsSegmentationFilter.hxx.
template<typename TInputImage > void anima::GcStremMsLesionsSegmentationFilter< TInputImage >::ComputeNABT ()
Definition at line 1086 of file animaGcStremMsLesionsSegmentationFilter.hxx.
References manualGC.
template<typename TInputImage > virtual::itk::LightObject::Pointer anima::GcStremMsLesionsSegmentationFilter< TInputImage >::CreateAnother (void) const
template<typename TInputImage > void anima::GcStremMsLesionsSegmentationFilter< TInputImage >::CreateFuzzyRuleImage ()
Definition at line 693 of file animaGcStremMsLesionsSegmentationFilter.hxx.
template<typename TInputImage > void anima::GcStremMsLesionsSegmentationFilter< TInputImage >::EmitProgress (int prog) [protected]
template<typename TInputImage > void anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GenerateData ()
Definition at line 1189 of file animaGcStremMsLesionsSegmentationFilter.hxx.
References manualGC, and strem.
template<typename TInputImage > virtual double anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GetAlpha () [virtual]
template<typename TInputImage > virtual bool anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GetEM_before_concentration () [virtual]
template<typename TInputImage > virtual int anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GetEmIter () [virtual]
template<typename TInputImage > virtual int anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GetEmIter_concentration () [virtual]
template<typename TInputImage > std::string anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GetFuzzyOutputObjectFilename () [inline]
Definition at line 311 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > virtual double anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GetFuzzyRuleMax () [virtual]
template<typename TInputImage > virtual double anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GetFuzzyRuleMin () [virtual]
template<typename TInputImage > virtual unsigned int anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GetInitMethodType () [virtual]
template<typename TInputImage > itk::Image< double, 3 >::ConstPointer anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GetInputCSFAtlas () [protected]
Definition at line 144 of file animaGcStremMsLesionsSegmentationFilter.hxx.
template<typename TInputImage > itk::Image< double, 3 >::ConstPointer anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GetInputGMAtlas () [protected]
Definition at line 151 of file animaGcStremMsLesionsSegmentationFilter.hxx.
template<typename TInputImage > TInputImage::ConstPointer anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GetInputImageDP () [protected]
Definition at line 123 of file animaGcStremMsLesionsSegmentationFilter.hxx.
template<typename TInputImage > TInputImage::ConstPointer anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GetInputImageFLAIR () [protected]
Definition at line 130 of file animaGcStremMsLesionsSegmentationFilter.hxx.
template<typename TInputImage > TInputImage::ConstPointer anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GetInputImageT1 () [protected]
Definition at line 109 of file animaGcStremMsLesionsSegmentationFilter.hxx.
template<typename TInputImage > TInputImage::ConstPointer anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GetInputImageT1Gd () [protected]
Definition at line 136 of file animaGcStremMsLesionsSegmentationFilter.hxx.
template<typename TInputImage > TInputImage::ConstPointer anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GetInputImageT2 () [protected]
Definition at line 116 of file animaGcStremMsLesionsSegmentationFilter.hxx.
template<typename TInputImage > itk::Image< double, 3 >::ConstPointer anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GetInputWMAtlas () [protected]
Definition at line 158 of file animaGcStremMsLesionsSegmentationFilter.hxx.
template<typename TInputImage > virtual double anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GetIntensityDPFactor () [virtual]
template<typename TInputImage > virtual double anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GetIntensityFLAIRFactor () [virtual]
template<typename TInputImage > virtual double anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GetIntensityT2Factor () [virtual]
template<typename TInputImage > LesionSegmentationType anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GetLesionSegmentationType () [inline]
Definition at line 278 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > virtual double anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GetMahalanobisThCSF () [virtual]
template<typename TInputImage > virtual double anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GetMahalanobisThGM () [virtual]
template<typename TInputImage > virtual double anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GetMahalanobisThWM () [virtual]
template<typename TInputImage > TInputImage::ConstPointer anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GetMask () [protected]
Definition at line 102 of file animaGcStremMsLesionsSegmentationFilter.hxx.
template<typename TInputImage > std::string anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GetMatrixGradFilename () [inline]
Definition at line 341 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > virtual double anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GetMinDistance () [virtual]
template<typename TInputImage > virtual double anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GetMinLesionsSize () [virtual]
template<typename TInputImage > virtual double anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GetMultiVarSinks () [virtual]
template<typename TInputImage > virtual double anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GetMultiVarSources () [virtual]
template<typename TInputImage > virtual const char* anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GetNameOfClass () const [virtual]
Run-time type information (and related methods)
template<typename TInputImage > itk::Image< unsigned char, 3 > * anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GetOutputCSF ()
Definition at line 205 of file animaGcStremMsLesionsSegmentationFilter.hxx.
template<typename TInputImage > std::string anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GetOutputCSFFilename () [inline]
Definition at line 284 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > itk::Image< double, 3 > * anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GetOutputFuzzyObjectImage ()
Definition at line 255 of file animaGcStremMsLesionsSegmentationFilter.hxx.
template<typename TInputImage > std::string anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GetOutputGCFilename () [inline]
Definition at line 296 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > itk::Image< unsigned char, 3 > * anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GetOutputGM ()
Definition at line 210 of file animaGcStremMsLesionsSegmentationFilter.hxx.
template<typename TInputImage > std::string anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GetOutputGMFilename () [inline]
Definition at line 287 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > itk::Image< unsigned char, 3 > * anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GetOutputGraphCut ()
Definition at line 285 of file animaGcStremMsLesionsSegmentationFilter.hxx.
template<typename TInputImage > itk::Image< unsigned char, 3 > * anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GetOutputIntensityImage1 ()
Definition at line 245 of file animaGcStremMsLesionsSegmentationFilter.hxx.
template<typename TInputImage > std::string anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GetOutputIntensityImage1Filename () [inline]
Definition at line 329 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > itk::Image< unsigned char, 3 > * anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GetOutputIntensityImage2 ()
Definition at line 250 of file animaGcStremMsLesionsSegmentationFilter.hxx.
template<typename TInputImage > std::string anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GetOutputIntensityImage2Filename () [inline]
Definition at line 332 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > std::string anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GetOutputLesionFile () [inline]
Definition at line 281 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > itk::Image< unsigned char, 3 > * anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GetOutputLesions ()
Definition at line 200 of file animaGcStremMsLesionsSegmentationFilter.hxx.
template<typename TInputImage > std::string anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GetOutputMahaCSFFilename () [inline]
Definition at line 314 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > itk::Image< double, 3 > * anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GetOutputMahaCSFImage ()
Definition at line 260 of file animaGcStremMsLesionsSegmentationFilter.hxx.
template<typename TInputImage > std::string anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GetOutputMahaGMFilename () [inline]
Definition at line 317 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > itk::Image< double, 3 > * anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GetOutputMahaGMImage ()
Definition at line 265 of file animaGcStremMsLesionsSegmentationFilter.hxx.
template<typename TInputImage > std::string anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GetOutputMahaMaximumFilename () [inline]
Definition at line 323 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > itk::Image< double, 3 > * anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GetOutputMahaMaximumImage ()
Definition at line 280 of file animaGcStremMsLesionsSegmentationFilter.hxx.
template<typename TInputImage > std::string anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GetOutputMahaMinimumFilename () [inline]
Definition at line 326 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > itk::Image< double, 3 > * anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GetOutputMahaMinimumImage ()
Definition at line 275 of file animaGcStremMsLesionsSegmentationFilter.hxx.
template<typename TInputImage > std::string anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GetOutputMahaWMFilename () [inline]
Definition at line 320 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > itk::Image< double, 3 > * anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GetOutputMahaWMImage ()
Definition at line 270 of file animaGcStremMsLesionsSegmentationFilter.hxx.
template<typename TInputImage > itk::Image< unsigned char, 3 > * anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GetOutputStrem ()
Definition at line 225 of file animaGcStremMsLesionsSegmentationFilter.hxx.
template<typename TInputImage > itk::Image< unsigned char, 3 > * anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GetOutputStremCSF ()
Definition at line 230 of file animaGcStremMsLesionsSegmentationFilter.hxx.
template<typename TInputImage > std::string anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GetOutputStremCSFFilename () [inline]
Definition at line 302 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > std::string anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GetOutputStremFilename () [inline]
Definition at line 299 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > itk::Image< unsigned char, 3 > * anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GetOutputStremGM ()
Definition at line 235 of file animaGcStremMsLesionsSegmentationFilter.hxx.
template<typename TInputImage > std::string anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GetOutputStremGMFilename () [inline]
Definition at line 305 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > itk::Image< unsigned char, 3 > * anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GetOutputStremWM ()
Definition at line 240 of file animaGcStremMsLesionsSegmentationFilter.hxx.
template<typename TInputImage > std::string anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GetOutputStremWMFilename () [inline]
Definition at line 308 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > std::string anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GetOutputWholeFilename () [inline]
Definition at line 293 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > itk::Image< unsigned char, 3 > * anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GetOutputWholeSeg ()
Definition at line 220 of file animaGcStremMsLesionsSegmentationFilter.hxx.
template<typename TInputImage > itk::Image< unsigned char, 3 > * anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GetOutputWM ()
Definition at line 215 of file animaGcStremMsLesionsSegmentationFilter.hxx.
template<typename TInputImage > std::string anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GetOutputWMFilename () [inline]
Definition at line 290 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > virtual double anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GetRatioContourWM () [virtual]
template<typename TInputImage > virtual double anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GetRejRatio () [virtual]
template<typename TInputImage > virtual double anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GetRejRatioHierar () [virtual]
template<typename TInputImage > virtual bool anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GetRemoveBorder () [virtual]
template<typename TInputImage > virtual double anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GetSigma () [virtual]
template<typename TInputImage > itk::Image< unsigned char, 3 >::ConstPointer anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GetSinksMask () [protected]
Definition at line 171 of file animaGcStremMsLesionsSegmentationFilter.hxx.
template<typename TInputImage > std::vector<GaussianFunctionType::Pointer> anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GetSolution () [inline]
Definition at line 336 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > itk::Image< unsigned char, 3 >::ConstPointer anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GetSourcesMask () [protected]
Definition at line 165 of file animaGcStremMsLesionsSegmentationFilter.hxx.
template<typename TInputImage > virtual double anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GetThresoldWMmap () [virtual]
template<typename TInputImage > virtual bool anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GetUseDP () [virtual]
template<typename TInputImage > virtual bool anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GetUseFLAIR () [virtual]
template<typename TInputImage > virtual bool anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GetUseSpecGrad () [virtual]
template<typename TInputImage > virtual bool anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GetUseT2 () [virtual]
template<typename TInputImage > virtual bool anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GetVerbose () [virtual]
template<typename TInputImage > void anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GraphCut ()
Definition at line 763 of file animaGcStremMsLesionsSegmentationFilter.hxx.
References gcemAndManualGC, manualGC, anima::GcStremMsLesionsSegmentationFilter< TInputImage >::SetAlpha(), singleGaussianTLink, and stremTLink.
template<typename TInputImage > itk::DataObject::Pointer anima::GcStremMsLesionsSegmentationFilter< TInputImage >::MakeOutput (unsigned int idx) [protected]
Create the Output
Definition at line 179 of file animaGcStremMsLesionsSegmentationFilter.hxx.
Referenced by anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GcStremMsLesionsSegmentationFilter().
template<typename TInputImage > static void anima::GcStremMsLesionsSegmentationFilter< TInputImage >::ManageProgress (itk::Object * caller, const itk::EventObject & event, void * clientData) [static, protected]
template<typename TInputImage > static Pointer anima::GcStremMsLesionsSegmentationFilter< TInputImage >::New () [static]
Method for creation through the object factory.
Referenced by anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GcStremMsLesionsSegmentationFilter().
template<typename TInputImage > void anima::GcStremMsLesionsSegmentationFilter< TInputImage >::RescaleImages (void)
Definition at line 425 of file animaGcStremMsLesionsSegmentationFilter.hxx.
References manualGC.
template<typename TInputImage > virtual void anima::GcStremMsLesionsSegmentationFilter< TInputImage >::SetAlpha (double _arg) [virtual]
Referenced by anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GraphCut().
template<typename TInputImage > virtual void anima::GcStremMsLesionsSegmentationFilter< TInputImage >::SetEM_before_concentration (bool _arg) [virtual]
template<typename TInputImage > virtual void anima::GcStremMsLesionsSegmentationFilter< TInputImage >::SetEmIter (int _arg) [virtual]
template<typename TInputImage > virtual void anima::GcStremMsLesionsSegmentationFilter< TInputImage >::SetEmIter_concentration (int _arg) [virtual]
template<typename TInputImage > virtual void anima::GcStremMsLesionsSegmentationFilter< TInputImage >::SetFuzzyRuleMax (double _arg) [virtual]
template<typename TInputImage > virtual void anima::GcStremMsLesionsSegmentationFilter< TInputImage >::SetFuzzyRuleMin (double _arg) [virtual]
template<typename TInputImage > void anima::GcStremMsLesionsSegmentationFilter< TInputImage >::SetGaussianModel (std::vector< GaussianFunctionType::Pointer > solution) [inline]
Definition at line 335 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > virtual void anima::GcStremMsLesionsSegmentationFilter< TInputImage >::SetInitMethodType (unsigned int _arg) [virtual]
Setter/Getter for parameters
template<typename TInputImage > void anima::GcStremMsLesionsSegmentationFilter< TInputImage >::SetInputCSFAtlas (const ImageTypeD * image)
Definition at line 60 of file animaGcStremMsLesionsSegmentationFilter.hxx.
template<typename TInputImage > void anima::GcStremMsLesionsSegmentationFilter< TInputImage >::SetInputGMAtlas (const ImageTypeD * image)
Definition at line 68 of file animaGcStremMsLesionsSegmentationFilter.hxx.
template<typename TInputImage > void anima::GcStremMsLesionsSegmentationFilter< TInputImage >::SetInputImageDP (const InputImageType * image)
Definition at line 33 of file animaGcStremMsLesionsSegmentationFilter.hxx.
template<typename TInputImage > void anima::GcStremMsLesionsSegmentationFilter< TInputImage >::SetInputImageFLAIR (const InputImageType * image)
Definition at line 42 of file animaGcStremMsLesionsSegmentationFilter.hxx.
template<typename TInputImage > void anima::GcStremMsLesionsSegmentationFilter< TInputImage >::SetInputImageT1 (const InputImageType * image)
Setter for images
Definition at line 15 of file animaGcStremMsLesionsSegmentationFilter.hxx.
template<typename TInputImage > void anima::GcStremMsLesionsSegmentationFilter< TInputImage >::SetInputImageT1Gd (const InputImageType * image)
Definition at line 51 of file animaGcStremMsLesionsSegmentationFilter.hxx.
template<typename TInputImage > void anima::GcStremMsLesionsSegmentationFilter< TInputImage >::SetInputImageT2 (const InputImageType * image)
Definition at line 24 of file animaGcStremMsLesionsSegmentationFilter.hxx.
template<typename TInputImage > void anima::GcStremMsLesionsSegmentationFilter< TInputImage >::SetInputWMAtlas (const ImageTypeD * image)
Definition at line 76 of file animaGcStremMsLesionsSegmentationFilter.hxx.
template<typename TInputImage > virtual void anima::GcStremMsLesionsSegmentationFilter< TInputImage >::SetIntensityDPFactor (double _arg) [virtual]
template<typename TInputImage > virtual void anima::GcStremMsLesionsSegmentationFilter< TInputImage >::SetIntensityFLAIRFactor (double _arg) [virtual]
template<typename TInputImage > virtual void anima::GcStremMsLesionsSegmentationFilter< TInputImage >::SetIntensityT2Factor (double _arg) [virtual]
template<typename TInputImage > void anima::GcStremMsLesionsSegmentationFilter< TInputImage >::SetLesionSegmentationType (LesionSegmentationType type) [inline]
Definition at line 279 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > virtual void anima::GcStremMsLesionsSegmentationFilter< TInputImage >::SetMahalanobisThCSF (double _arg) [virtual]
template<typename TInputImage > virtual void anima::GcStremMsLesionsSegmentationFilter< TInputImage >::SetMahalanobisThGM (double _arg) [virtual]
template<typename TInputImage > virtual void anima::GcStremMsLesionsSegmentationFilter< TInputImage >::SetMahalanobisThWM (double _arg) [virtual]
template<typename TInputImage > void anima::GcStremMsLesionsSegmentationFilter< TInputImage >::SetMask (const TInputImage * MaskImage)
Definition at line 7 of file animaGcStremMsLesionsSegmentationFilter.hxx.
template<typename TInputImage > void anima::GcStremMsLesionsSegmentationFilter< TInputImage >::SetMatrixGradFilename (std::string fn) [inline]
Definition at line 342 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > virtual void anima::GcStremMsLesionsSegmentationFilter< TInputImage >::SetMinDistance (double _arg) [virtual]
template<typename TInputImage > virtual void anima::GcStremMsLesionsSegmentationFilter< TInputImage >::SetMinLesionsSize (double _arg) [virtual]
template<typename TInputImage > virtual void anima::GcStremMsLesionsSegmentationFilter< TInputImage >::SetMultiVarSinks (double _arg) [virtual]
template<typename TInputImage > virtual void anima::GcStremMsLesionsSegmentationFilter< TInputImage >::SetMultiVarSources (double _arg) [virtual]
template<typename TInputImage > void anima::GcStremMsLesionsSegmentationFilter< TInputImage >::SetOutputCSFFilename (std::string fn) [inline]
Definition at line 285 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > void anima::GcStremMsLesionsSegmentationFilter< TInputImage >::SetOutputFuzzyObjectFilename (std::string fn) [inline]
Definition at line 312 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > void anima::GcStremMsLesionsSegmentationFilter< TInputImage >::SetOutputGCFilename (std::string fn) [inline]
Definition at line 297 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > void anima::GcStremMsLesionsSegmentationFilter< TInputImage >::SetOutputGMFilename (std::string fn) [inline]
Definition at line 288 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > void anima::GcStremMsLesionsSegmentationFilter< TInputImage >::SetOutputIntensityImage1Filename (std::string fn) [inline]
Definition at line 330 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > void anima::GcStremMsLesionsSegmentationFilter< TInputImage >::SetOutputIntensityImage2Filename (std::string fn) [inline]
Definition at line 333 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > void anima::GcStremMsLesionsSegmentationFilter< TInputImage >::SetOutputLesionFilename (std::string fn) [inline]
Definition at line 282 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > void anima::GcStremMsLesionsSegmentationFilter< TInputImage >::SetOutputMahaCSFFilename (std::string fn) [inline]
Definition at line 315 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > void anima::GcStremMsLesionsSegmentationFilter< TInputImage >::SetOutputMahaGMFilename (std::string fn) [inline]
Definition at line 318 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > void anima::GcStremMsLesionsSegmentationFilter< TInputImage >::SetOutputMahaMaximumFilename (std::string fn) [inline]
Definition at line 324 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > void anima::GcStremMsLesionsSegmentationFilter< TInputImage >::SetOutputMahaMinimumFilename (std::string fn) [inline]
Definition at line 327 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > void anima::GcStremMsLesionsSegmentationFilter< TInputImage >::SetOutputMahaWMFilename (std::string fn) [inline]
Definition at line 321 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > void anima::GcStremMsLesionsSegmentationFilter< TInputImage >::SetOutputStremCSFFilename (std::string fn) [inline]
Definition at line 303 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > void anima::GcStremMsLesionsSegmentationFilter< TInputImage >::SetOutputStremFilename (std::string fn) [inline]
Definition at line 300 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > void anima::GcStremMsLesionsSegmentationFilter< TInputImage >::SetOutputStremGMFilename (std::string fn) [inline]
Definition at line 306 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > void anima::GcStremMsLesionsSegmentationFilter< TInputImage >::SetOutputStremWMFilename (std::string fn) [inline]
Definition at line 309 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > void anima::GcStremMsLesionsSegmentationFilter< TInputImage >::SetOutputWholeFilename (std::string fn) [inline]
Definition at line 294 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > void anima::GcStremMsLesionsSegmentationFilter< TInputImage >::SetOutputWMFilename (std::string fn) [inline]
Definition at line 291 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > virtual void anima::GcStremMsLesionsSegmentationFilter< TInputImage >::SetRatioContourWM (double _arg) [virtual]
template<typename TInputImage > virtual void anima::GcStremMsLesionsSegmentationFilter< TInputImage >::SetRejRatio (double _arg) [virtual]
template<typename TInputImage > virtual void anima::GcStremMsLesionsSegmentationFilter< TInputImage >::SetRejRatioHierar (double _arg) [virtual]
template<typename TInputImage > virtual void anima::GcStremMsLesionsSegmentationFilter< TInputImage >::SetRemoveBorder (bool _arg) [virtual]
template<typename TInputImage > virtual void anima::GcStremMsLesionsSegmentationFilter< TInputImage >::SetSigma (double _arg) [virtual]
template<typename TInputImage > void anima::GcStremMsLesionsSegmentationFilter< TInputImage >::SetSinksMask (const ImageTypeUC * MaskImage)
Definition at line 92 of file animaGcStremMsLesionsSegmentationFilter.hxx.
template<typename TInputImage > void anima::GcStremMsLesionsSegmentationFilter< TInputImage >::SetSolutionReadFilename (std::string fn) [inline]
Definition at line 338 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > void anima::GcStremMsLesionsSegmentationFilter< TInputImage >::SetSolutionWriteFilename (std::string fn) [inline]
Definition at line 339 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > void anima::GcStremMsLesionsSegmentationFilter< TInputImage >::SetSourcesMask (const ImageTypeUC * MaskImage)
Definition at line 84 of file animaGcStremMsLesionsSegmentationFilter.hxx.
template<typename TInputImage > virtual void anima::GcStremMsLesionsSegmentationFilter< TInputImage >::SetThresoldWMmap (double _arg) [virtual]
template<typename TInputImage > void anima::GcStremMsLesionsSegmentationFilter< TInputImage >::SetTol (const double tol) [inline]
Definition at line 184 of file animaGcStremMsLesionsSegmentationFilter.h.
template<typename TInputImage > virtual void anima::GcStremMsLesionsSegmentationFilter< TInputImage >::SetUseDP (bool _arg) [virtual]
template<typename TInputImage > virtual void anima::GcStremMsLesionsSegmentationFilter< TInputImage >::SetUseFLAIR (bool _arg) [virtual]
template<typename TInputImage > virtual void anima::GcStremMsLesionsSegmentationFilter< TInputImage >::SetUseSpecGrad (bool _arg) [virtual]
template<typename TInputImage > virtual void anima::GcStremMsLesionsSegmentationFilter< TInputImage >::SetUseT2 (bool _arg) [virtual]
template<typename TInputImage > virtual void anima::GcStremMsLesionsSegmentationFilter< TInputImage >::SetVerbose (bool _arg) [virtual]
template<typename TInputImage > void anima::GcStremMsLesionsSegmentationFilter< TInputImage >::StremThreshold ()
Definition at line 608 of file animaGcStremMsLesionsSegmentationFilter.hxx.
template<typename TInputImage > void anima::GcStremMsLesionsSegmentationFilter< TInputImage >::WriteOutputs ()
Definition at line 293 of file animaGcStremMsLesionsSegmentationFilter.hxx.
References gcem, gcemAndManualGC, manualGC, strem, and anima::GcStremMsLesionsSegmentationFilter< TInputImage >::WriteOutputs().
Referenced by anima::GcStremMsLesionsSegmentationFilter< TInputImage >::WriteOutputs().
Member Data Documentation
template<typename TInputImage > MaximumFilterType::Pointer anima::GcStremMsLesionsSegmentationFilter< TInputImage >::m_FilterMaxSinks [protected]
Definition at line 350 of file animaGcStremMsLesionsSegmentationFilter.h.
Referenced by anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GcStremMsLesionsSegmentationFilter().
template<typename TInputImage > MaximumFilterType::Pointer anima::GcStremMsLesionsSegmentationFilter< TInputImage >::m_FilterMaxSources [protected]
Definition at line 349 of file animaGcStremMsLesionsSegmentationFilter.h.
Referenced by anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GcStremMsLesionsSegmentationFilter().
template<typename TInputImage > GraphCutFilterType::Pointer anima::GcStremMsLesionsSegmentationFilter< TInputImage >::m_GraphCutFilter [protected]
Definition at line 347 of file animaGcStremMsLesionsSegmentationFilter.h.
Referenced by anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GcStremMsLesionsSegmentationFilter().
template<typename TInputImage > ComputeMahalanobisImagesFilterType::Pointer anima::GcStremMsLesionsSegmentationFilter< TInputImage >::m_MahalanobisFilter [protected]
Definition at line 351 of file animaGcStremMsLesionsSegmentationFilter.h.
Referenced by anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GcStremMsLesionsSegmentationFilter().
template<typename TInputImage > TLinksFilterType::Pointer anima::GcStremMsLesionsSegmentationFilter< TInputImage >::m_TLinksFilter [protected]
Definition at line 348 of file animaGcStremMsLesionsSegmentationFilter.h.
Referenced by anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GcStremMsLesionsSegmentationFilter().
The documentation for this class was generated from the following files:
animaGcStremMsLesionsSegmentationFilter.h
animaGcStremMsLesionsSegmentationFilter.hxx