ANIMA: anima::SphericalHarmonic Class Reference
anima::SphericalHarmonic Class Reference
#include <animaSphericalHarmonic.h>
Public Member Functions
std::complex< double > getPhiFirstDerivative (const double &theta, const double &phi)
std::complex< double > getPhiSecondDerivative (const double &theta, const double &phi)
std::complex< double > getThetaFirstDerivative (const double &theta, const double &phi)
std::complex< double > getThetaPhiDerivative (const double &theta, const double &phi)
std::complex< double > getThetaSecondDerivative (const double &theta, const double &phi)
void SetL (int &l)
void SetM (int &m)
SphericalHarmonic ()
SphericalHarmonic (int &l, int &m)
std::complex< double > Value (const double &theta, const double &phi)
Detailed Description
Definition at line 9 of file animaSphericalHarmonic.h.
Constructor & Destructor Documentation
anima::SphericalHarmonic::SphericalHarmonic ()
Definition at line 11 of file animaSphericalHarmonic.cxx.
anima::SphericalHarmonic::SphericalHarmonic (int & l, int & m)
Definition at line 17 of file animaSphericalHarmonic.cxx.
Member Function Documentation
std::complex< double > anima::SphericalHarmonic::getPhiFirstDerivative (const double & theta, const double & phi)
Definition at line 61 of file animaSphericalHarmonic.cxx.
std::complex< double > anima::SphericalHarmonic::getPhiSecondDerivative (const double & theta, const double & phi)
Definition at line 96 of file animaSphericalHarmonic.cxx.
References Value().
std::complex< double > anima::SphericalHarmonic::getThetaFirstDerivative (const double & theta, const double & phi)
Definition at line 43 of file animaSphericalHarmonic.cxx.
References anima::legendre_first_derivative().
std::complex< double > anima::SphericalHarmonic::getThetaPhiDerivative (const double & theta, const double & phi)
Definition at line 103 of file animaSphericalHarmonic.cxx.
References anima::legendre_first_derivative().
std::complex< double > anima::SphericalHarmonic::getThetaSecondDerivative (const double & theta, const double & phi)
Definition at line 77 of file animaSphericalHarmonic.cxx.
References anima::legendre_first_derivative(), and anima::legendre_second_derivative().
void anima::SphericalHarmonic::SetL (int & l) [inline]
Definition at line 15 of file animaSphericalHarmonic.h.
void anima::SphericalHarmonic::SetM (int & m) [inline]
Definition at line 16 of file animaSphericalHarmonic.h.
std::complex< double > anima::SphericalHarmonic::Value (const double & theta, const double & phi)
Definition at line 23 of file animaSphericalHarmonic.cxx.
Referenced by getPhiSecondDerivative().
The documentation for this class was generated from the following files:
animaSphericalHarmonic.h
animaSphericalHarmonic.cxx