ANIMA: anima::MEstTransformAgregator< NDimensions > Class Template Reference
anima::MEstTransformAgregator< NDimensions > Class Template Reference
#include <animaMEstTransformAgregator.h>
Public Types
typedef
Superclass::BaseInputTransformType BaseInputTransformType
typedef itk::AffineTransform
< ScalarType, NDimensions > BaseOutputTransformType
typedef
Superclass::InternalScalarType InternalScalarType
typedef Superclass::PointType PointType
typedef Superclass::ScalarType ScalarType
typedef BaseTransformAgregator
< NDimensions > Superclass
Public Member Functions
MEstTransformAgregator ()
void SeStoppingThreshold (double stopThr)
void SetMEstimateFactor (double mestFactor)
virtual bool Update ()
virtual ~MEstTransformAgregator ()
Detailed Description
template<unsigned int NDimensions = 3>
class anima::MEstTransformAgregator< NDimensions >
Definition at line 10 of file animaMEstTransformAgregator.h.
Member Typedef Documentation
template<unsigned int NDimensions = 3> typedef Superclass::BaseInputTransformType anima::MEstTransformAgregator< NDimensions >::BaseInputTransformType
Reimplemented from anima::BaseTransformAgregator< NDimensions >.
Definition at line 16 of file animaMEstTransformAgregator.h.
template<unsigned int NDimensions = 3> typedef itk::AffineTransform<ScalarType,NDimensions> anima::MEstTransformAgregator< NDimensions >::BaseOutputTransformType
Reimplemented from anima::BaseTransformAgregator< NDimensions >.
Definition at line 18 of file animaMEstTransformAgregator.h.
template<unsigned int NDimensions = 3> typedef Superclass::InternalScalarType anima::MEstTransformAgregator< NDimensions >::InternalScalarType
Reimplemented from anima::BaseTransformAgregator< NDimensions >.
Definition at line 19 of file animaMEstTransformAgregator.h.
template<unsigned int NDimensions = 3> typedef Superclass::PointType anima::MEstTransformAgregator< NDimensions >::PointType
Reimplemented from anima::BaseTransformAgregator< NDimensions >.
Definition at line 15 of file animaMEstTransformAgregator.h.
template<unsigned int NDimensions = 3> typedef Superclass::ScalarType anima::MEstTransformAgregator< NDimensions >::ScalarType
Reimplemented from anima::BaseTransformAgregator< NDimensions >.
Definition at line 17 of file animaMEstTransformAgregator.h.
template<unsigned int NDimensions = 3> typedef BaseTransformAgregator<NDimensions> anima::MEstTransformAgregator< NDimensions >::Superclass
Definition at line 14 of file animaMEstTransformAgregator.h.
Constructor & Destructor Documentation
template<unsigned int NDimensions> anima::MEstTransformAgregator< NDimensions >::MEstTransformAgregator ()
Definition at line 13 of file animaMEstTransformAgregator.hxx.
template<unsigned int NDimensions = 3> virtual anima::MEstTransformAgregator< NDimensions >::~MEstTransformAgregator () [inline, virtual]
Definition at line 22 of file animaMEstTransformAgregator.h.
Member Function Documentation
template<unsigned int NDimensions = 3> void anima::MEstTransformAgregator< NDimensions >::SeStoppingThreshold (double stopThr) [inline]
Definition at line 27 of file animaMEstTransformAgregator.h.
References anima::BaseTransformAgregator< NDimensions >::SetUpToDate().
template<unsigned int NDimensions = 3> void anima::MEstTransformAgregator< NDimensions >::SetMEstimateFactor (double mestFactor) [inline]
Definition at line 26 of file animaMEstTransformAgregator.h.
References anima::BaseTransformAgregator< NDimensions >::SetUpToDate().
Referenced by anima::PyramidalBlockMatchingBridge< ImageDimension >::Update().
template<unsigned int NDimensions> bool anima::MEstTransformAgregator< NDimensions >::Update () [virtual]
Implements anima::BaseTransformAgregator< NDimensions >.
Definition at line 22 of file animaMEstTransformAgregator.hxx.
The documentation for this class was generated from the following files:
animaMEstTransformAgregator.h
animaMEstTransformAgregator.hxx