ANIMA: anima::BaseBMRegistrationMethod< TInputImageType > Class Template Reference
anima::BaseBMRegistrationMethod< TInputImageType > Class Template Reference
#include <animaBaseBMRegistrationMethod.h>
Public Types
typedef
AffineTransformType::Pointer AffineTransformPointer
typedef itk::AffineTransform
< typename
AgregatorType::ScalarType,
TInputImageType::ImageDimension > AffineTransformType
typedef AgregatorType::ScalarType AgregatorScalarType
typedef
anima::BaseTransformAgregator
< TInputImageType::ImageDimension > AgregatorType
typedef
AgregatorType::BaseInputTransformType BaseInputTransformType
typedef
AgregatorType::BaseOutputTransformType BaseOutputTransformType
typedef
anima::BaseBlockMatcher
< TInputImageType > BlockMatcherType
typedef itk::SmartPointer
< const Self > ConstPointer
typedef
itk::ProcessObject::DataObjectPointerArraySizeType DataObjectPointerArraySizeType
typedef
DisplacementFieldTransformType::Pointer DisplacementFieldTransformPointer
typedef
rpi::DisplacementFieldTransform
< AgregatorScalarType,
TInputImageType::ImageDimension > DisplacementFieldTransformType
typedef
TInputImageType::IOPixelType ImageScalarType
typedef InputImageType::Pointer InputImagePointer
typedef TInputImageType InputImageType
typedef MaskImageType::Pointer MaskImagePointer
typedef itk::Image< unsigned
char,
TInputImageType::ImageDimension > MaskImageType
typedef itk::SmartPointer< Self > Pointer
typedef
ResamplerFilterType::Pointer ResamplerFilterPointer
typedef
itk::ImageToImageFilter
< InputImageType,
InputImageType > ResamplerFilterType
typedef BaseBMRegistrationMethod Self
typedef itk::ProcessObject Superclass
typedef SVFTransformType::Pointer SVFTransformPointer
typedef
itk::StationaryVelocityFieldTransform
< AgregatorScalarType,
TInputImageType::ImageDimension > SVFTransformType
typedef
TransformOutputType::Pointer TransformOutputPointer
typedef
itk::DataObjectDecorator
< TransformType > TransformOutputType
typedef TransformType::Pointer TransformPointer
typedef
AgregatorType::BaseOutputTransformType TransformType
Public Member Functions
void Abort ()
virtual AgregatorType * GetAgregator ()
virtual unsigned int GetBCHCompositionOrder ()
BlockMatcherType * GetBlockMatcher ()
virtual InputImageType * GetFixedImage ()
TransformPointer & GetInitialTransform ()
virtual unsigned int GetMaximumIterations ()
virtual double GetMinimalTransformError ()
virtual InputImageType * GetMovingImage ()
ResamplerFilterPointer & GetMovingImageResampler ()
virtual const char * GetNameOfClass () const
TransformOutputType * GetOutput ()
ResamplerFilterPointer & GetReferenceImageResampler ()
virtual double GetSVFElasticRegSigma ()
virtual bool GetVerboseProgression ()
virtual DataObjectPointer MakeOutput (DataObjectPointerArraySizeType idx) ITK_OVERRIDE
virtual void SetAgregator (AgregatorType *_arg)
virtual void SetBCHCompositionOrder (unsigned int _arg)
void SetBlockMatcher (BlockMatcherType *matcher)
virtual void SetFixedImage (InputImageType *_arg)
virtual void SetInitialTransform (TransformPointer _arg)
virtual void SetMaximumIterations (unsigned int _arg)
virtual void SetMinimalTransformError (double _arg)
virtual void SetMovingImage (InputImageType *_arg)
void SetMovingImageResampler (ResamplerFilterType *filter)
void SetReferenceImageResampler (ResamplerFilterType *filter)
virtual void SetSVFElasticRegSigma (double _arg)
virtual void SetVerboseProgression (bool _arg)
Protected Member Functions
BaseBMRegistrationMethod ()
virtual bool ComposeAddOnWithTransform (TransformPointer &computedTransform, TransformType *addOn)
void GenerateData () ITK_OVERRIDE
virtual void PerformOneIteration (InputImageType *refImage, InputImageType *movingImage, TransformPointer &addOn)=0
virtual void PrintSelf (std::ostream &os, itk::Indent indent) const ITK_OVERRIDE
virtual void ResampleImages (TransformType *currentTransform, InputImagePointer &refImage, InputImagePointer &movingImage)
virtual void SetupTransform (TransformPointer &optimizedTransform)
void StartOptimization ()
virtual ~BaseBMRegistrationMethod ()
Detailed Description
template<typename TInputImageType>
class anima::BaseBMRegistrationMethod< TInputImageType >
Definition at line 24 of file animaBaseBMRegistrationMethod.h.
Member Typedef Documentation
template<typename TInputImageType> typedef AffineTransformType::Pointer anima::BaseBMRegistrationMethod< TInputImageType >::AffineTransformPointer
Definition at line 57 of file animaBaseBMRegistrationMethod.h.
template<typename TInputImageType> typedef itk::AffineTransform<typename AgregatorType::ScalarType, TInputImageType::ImageDimension> anima::BaseBMRegistrationMethod< TInputImageType >::AffineTransformType
Reimplemented in anima::DistortionCorrectionBMRegistrationMethod< TInputImageType >, anima::KissingSymmetricBMRegistrationMethod< TInputImageType >, and anima::SymmetricBMRegistrationMethod< TInputImageType >.
Definition at line 56 of file animaBaseBMRegistrationMethod.h.
template<typename TInputImageType> typedef AgregatorType::ScalarType anima::BaseBMRegistrationMethod< TInputImageType >::AgregatorScalarType
Reimplemented in anima::DistortionCorrectionBMRegistrationMethod< TInputImageType >.
Definition at line 42 of file animaBaseBMRegistrationMethod.h.
template<typename TInputImageType> typedef anima::BaseTransformAgregator<TInputImageType::ImageDimension> anima::BaseBMRegistrationMethod< TInputImageType >::AgregatorType
Type of Transform Agregator
Reimplemented in anima::DistortionCorrectionBMRegistrationMethod< TInputImageType >, anima::KissingSymmetricBMRegistrationMethod< TInputImageType >, anima::SymmetricBMRegistrationMethod< TInputImageType >, and anima::AsymmetricBMRegistrationMethod< TInputImageType >.
Definition at line 39 of file animaBaseBMRegistrationMethod.h.
template<typename TInputImageType> typedef AgregatorType::BaseInputTransformType anima::BaseBMRegistrationMethod< TInputImageType >::BaseInputTransformType
Definition at line 40 of file animaBaseBMRegistrationMethod.h.
template<typename TInputImageType> typedef AgregatorType::BaseOutputTransformType anima::BaseBMRegistrationMethod< TInputImageType >::BaseOutputTransformType
Definition at line 41 of file animaBaseBMRegistrationMethod.h.
template<typename TInputImageType> typedef anima::BaseBlockMatcher<TInputImageType> anima::BaseBMRegistrationMethod< TInputImageType >::BlockMatcherType
Reimplemented in anima::DistortionCorrectionBMRegistrationMethod< TInputImageType >, anima::KissingSymmetricBMRegistrationMethod< TInputImageType >, and anima::SymmetricBMRegistrationMethod< TInputImageType >.
Definition at line 64 of file animaBaseBMRegistrationMethod.h.
template<typename TInputImageType> typedef itk::SmartPointer<const Self> anima::BaseBMRegistrationMethod< TInputImageType >::ConstPointer
Reimplemented in anima::AsymmetricBMRegistrationMethod< TInputImageType >, anima::DistortionCorrectionBMRegistrationMethod< TInputImageType >, anima::KissingSymmetricBMRegistrationMethod< TInputImageType >, and anima::SymmetricBMRegistrationMethod< TInputImageType >.
Definition at line 31 of file animaBaseBMRegistrationMethod.h.
template<typename TInputImageType> typedef itk::ProcessObject::DataObjectPointerArraySizeType anima::BaseBMRegistrationMethod< TInputImageType >::DataObjectPointerArraySizeType
Make a DataObject of the correct type to be used as the specified output.
Definition at line 116 of file animaBaseBMRegistrationMethod.h.
template<typename TInputImageType> typedef DisplacementFieldTransformType::Pointer anima::BaseBMRegistrationMethod< TInputImageType >::DisplacementFieldTransformPointer
Reimplemented in anima::DistortionCorrectionBMRegistrationMethod< TInputImageType >.
Definition at line 55 of file animaBaseBMRegistrationMethod.h.
template<typename TInputImageType> typedef rpi::DisplacementFieldTransform<AgregatorScalarType, TInputImageType::ImageDimension> anima::BaseBMRegistrationMethod< TInputImageType >::DisplacementFieldTransformType
Reimplemented in anima::DistortionCorrectionBMRegistrationMethod< TInputImageType >.
Definition at line 54 of file animaBaseBMRegistrationMethod.h.
template<typename TInputImageType> typedef TInputImageType::IOPixelType anima::BaseBMRegistrationMethod< TInputImageType >::ImageScalarType
Reimplemented in anima::DistortionCorrectionBMRegistrationMethod< TInputImageType >.
Definition at line 36 of file animaBaseBMRegistrationMethod.h.
template<typename TInputImageType> typedef InputImageType::Pointer anima::BaseBMRegistrationMethod< TInputImageType >::InputImagePointer
Reimplemented in anima::DistortionCorrectionBMRegistrationMethod< TInputImageType >.
Definition at line 60 of file animaBaseBMRegistrationMethod.h.
template<typename TInputImageType> typedef TInputImageType anima::BaseBMRegistrationMethod< TInputImageType >::InputImageType
Reimplemented in anima::DistortionCorrectionBMRegistrationMethod< TInputImageType >, anima::AsymmetricBMRegistrationMethod< TInputImageType >, anima::KissingSymmetricBMRegistrationMethod< TInputImageType >, and anima::SymmetricBMRegistrationMethod< TInputImageType >.
Definition at line 59 of file animaBaseBMRegistrationMethod.h.
template<typename TInputImageType> typedef MaskImageType::Pointer anima::BaseBMRegistrationMethod< TInputImageType >::MaskImagePointer
Definition at line 67 of file animaBaseBMRegistrationMethod.h.
template<typename TInputImageType> typedef itk::Image<unsigned char, TInputImageType::ImageDimension> anima::BaseBMRegistrationMethod< TInputImageType >::MaskImageType
Definition at line 66 of file animaBaseBMRegistrationMethod.h.
template<typename TInputImageType> typedef itk::SmartPointer<Self> anima::BaseBMRegistrationMethod< TInputImageType >::Pointer
Reimplemented in anima::AsymmetricBMRegistrationMethod< TInputImageType >, anima::DistortionCorrectionBMRegistrationMethod< TInputImageType >, anima::KissingSymmetricBMRegistrationMethod< TInputImageType >, and anima::SymmetricBMRegistrationMethod< TInputImageType >.
Definition at line 30 of file animaBaseBMRegistrationMethod.h.
template<typename TInputImageType> typedef ResamplerFilterType::Pointer anima::BaseBMRegistrationMethod< TInputImageType >::ResamplerFilterPointer
Definition at line 62 of file animaBaseBMRegistrationMethod.h.
template<typename TInputImageType> typedef itk::ImageToImageFilter<InputImageType,InputImageType> anima::BaseBMRegistrationMethod< TInputImageType >::ResamplerFilterType
Definition at line 61 of file animaBaseBMRegistrationMethod.h.
template<typename TInputImageType> typedef BaseBMRegistrationMethod anima::BaseBMRegistrationMethod< TInputImageType >::Self
Standard class typedefs.
Reimplemented in anima::AsymmetricBMRegistrationMethod< TInputImageType >, anima::DistortionCorrectionBMRegistrationMethod< TInputImageType >, anima::KissingSymmetricBMRegistrationMethod< TInputImageType >, and anima::SymmetricBMRegistrationMethod< TInputImageType >.
Definition at line 28 of file animaBaseBMRegistrationMethod.h.
template<typename TInputImageType> typedef itk::ProcessObject anima::BaseBMRegistrationMethod< TInputImageType >::Superclass
Reimplemented in anima::AsymmetricBMRegistrationMethod< TInputImageType >, anima::DistortionCorrectionBMRegistrationMethod< TInputImageType >, anima::KissingSymmetricBMRegistrationMethod< TInputImageType >, and anima::SymmetricBMRegistrationMethod< TInputImageType >.
Definition at line 29 of file animaBaseBMRegistrationMethod.h.
template<typename TInputImageType> typedef SVFTransformType::Pointer anima::BaseBMRegistrationMethod< TInputImageType >::SVFTransformPointer
Definition at line 53 of file animaBaseBMRegistrationMethod.h.
template<typename TInputImageType> typedef itk::StationaryVelocityFieldTransform<AgregatorScalarType, TInputImageType::ImageDimension> anima::BaseBMRegistrationMethod< TInputImageType >::SVFTransformType
RPI specific types
Reimplemented in anima::DistortionCorrectionBMRegistrationMethod< TInputImageType >, anima::KissingSymmetricBMRegistrationMethod< TInputImageType >, and anima::SymmetricBMRegistrationMethod< TInputImageType >.
Definition at line 52 of file animaBaseBMRegistrationMethod.h.
template<typename TInputImageType> typedef TransformOutputType::Pointer anima::BaseBMRegistrationMethod< TInputImageType >::TransformOutputPointer
Definition at line 49 of file animaBaseBMRegistrationMethod.h.
template<typename TInputImageType> typedef itk::DataObjectDecorator< TransformType > anima::BaseBMRegistrationMethod< TInputImageType >::TransformOutputType
Type for the output: Using Decorator pattern for enabling the Transform to be passed in the data pipeline
Definition at line 48 of file animaBaseBMRegistrationMethod.h.
template<typename TInputImageType> typedef TransformType::Pointer anima::BaseBMRegistrationMethod< TInputImageType >::TransformPointer
Reimplemented in anima::DistortionCorrectionBMRegistrationMethod< TInputImageType >, anima::AsymmetricBMRegistrationMethod< TInputImageType >, anima::KissingSymmetricBMRegistrationMethod< TInputImageType >, and anima::SymmetricBMRegistrationMethod< TInputImageType >.
Definition at line 44 of file animaBaseBMRegistrationMethod.h.
template<typename TInputImageType> typedef AgregatorType::BaseOutputTransformType anima::BaseBMRegistrationMethod< TInputImageType >::TransformType
Reimplemented in anima::DistortionCorrectionBMRegistrationMethod< TInputImageType >.
Definition at line 43 of file animaBaseBMRegistrationMethod.h.
Constructor & Destructor Documentation
template<typename TInputImageType > anima::BaseBMRegistrationMethod< TInputImageType >::BaseBMRegistrationMethod () [protected]
Definition at line 15 of file animaBaseBMRegistrationMethod.hxx.
template<typename TInputImageType> virtual anima::BaseBMRegistrationMethod< TInputImageType >::~BaseBMRegistrationMethod () [inline, protected, virtual]
Definition at line 122 of file animaBaseBMRegistrationMethod.h.
Member Function Documentation
template<typename TInputImageType> void anima::BaseBMRegistrationMethod< TInputImageType >::Abort () [inline]
Definition at line 103 of file animaBaseBMRegistrationMethod.h.
template<typename TInputImageType > bool anima::BaseBMRegistrationMethod< TInputImageType >::ComposeAddOnWithTransform (TransformPointer & computedTransform, TransformType * addOn) [protected, virtual]
Reimplemented in anima::DistortionCorrectionBMRegistrationMethod< TInputImageType >.
Definition at line 270 of file animaBaseBMRegistrationMethod.hxx.
References anima::composeSVF().
template<typename TInputImageType > void anima::BaseBMRegistrationMethod< TInputImageType >::GenerateData () [protected]
Starts registration when Update method is called
Definition at line 73 of file animaBaseBMRegistrationMethod.hxx.
template<typename TInputImageType> virtual AgregatorType* anima::BaseBMRegistrationMethod< TInputImageType >::GetAgregator () [virtual]
template<typename TInputImageType> virtual unsigned int anima::BaseBMRegistrationMethod< TInputImageType >::GetBCHCompositionOrder () [virtual]
template<typename TInputImageType> BlockMatcherType* anima::BaseBMRegistrationMethod< TInputImageType >::GetBlockMatcher () [inline]
Definition at line 109 of file animaBaseBMRegistrationMethod.h.
template<typename TInputImageType> virtual InputImageType* anima::BaseBMRegistrationMethod< TInputImageType >::GetFixedImage () [virtual]
template<typename TInputImageType> TransformPointer& anima::BaseBMRegistrationMethod< TInputImageType >::GetInitialTransform () [inline]
Definition at line 106 of file animaBaseBMRegistrationMethod.h.
template<typename TInputImageType> virtual unsigned int anima::BaseBMRegistrationMethod< TInputImageType >::GetMaximumIterations () [virtual]
template<typename TInputImageType> virtual double anima::BaseBMRegistrationMethod< TInputImageType >::GetMinimalTransformError () [virtual]
template<typename TInputImageType> virtual InputImageType* anima::BaseBMRegistrationMethod< TInputImageType >::GetMovingImage () [virtual]
template<typename TInputImageType> ResamplerFilterPointer& anima::BaseBMRegistrationMethod< TInputImageType >::GetMovingImageResampler () [inline]
Definition at line 80 of file animaBaseBMRegistrationMethod.h.
template<typename TInputImageType> virtual const char* anima::BaseBMRegistrationMethod< TInputImageType >::GetNameOfClass () const [virtual]
Run-time type information (and related methods).
Reimplemented in anima::DistortionCorrectionBMRegistrationMethod< TInputImageType >, anima::KissingSymmetricBMRegistrationMethod< TInputImageType >, anima::SymmetricBMRegistrationMethod< TInputImageType >, and anima::AsymmetricBMRegistrationMethod< TInputImageType >.
template<typename TInputImageType > BaseBMRegistrationMethod< TInputImageType >::TransformOutputType * anima::BaseBMRegistrationMethod< TInputImageType >::GetOutput ()
Returns the transform resulting from the registration process
Get Output
Definition at line 46 of file animaBaseBMRegistrationMethod.hxx.
template<typename TInputImageType> ResamplerFilterPointer& anima::BaseBMRegistrationMethod< TInputImageType >::GetReferenceImageResampler () [inline]
Definition at line 79 of file animaBaseBMRegistrationMethod.h.
template<typename TInputImageType> virtual double anima::BaseBMRegistrationMethod< TInputImageType >::GetSVFElasticRegSigma () [virtual]
template<typename TInputImageType> virtual bool anima::BaseBMRegistrationMethod< TInputImageType >::GetVerboseProgression () [virtual]
template<typename TInputImageType > itk::DataObject::Pointer anima::BaseBMRegistrationMethod< TInputImageType >::MakeOutput (DataObjectPointerArraySizeType idx) [virtual]
Definition at line 54 of file animaBaseBMRegistrationMethod.hxx.
template<typename TInputImageType> virtual void anima::BaseBMRegistrationMethod< TInputImageType >::PerformOneIteration (InputImageType * refImage, InputImageType * movingImage, TransformPointer & addOn) [protected, pure virtual]
Implemented in anima::DistortionCorrectionBMRegistrationMethod< TInputImageType >, anima::SymmetricBMRegistrationMethod< TInputImageType >, anima::KissingSymmetricBMRegistrationMethod< TInputImageType >, and anima::AsymmetricBMRegistrationMethod< TInputImageType >.
template<typename TInputImageType > void anima::BaseBMRegistrationMethod< TInputImageType >::PrintSelf (std::ostream & os, itk::Indent indent) const [protected, virtual]
PrintSelf
Definition at line 326 of file animaBaseBMRegistrationMethod.hxx.
template<typename TInputImageType > void anima::BaseBMRegistrationMethod< TInputImageType >::ResampleImages (TransformType * currentTransform, InputImagePointer & refImage, InputImagePointer & movingImage) [protected, virtual]
Reimplemented in anima::DistortionCorrectionBMRegistrationMethod< TInputImageType >.
Definition at line 160 of file animaBaseBMRegistrationMethod.hxx.
References anima::GetSVFExponential().
template<typename TInputImageType> virtual void anima::BaseBMRegistrationMethod< TInputImageType >::SetAgregator (AgregatorType * _arg) [virtual]
Set/Get Method for the Agregator
template<typename TInputImageType> virtual void anima::BaseBMRegistrationMethod< TInputImageType >::SetBCHCompositionOrder (unsigned int _arg) [virtual]
template<typename TInputImageType> void anima::BaseBMRegistrationMethod< TInputImageType >::SetBlockMatcher (BlockMatcherType * matcher) [inline]
Definition at line 108 of file animaBaseBMRegistrationMethod.h.
template<typename TInputImageType> virtual void anima::BaseBMRegistrationMethod< TInputImageType >::SetFixedImage (InputImageType * _arg) [virtual]
Set/Get the Fixed image.
template<typename TInputImageType> virtual void anima::BaseBMRegistrationMethod< TInputImageType >::SetInitialTransform (TransformPointer _arg) [virtual]
template<typename TInputImageType> virtual void anima::BaseBMRegistrationMethod< TInputImageType >::SetMaximumIterations (unsigned int _arg) [virtual]
Set/Get the maximum number of iterations
template<typename TInputImageType> virtual void anima::BaseBMRegistrationMethod< TInputImageType >::SetMinimalTransformError (double _arg) [virtual]
Set/Get the minimal error over consecutive transformations
template<typename TInputImageType> virtual void anima::BaseBMRegistrationMethod< TInputImageType >::SetMovingImage (InputImageType * _arg) [virtual]
Set/Get the Moving image.
Referenced by anima::DistortionCorrectionBMRegistrationMethod< TInputImageType >::PerformOneIteration().
template<typename TInputImageType> void anima::BaseBMRegistrationMethod< TInputImageType >::SetMovingImageResampler (ResamplerFilterType * filter) [inline]
Definition at line 78 of file animaBaseBMRegistrationMethod.h.
template<typename TInputImageType> void anima::BaseBMRegistrationMethod< TInputImageType >::SetReferenceImageResampler (ResamplerFilterType * filter) [inline]
Definition at line 77 of file animaBaseBMRegistrationMethod.h.
template<typename TInputImageType> virtual void anima::BaseBMRegistrationMethod< TInputImageType >::SetSVFElasticRegSigma (double _arg) [virtual]
template<typename TInputImageType > void anima::BaseBMRegistrationMethod< TInputImageType >::SetupTransform (TransformPointer & optimizedTransform) [protected, virtual]
Reimplemented in anima::DistortionCorrectionBMRegistrationMethod< TInputImageType >.
Definition at line 128 of file animaBaseBMRegistrationMethod.hxx.
template<typename TInputImageType> virtual void anima::BaseBMRegistrationMethod< TInputImageType >::SetVerboseProgression (bool _arg) [virtual]
template<typename TInputImageType > void anima::BaseBMRegistrationMethod< TInputImageType >::StartOptimization () [protected]
Starts the Registration Process
Definition at line 85 of file animaBaseBMRegistrationMethod.hxx.
The documentation for this class was generated from the following files:
animaBaseBMRegistrationMethod.h
animaBaseBMRegistrationMethod.hxx