ANIMA: anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType > Class Template Reference
anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType > Class Template Reference
#include <animaDTIEstimationImageFilter.h>
Classes
struct OptimizationDataStructure
Public Types
typedef itk::SmartPointer
< const Self > ConstPointer
typedef OutputImageType DTIImageType
typedef itk::Image
< InputPixelScalarType, 4 > Image4DType
typedef InputImageType::Pointer InputImagePointer
typedef
Superclass::InputImageRegionType InputImageRegionType
typedef itk::Image
< InputPixelScalarType, 3 > InputImageType
typedef Superclass::MaskImageType MaskImageType
typedef itk::Image
< OutputPixelScalarType, 3 > OutputB0ImageType
typedef OutputImageType::Pointer OutputImagePointer
typedef
Superclass::OutputImageRegionType OutputImageRegionType
typedef itk::VectorImage
< OutputPixelScalarType, 3 > OutputImageType
typedef itk::SmartPointer< Self > Pointer
typedef
DTIEstimationImageFilter
< InputPixelScalarType,
OutputPixelScalarType > Self
typedef
anima::MaskedImageToImageFilter
< InputImageType,
OutputImageType > Superclass
Public Member Functions
void AddGradientDirection (unsigned int i, vnl_vector_fixed< double, 3 > &grad)
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual double GetB0Threshold ()
virtual OutputB0ImageType * GetEstimatedB0Image ()
virtual const char * GetNameOfClass () const
virtual void SetB0Threshold (double _arg)
void SetBValuesList (std::vector< double > bValuesList)
virtual void SetProjectDegeneratedTensors (bool _arg)
virtual void SetRemoveDegeneratedTensors (bool _arg)
Static Public Member Functions
static Pointer New ()
Protected Member Functions
void BeforeThreadedGenerateData () ITK_OVERRIDE
void CheckComputationMask () ITK_OVERRIDE
double ComputeB0FromTensorVector (const std::vector< double > &tensorValue, const std::vector< double > &dwiSignal)
double ComputeCostAtPosition (const std::vector< double > &x, const std::vector< double > &observedData, std::vector< double > &predictedValues)
DTIEstimationImageFilter ()
void GenerateOutputInformation () ITK_OVERRIDE
void ThreadedGenerateData (const OutputImageRegionType &outputRegionForThread, itk::ThreadIdType threadId) ITK_OVERRIDE
virtual ~DTIEstimationImageFilter ()
Static Protected Member Functions
static double OptimizationFunction (const std::vector< double > &x, std::vector< double > &grad, void *func_data)
Detailed Description
template<class InputPixelScalarType, class OutputPixelScalarType>
class anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >
Definition at line 11 of file animaDTIEstimationImageFilter.h.
Member Typedef Documentation
template<class InputPixelScalarType , class OutputPixelScalarType > typedef itk::SmartPointer<const Self> anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::ConstPointer
Reimplemented from anima::MaskedImageToImageFilter< itk::Image< InputPixelScalarType, 3 >, itk::VectorImage< OutputPixelScalarType, 3 > >.
Definition at line 24 of file animaDTIEstimationImageFilter.h.
template<class InputPixelScalarType , class OutputPixelScalarType > typedef OutputImageType anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::DTIImageType
Definition at line 20 of file animaDTIEstimationImageFilter.h.
template<class InputPixelScalarType , class OutputPixelScalarType > typedef itk::Image<InputPixelScalarType,4> anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::Image4DType
Definition at line 21 of file animaDTIEstimationImageFilter.h.
template<class InputPixelScalarType , class OutputPixelScalarType > typedef InputImageType::Pointer anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::InputImagePointer
Image typedef support
Definition at line 33 of file animaDTIEstimationImageFilter.h.
template<class InputPixelScalarType , class OutputPixelScalarType > typedef Superclass::InputImageRegionType anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::InputImageRegionType
Superclass typedefs.
Reimplemented from anima::MaskedImageToImageFilter< itk::Image< InputPixelScalarType, 3 >, itk::VectorImage< OutputPixelScalarType, 3 > >.
Definition at line 38 of file animaDTIEstimationImageFilter.h.
template<class InputPixelScalarType , class OutputPixelScalarType > typedef itk::Image<InputPixelScalarType,3> anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::InputImageType
Definition at line 17 of file animaDTIEstimationImageFilter.h.
template<class InputPixelScalarType , class OutputPixelScalarType > typedef Superclass::MaskImageType anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::MaskImageType
Superclass typedefs.
Reimplemented from anima::MaskedImageToImageFilter< itk::Image< InputPixelScalarType, 3 >, itk::VectorImage< OutputPixelScalarType, 3 > >.
Definition at line 37 of file animaDTIEstimationImageFilter.h.
template<class InputPixelScalarType , class OutputPixelScalarType > typedef itk::Image<OutputPixelScalarType,3> anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::OutputB0ImageType
Definition at line 19 of file animaDTIEstimationImageFilter.h.
template<class InputPixelScalarType , class OutputPixelScalarType > typedef OutputImageType::Pointer anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::OutputImagePointer
Definition at line 34 of file animaDTIEstimationImageFilter.h.
template<class InputPixelScalarType , class OutputPixelScalarType > typedef Superclass::OutputImageRegionType anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::OutputImageRegionType
Reimplemented from anima::MaskedImageToImageFilter< itk::Image< InputPixelScalarType, 3 >, itk::VectorImage< OutputPixelScalarType, 3 > >.
Definition at line 39 of file animaDTIEstimationImageFilter.h.
template<class InputPixelScalarType , class OutputPixelScalarType > typedef itk::VectorImage<OutputPixelScalarType,3> anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::OutputImageType
Definition at line 18 of file animaDTIEstimationImageFilter.h.
template<class InputPixelScalarType , class OutputPixelScalarType > typedef itk::SmartPointer<Self> anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::Pointer
Reimplemented from anima::MaskedImageToImageFilter< itk::Image< InputPixelScalarType, 3 >, itk::VectorImage< OutputPixelScalarType, 3 > >.
Definition at line 23 of file animaDTIEstimationImageFilter.h.
template<class InputPixelScalarType , class OutputPixelScalarType > typedef DTIEstimationImageFilter<InputPixelScalarType, OutputPixelScalarType> anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::Self
Standard class typedefs.
Reimplemented from anima::MaskedImageToImageFilter< itk::Image< InputPixelScalarType, 3 >, itk::VectorImage< OutputPixelScalarType, 3 > >.
Definition at line 16 of file animaDTIEstimationImageFilter.h.
template<class InputPixelScalarType , class OutputPixelScalarType > typedef anima::MaskedImageToImageFilter< InputImageType, OutputImageType > anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::Superclass
Reimplemented from anima::MaskedImageToImageFilter< itk::Image< InputPixelScalarType, 3 >, itk::VectorImage< OutputPixelScalarType, 3 > >.
Definition at line 22 of file animaDTIEstimationImageFilter.h.
Constructor & Destructor Documentation
template<class InputPixelScalarType , class OutputPixelScalarType > anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::DTIEstimationImageFilter () [inline, protected]
Definition at line 60 of file animaDTIEstimationImageFilter.h.
template<class InputPixelScalarType , class OutputPixelScalarType > virtual anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::~DTIEstimationImageFilter () [inline, protected, virtual]
Definition at line 71 of file animaDTIEstimationImageFilter.h.
Member Function Documentation
template<class InputPixelScalarType , class OutputPixelScalarType > void anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::AddGradientDirection (unsigned int i, vnl_vector_fixed< double, 3 > & grad)
Definition at line 23 of file animaDTIEstimationImageFilter.hxx.
template<class InputPixelScalarType , class OutputPixelScalarType > void anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::BeforeThreadedGenerateData () [protected, virtual]
Reimplemented from anima::MaskedImageToImageFilter< itk::Image< InputPixelScalarType, 3 >, itk::VectorImage< OutputPixelScalarType, 3 > >.
Definition at line 90 of file animaDTIEstimationImageFilter.hxx.
template<class InputPixelScalarType , class OutputPixelScalarType > void anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::CheckComputationMask () [protected, virtual]
Reimplemented from anima::MaskedImageToImageFilter< itk::Image< InputPixelScalarType, 3 >, itk::VectorImage< OutputPixelScalarType, 3 > >.
Definition at line 36 of file animaDTIEstimationImageFilter.hxx.
template<class InputPixelScalarType , class OutputPixelScalarType > double anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::ComputeB0FromTensorVector (const std::vector< double > & tensorValue, const std::vector< double > & dwiSignal) [protected]
Definition at line 276 of file animaDTIEstimationImageFilter.hxx.
template<class InputPixelScalarType , class OutputPixelScalarType > double anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::ComputeCostAtPosition (const std::vector< double > & x, const std::vector< double > & observedData, std::vector< double > & predictedValues) [protected]
Definition at line 322 of file animaDTIEstimationImageFilter.hxx.
Referenced by anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::OptimizationFunction().
template<class InputPixelScalarType , class OutputPixelScalarType > virtual::itk::LightObject::Pointer anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::CreateAnother (void) const
Reimplemented from anima::MaskedImageToImageFilter< itk::Image< InputPixelScalarType, 3 >, itk::VectorImage< OutputPixelScalarType, 3 > >.
template<class InputPixelScalarType , class OutputPixelScalarType > void anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::GenerateOutputInformation () [protected]
Definition at line 76 of file animaDTIEstimationImageFilter.hxx.
template<class InputPixelScalarType , class OutputPixelScalarType > virtual double anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::GetB0Threshold () [virtual]
template<class InputPixelScalarType , class OutputPixelScalarType > virtual OutputB0ImageType* anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::GetEstimatedB0Image () [virtual]
template<class InputPixelScalarType , class OutputPixelScalarType > virtual const char* anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::GetNameOfClass () const [virtual]
Run-time type information (and related methods)
Reimplemented from anima::MaskedImageToImageFilter< itk::Image< InputPixelScalarType, 3 >, itk::VectorImage< OutputPixelScalarType, 3 > >.
template<class InputPixelScalarType , class OutputPixelScalarType > static Pointer anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::New () [static]
Method for creation through the object factory.
Reimplemented from anima::MaskedImageToImageFilter< itk::Image< InputPixelScalarType, 3 >, itk::VectorImage< OutputPixelScalarType, 3 > >.
template<class InputPixelScalarType , class OutputPixelScalarType > double anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::OptimizationFunction (const std::vector< double > & x, std::vector< double > & grad, void * func_data) [static, protected]
Definition at line 312 of file animaDTIEstimationImageFilter.hxx.
References anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::ComputeCostAtPosition(), anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::OptimizationDataStructure::dwi, anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::OptimizationDataStructure::filter, and anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::OptimizationDataStructure::predictedValues.
template<class InputPixelScalarType , class OutputPixelScalarType > virtual void anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::SetB0Threshold (double _arg) [virtual]
template<class InputPixelScalarType , class OutputPixelScalarType > void anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::SetBValuesList (std::vector< double > bValuesList) [inline]
Definition at line 47 of file animaDTIEstimationImageFilter.h.
template<class InputPixelScalarType , class OutputPixelScalarType > virtual void anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::SetProjectDegeneratedTensors (bool _arg) [virtual]
template<class InputPixelScalarType , class OutputPixelScalarType > virtual void anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::SetRemoveDegeneratedTensors (bool _arg) [virtual]
template<class InputPixelScalarType , class OutputPixelScalarType > void anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::ThreadedGenerateData (const OutputImageRegionType & outputRegionForThread, itk::ThreadIdType threadId) [protected]
Definition at line 128 of file animaDTIEstimationImageFilter.hxx.
References anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::OptimizationDataStructure::dwi, anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::OptimizationDataStructure::filter, anima::GetTensorFromVectorRepresentation(), anima::GetVectorRepresentation(), anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::OptimizationDataStructure::predictedValues, and anima::ProjectOnTensorSpace().
The documentation for this class was generated from the following files:
animaDTIEstimationImageFilter.h
animaDTIEstimationImageFilter.hxx