ANIMA: anima::BaseIsotropicCompartment Class Reference
anima::BaseIsotropicCompartment Class Reference
#include <animaBaseIsotropicCompartment.h>
Public Types
typedef Superclass::Pointer BasePointer
typedef itk::SmartPointer
< const Self > ConstPointer
typedef Superclass::Matrix3DType Matrix3DType
typedef
Superclass::ModelOutputVectorType ModelOutputVectorType
typedef itk::SmartPointer< Self > Pointer
typedef BaseIsotropicCompartment Self
typedef BaseCompartment Superclass
typedef Superclass::Vector3DType Vector3DType
Public Member Functions
unsigned int GetCompartmentSize () ITK_OVERRIDE
Number of parameters to describe the model, these parameters will be self-contained, i.e. include fixed parameters for example.
ModelOutputVectorType & GetCompartmentVector () ITK_OVERRIDE
Get compartment overall description vector, mainly for writing, should be self-contained.
const Matrix3DType & GetDiffusionTensor () ITK_OVERRIDE
Get compartment as a 3D tensor (default behavior: throw exception if not supported by the compartment model)
bool GetEstimateAxialDiffusivity ()
virtual double GetFourierTransformedDiffusionProfile (double bValue, const Vector3DType &gradient) ITK_OVERRIDE
double GetFractionalAnisotropy () ITK_OVERRIDE
virtual double GetLogDiffusionProfile (const Vector3DType &sample) ITK_OVERRIDE
virtual const char * GetNameOfClass () const
unsigned int GetNumberOfParameters () ITK_OVERRIDE
Number of optimized parameters: smaller than total number of parameters.
virtual ListType GetParametersAsVector () ITK_OVERRIDE
virtual ListType GetSignalAttenuationJacobian (double bValue, const Vector3DType &gradient) ITK_OVERRIDE
void Reorient (vnl_matrix< double > &orientationMatrix, bool affineTransform) ITK_OVERRIDE
Reimplements re-orientation, useless in isotropic water compartment.
void SetCompartmentVector (ModelOutputVectorType &compartmentVector) ITK_OVERRIDE
Set compartment overall description vector, for setting automatically the individual parameters when reading from disk.
void SetEstimateAxialDiffusivity (bool arg)
virtual void SetParametersFromVector (const ListType &params) ITK_OVERRIDE
Various methods for optimization parameters setting and getting.
Protected Member Functions
BaseIsotropicCompartment ()
virtual double GetAxialDiffusivityDerivativeFactor ()
virtual ~BaseIsotropicCompartment ()
Detailed Description
Definition at line 9 of file animaBaseIsotropicCompartment.h.
Member Typedef Documentation
typedef Superclass::Pointer anima::BaseIsotropicCompartment::BasePointer
Reimplemented in anima::FreeWaterCompartment, anima::IsotropicRestrictedWaterCompartment, and anima::StationaryWaterCompartment.
Definition at line 15 of file animaBaseIsotropicCompartment.h.
typedef itk::SmartPointer<const Self> anima::BaseIsotropicCompartment::ConstPointer
Reimplemented from anima::BaseCompartment.
Reimplemented in anima::FreeWaterCompartment, anima::IsotropicRestrictedWaterCompartment, and anima::StationaryWaterCompartment.
Definition at line 17 of file animaBaseIsotropicCompartment.h.
typedef Superclass::Matrix3DType anima::BaseIsotropicCompartment::Matrix3DType
Reimplemented from anima::BaseCompartment.
Definition at line 20 of file animaBaseIsotropicCompartment.h.
typedef Superclass::ModelOutputVectorType anima::BaseIsotropicCompartment::ModelOutputVectorType
Reimplemented from anima::BaseCompartment.
Definition at line 18 of file animaBaseIsotropicCompartment.h.
typedef itk::SmartPointer<Self> anima::BaseIsotropicCompartment::Pointer
Reimplemented from anima::BaseCompartment.
Reimplemented in anima::FreeWaterCompartment, anima::IsotropicRestrictedWaterCompartment, and anima::StationaryWaterCompartment.
Definition at line 16 of file animaBaseIsotropicCompartment.h.
typedef BaseIsotropicCompartment anima::BaseIsotropicCompartment::Self
Reimplemented from anima::BaseCompartment.
Reimplemented in anima::FreeWaterCompartment, anima::IsotropicRestrictedWaterCompartment, and anima::StationaryWaterCompartment.
Definition at line 13 of file animaBaseIsotropicCompartment.h.
typedef BaseCompartment anima::BaseIsotropicCompartment::Superclass
Reimplemented from anima::BaseCompartment.
Reimplemented in anima::FreeWaterCompartment, anima::IsotropicRestrictedWaterCompartment, and anima::StationaryWaterCompartment.
Definition at line 14 of file animaBaseIsotropicCompartment.h.
typedef Superclass::Vector3DType anima::BaseIsotropicCompartment::Vector3DType
Reimplemented from anima::BaseCompartment.
Definition at line 19 of file animaBaseIsotropicCompartment.h.
Constructor & Destructor Documentation
anima::BaseIsotropicCompartment::BaseIsotropicCompartment () [inline, protected]
Definition at line 49 of file animaBaseIsotropicCompartment.h.
virtual anima::BaseIsotropicCompartment::~BaseIsotropicCompartment () [inline, protected, virtual]
Definition at line 57 of file animaBaseIsotropicCompartment.h.
Member Function Documentation
virtual double anima::BaseIsotropicCompartment::GetAxialDiffusivityDerivativeFactor () [inline, protected, virtual]
Reimplemented in anima::FreeWaterCompartment, and anima::IsotropicRestrictedWaterCompartment.
Definition at line 59 of file animaBaseIsotropicCompartment.h.
Referenced by GetSignalAttenuationJacobian().
unsigned int anima::BaseIsotropicCompartment::GetCompartmentSize () [virtual]
Number of parameters to describe the model, these parameters will be self-contained, i.e. include fixed parameters for example.
Implements anima::BaseCompartment.
Definition at line 89 of file animaBaseIsotropicCompartment.cxx.
Referenced by GetCompartmentVector(), GetNumberOfParameters(), and SetCompartmentVector().
BaseIsotropicCompartment::ModelOutputVectorType & anima::BaseIsotropicCompartment::GetCompartmentVector () [virtual]
Get compartment overall description vector, mainly for writing, should be self-contained.
Implements anima::BaseCompartment.
Definition at line 108 of file animaBaseIsotropicCompartment.cxx.
References anima::BaseCompartment::GetAxialDiffusivity(), GetCompartmentSize(), and anima::BaseCompartment::m_CompartmentVector.
const BaseIsotropicCompartment::Matrix3DType & anima::BaseIsotropicCompartment::GetDiffusionTensor () [virtual]
Get compartment as a 3D tensor (default behavior: throw exception if not supported by the compartment model)
Reimplemented from anima::BaseCompartment.
Definition at line 118 of file animaBaseIsotropicCompartment.cxx.
References anima::BaseCompartment::GetAxialDiffusivity(), and anima::BaseCompartment::m_SpaceDimension.
bool anima::BaseIsotropicCompartment::GetEstimateAxialDiffusivity () [inline]
Definition at line 34 of file animaBaseIsotropicCompartment.h.
Referenced by anima::FreeWaterCompartment::BoundParameters(), anima::IsotropicRestrictedWaterCompartment::BoundParameters(), anima::FreeWaterCompartment::GetParameterLowerBounds(), anima::IsotropicRestrictedWaterCompartment::GetParameterLowerBounds(), anima::FreeWaterCompartment::GetParameterUpperBounds(), anima::IsotropicRestrictedWaterCompartment::GetParameterUpperBounds(), anima::FreeWaterCompartment::UnboundParameters(), and anima::IsotropicRestrictedWaterCompartment::UnboundParameters().
double anima::BaseIsotropicCompartment::GetFourierTransformedDiffusionProfile (double bValue, const Vector3DType & gradient) [virtual]
Implements anima::BaseCompartment.
Definition at line 8 of file animaBaseIsotropicCompartment.cxx.
References anima::BaseCompartment::GetAxialDiffusivity().
Referenced by GetSignalAttenuationJacobian().
double anima::BaseIsotropicCompartment::GetFractionalAnisotropy () [virtual]
Reimplemented from anima::BaseCompartment.
Definition at line 128 of file animaBaseIsotropicCompartment.cxx.
double anima::BaseIsotropicCompartment::GetLogDiffusionProfile (const Vector3DType & sample) [virtual]
Implements anima::BaseCompartment.
Definition at line 30 of file animaBaseIsotropicCompartment.cxx.
References anima::BaseCompartment::GetAxialDiffusivity().
virtual const char* anima::BaseIsotropicCompartment::GetNameOfClass () const [virtual]
Run-time type information (and related methods)
Reimplemented from anima::BaseCompartment.
Reimplemented in anima::FreeWaterCompartment, anima::IsotropicRestrictedWaterCompartment, and anima::StationaryWaterCompartment.
unsigned int anima::BaseIsotropicCompartment::GetNumberOfParameters () [virtual]
Number of optimized parameters: smaller than total number of parameters.
Implements anima::BaseCompartment.
Definition at line 94 of file animaBaseIsotropicCompartment.cxx.
References GetCompartmentSize().
Referenced by anima::FreeWaterCompartment::GetParameterLowerBounds(), anima::StationaryWaterCompartment::GetParameterLowerBounds(), anima::IsotropicRestrictedWaterCompartment::GetParameterLowerBounds(), GetParametersAsVector(), anima::StationaryWaterCompartment::GetParameterUpperBounds(), anima::FreeWaterCompartment::GetParameterUpperBounds(), anima::IsotropicRestrictedWaterCompartment::GetParameterUpperBounds(), GetSignalAttenuationJacobian(), and SetParametersFromVector().
BaseIsotropicCompartment::ListType anima::BaseIsotropicCompartment::GetParametersAsVector () [virtual]
Implements anima::BaseCompartment.
Definition at line 59 of file animaBaseIsotropicCompartment.cxx.
References anima::BaseCompartment::GetAxialDiffusivity(), GetNumberOfParameters(), anima::BaseCompartment::GetUseBoundedOptimization(), and anima::BaseCompartment::UnboundParameters().
BaseIsotropicCompartment::ListType anima::BaseIsotropicCompartment::GetSignalAttenuationJacobian (double bValue, const Vector3DType & gradient) [virtual]
Implements anima::BaseCompartment.
Definition at line 13 of file animaBaseIsotropicCompartment.cxx.
References GetAxialDiffusivityDerivativeFactor(), GetFourierTransformedDiffusionProfile(), GetNumberOfParameters(), and anima::BaseCompartment::GetUseBoundedOptimization().
void anima::BaseIsotropicCompartment::Reorient (vnl_matrix< double > & orientationMatrix, bool affineTransform) [inline, virtual]
Reimplements re-orientation, useless in isotropic water compartment.
Reimplemented from anima::BaseCompartment.
Definition at line 43 of file animaBaseIsotropicCompartment.h.
void anima::BaseIsotropicCompartment::SetCompartmentVector (ModelOutputVectorType & compartmentVector) [virtual]
Set compartment overall description vector, for setting automatically the individual parameters when reading from disk.
Implements anima::BaseCompartment.
Definition at line 81 of file animaBaseIsotropicCompartment.cxx.
References GetCompartmentSize(), and anima::BaseCompartment::SetAxialDiffusivity().
void anima::BaseIsotropicCompartment::SetEstimateAxialDiffusivity (bool arg)
Definition at line 72 of file animaBaseIsotropicCompartment.cxx.
void anima::BaseIsotropicCompartment::SetParametersFromVector (const ListType & params) [virtual]
Various methods for optimization parameters setting and getting.
Implements anima::BaseCompartment.
Definition at line 39 of file animaBaseIsotropicCompartment.cxx.
References anima::BaseCompartment::BoundParameters(), anima::BaseCompartment::GetBoundedSignVector(), GetNumberOfParameters(), anima::BaseCompartment::GetUseBoundedOptimization(), and anima::BaseCompartment::SetAxialDiffusivity().
The documentation for this class was generated from the following files:
animaBaseIsotropicCompartment.h
animaBaseIsotropicCompartment.cxx