ANIMA: anima::dtiTractographyImageFilter Class Reference
anima::dtiTractographyImageFilter Class Reference
#include <animaDTITractographyImageFilter.h>
Public Types
typedef itk::SmartPointer
< const Self > ConstPointer
typedef
DTIInterpolatorType::Pointer DTIInterpolatorPointer
typedef
itk::LinearInterpolateImageFunction
< ModelImageType > DTIInterpolatorType
typedef Superclass::ModelImageType ModelImageType
typedef itk::SmartPointer< Self > Pointer
typedef Superclass::PointType PointType
typedef dtiTractographyImageFilter Self
typedef
anima::BaseTractographyImageFilter Superclass
typedef Superclass::VectorType VectorType
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const char * GetNameOfClass () const
virtual void SetInputImage (ModelImageType *input) ITK_OVERRIDE
void SetStopFAThreshold (double num)
Static Public Member Functions
static Pointer New ()
Protected Member Functions
virtual bool CheckIndexInImageBounds (ContinuousIndexType &index) ITK_OVERRIDE
virtual bool CheckModelCompatibility (VectorType &modelValue, itk::ThreadIdType threadId) ITK_OVERRIDE
virtual void ComputeAdditionalScalarMaps () ITK_OVERRIDE
dtiTractographyImageFilter ()
virtual PointType GetModelPrincipalDirection (VectorType &modelValue, bool is2d, itk::ThreadIdType threadId) ITK_OVERRIDE
virtual VectorType GetModelValue (ContinuousIndexType &index) ITK_OVERRIDE
virtual PointType GetNextDirection (PointType &previousDirection, VectorType &modelValue, bool is2d, itk::ThreadIdType threadId) ITK_OVERRIDE
virtual ~dtiTractographyImageFilter ()
Detailed Description
Definition at line 11 of file animaDTITractographyImageFilter.h.
Member Typedef Documentation
typedef itk::SmartPointer<const Self> anima::dtiTractographyImageFilter::ConstPointer
Reimplemented from anima::BaseTractographyImageFilter.
Definition at line 19 of file animaDTITractographyImageFilter.h.
typedef DTIInterpolatorType::Pointer anima::dtiTractographyImageFilter::DTIInterpolatorPointer
Definition at line 29 of file animaDTITractographyImageFilter.h.
typedef itk::LinearInterpolateImageFunction<ModelImageType> anima::dtiTractographyImageFilter::DTIInterpolatorType
Definition at line 28 of file animaDTITractographyImageFilter.h.
typedef Superclass::ModelImageType anima::dtiTractographyImageFilter::ModelImageType
Reimplemented from anima::BaseTractographyImageFilter.
Definition at line 25 of file animaDTITractographyImageFilter.h.
typedef itk::SmartPointer<Self> anima::dtiTractographyImageFilter::Pointer
Reimplemented from anima::BaseTractographyImageFilter.
Definition at line 18 of file animaDTITractographyImageFilter.h.
typedef Superclass::PointType anima::dtiTractographyImageFilter::PointType
Reimplemented from anima::BaseTractographyImageFilter.
Definition at line 27 of file animaDTITractographyImageFilter.h.
typedef dtiTractographyImageFilter anima::dtiTractographyImageFilter::Self
SmartPointer typedef support
Reimplemented from anima::BaseTractographyImageFilter.
Definition at line 15 of file animaDTITractographyImageFilter.h.
typedef anima::BaseTractographyImageFilter anima::dtiTractographyImageFilter::Superclass
Reimplemented from anima::BaseTractographyImageFilter.
Definition at line 16 of file animaDTITractographyImageFilter.h.
typedef Superclass::VectorType anima::dtiTractographyImageFilter::VectorType
Reimplemented from anima::BaseTractographyImageFilter.
Definition at line 26 of file animaDTITractographyImageFilter.h.
Constructor & Destructor Documentation
anima::dtiTractographyImageFilter::dtiTractographyImageFilter () [protected]
Definition at line 12 of file animaDTITractographyImageFilter.cxx.
anima::dtiTractographyImageFilter::~dtiTractographyImageFilter () [protected, virtual]
Definition at line 17 of file animaDTITractographyImageFilter.cxx.
Member Function Documentation
bool anima::dtiTractographyImageFilter::CheckIndexInImageBounds (ContinuousIndexType & index) [protected, virtual]
Implements anima::BaseTractographyImageFilter.
Definition at line 74 of file animaDTITractographyImageFilter.cxx.
bool anima::dtiTractographyImageFilter::CheckModelCompatibility (VectorType & modelValue, itk::ThreadIdType threadId) [protected, virtual]
Implements anima::BaseTractographyImageFilter.
Definition at line 29 of file animaDTITractographyImageFilter.cxx.
void anima::dtiTractographyImageFilter::ComputeAdditionalScalarMaps () [protected, virtual]
Reimplemented from anima::BaseTractographyImageFilter.
Definition at line 179 of file animaDTITractographyImageFilter.cxx.
References anima::BaseTractographyImageFilter::GetInputImage(), GetModelValue(), anima::BaseTractographyImageFilter::GetOutput(), anima::GetTensorExponential(), anima::GetTensorFromVectorRepresentation(), anima::GetVectorRepresentation(), and New().
virtual::itk::LightObject::Pointer anima::dtiTractographyImageFilter::CreateAnother (void) const
dtiTractographyImageFilter::PointType anima::dtiTractographyImageFilter::GetModelPrincipalDirection (VectorType & modelValue, bool is2d, itk::ThreadIdType threadId) [protected, virtual]
Implements anima::BaseTractographyImageFilter.
Definition at line 88 of file animaDTITractographyImageFilter.cxx.
Referenced by GetNextDirection().
dtiTractographyImageFilter::VectorType anima::dtiTractographyImageFilter::GetModelValue (ContinuousIndexType & index) [protected, virtual]
Implements anima::BaseTractographyImageFilter.
Definition at line 80 of file animaDTITractographyImageFilter.cxx.
Referenced by ComputeAdditionalScalarMaps().
virtual const char* anima::dtiTractographyImageFilter::GetNameOfClass () const [virtual]
Reimplemented from anima::BaseTractographyImageFilter.
dtiTractographyImageFilter::PointType anima::dtiTractographyImageFilter::GetNextDirection (PointType & previousDirection, VectorType & modelValue, bool is2d, itk::ThreadIdType threadId) [protected, virtual]
Implements anima::BaseTractographyImageFilter.
Definition at line 132 of file animaDTITractographyImageFilter.cxx.
References anima::ComputeScalarProduct(), anima::BaseTractographyImageFilter::GetMinimalModelWeight(), GetModelPrincipalDirection(), anima::GetTensorFromVectorRepresentation(), anima::Normalize(), and anima::Revert().
static Pointer anima::dtiTractographyImageFilter::New () [static]
Referenced by ComputeAdditionalScalarMaps(), and SetInputImage().
void anima::dtiTractographyImageFilter::SetInputImage (ModelImageType * input) [virtual]
Reimplemented from anima::BaseTractographyImageFilter.
Definition at line 21 of file animaDTITractographyImageFilter.cxx.
References anima::BaseTractographyImageFilter::GetInputImage(), New(), and anima::BaseTractographyImageFilter::SetInputImage().
void anima::dtiTractographyImageFilter::SetStopFAThreshold (double num) [inline]
Definition at line 33 of file animaDTITractographyImageFilter.h.
The documentation for this class was generated from the following files:
animaDTITractographyImageFilter.h
animaDTITractographyImageFilter.cxx