ANIMA: anima::GaussianMCMVariableProjectionMultipleValuedCostFunction Class Reference
anima::GaussianMCMVariableProjectionMultipleValuedCostFunction Class Reference
#include <animaGaussianMCMVariableProjectionMultipleValuedCostFunction.h>
Public Types
typedef itk::SmartPointer
< const Self > ConstPointer
typedef Superclass::DerivativeType DerivativeType
typedef InternalCostType::Pointer InternalCostPointer
typedef
anima::GaussianMCMVariableProjectionCost InternalCostType
typedef Superclass::MeasureType MeasureType
typedef Superclass::ParametersType ParametersType
typedef itk::SmartPointer< Self > Pointer
typedef
GaussianMCMVariableProjectionMultipleValuedCostFunction Self
typedef
itk::MultipleValuedCostFunction Superclass
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
double GetB0Value ()
virtual void GetDerivative (const ParametersType &parameters, DerivativeType &derivative) const ITK_OVERRIDE
virtual const InternalCostPointer & GetInternalCost () const
virtual const char * GetNameOfClass () const
unsigned int GetNumberOfParameters () const ITK_OVERRIDE
unsigned int GetNumberOfValues () const ITK_OVERRIDE
std::vector< double > & GetOptimalWeights ()
double GetSigmaSquare ()
virtual MeasureType GetValue (const ParametersType &parameters) const ITK_OVERRIDE
virtual void SetInternalCost (InternalCostPointer _arg)
Static Public Member Functions
static Pointer New ()
Protected Member Functions
GaussianMCMVariableProjectionMultipleValuedCostFunction ()
virtual ~GaussianMCMVariableProjectionMultipleValuedCostFunction ()
Detailed Description
Definition at line 10 of file animaGaussianMCMVariableProjectionMultipleValuedCostFunction.h.
Member Typedef Documentation
typedef itk::SmartPointer<const Self> anima::GaussianMCMVariableProjectionMultipleValuedCostFunction::ConstPointer
Definition at line 17 of file animaGaussianMCMVariableProjectionMultipleValuedCostFunction.h.
typedef Superclass::DerivativeType anima::GaussianMCMVariableProjectionMultipleValuedCostFunction::DerivativeType
Definition at line 25 of file animaGaussianMCMVariableProjectionMultipleValuedCostFunction.h.
typedef InternalCostType::Pointer anima::GaussianMCMVariableProjectionMultipleValuedCostFunction::InternalCostPointer
Definition at line 29 of file animaGaussianMCMVariableProjectionMultipleValuedCostFunction.h.
typedef anima::GaussianMCMVariableProjectionCost anima::GaussianMCMVariableProjectionMultipleValuedCostFunction::InternalCostType
Definition at line 28 of file animaGaussianMCMVariableProjectionMultipleValuedCostFunction.h.
typedef Superclass::MeasureType anima::GaussianMCMVariableProjectionMultipleValuedCostFunction::MeasureType
Definition at line 24 of file animaGaussianMCMVariableProjectionMultipleValuedCostFunction.h.
typedef Superclass::ParametersType anima::GaussianMCMVariableProjectionMultipleValuedCostFunction::ParametersType
Definition at line 26 of file animaGaussianMCMVariableProjectionMultipleValuedCostFunction.h.
typedef itk::SmartPointer<Self> anima::GaussianMCMVariableProjectionMultipleValuedCostFunction::Pointer
Definition at line 16 of file animaGaussianMCMVariableProjectionMultipleValuedCostFunction.h.
typedef GaussianMCMVariableProjectionMultipleValuedCostFunction anima::GaussianMCMVariableProjectionMultipleValuedCostFunction::Self
Standard class typedefs.
Definition at line 14 of file animaGaussianMCMVariableProjectionMultipleValuedCostFunction.h.
typedef itk::MultipleValuedCostFunction anima::GaussianMCMVariableProjectionMultipleValuedCostFunction::Superclass
Definition at line 15 of file animaGaussianMCMVariableProjectionMultipleValuedCostFunction.h.
Constructor & Destructor Documentation
anima::GaussianMCMVariableProjectionMultipleValuedCostFunction::GaussianMCMVariableProjectionMultipleValuedCostFunction () [inline, protected]
Definition at line 45 of file animaGaussianMCMVariableProjectionMultipleValuedCostFunction.h.
virtual anima::GaussianMCMVariableProjectionMultipleValuedCostFunction::~GaussianMCMVariableProjectionMultipleValuedCostFunction () [inline, protected, virtual]
Definition at line 50 of file animaGaussianMCMVariableProjectionMultipleValuedCostFunction.h.
Member Function Documentation
virtual::itk::LightObject::Pointer anima::GaussianMCMVariableProjectionMultipleValuedCostFunction::CreateAnother (void) const
double anima::GaussianMCMVariableProjectionMultipleValuedCostFunction::GetB0Value ()
Definition at line 48 of file animaGaussianMCMVariableProjectionMultipleValuedCostFunction.cxx.
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::GetProfiledInformation().
void anima::GaussianMCMVariableProjectionMultipleValuedCostFunction::GetDerivative (const ParametersType & parameters, DerivativeType & derivative) const [virtual]
Definition at line 38 of file animaGaussianMCMVariableProjectionMultipleValuedCostFunction.cxx.
virtual const InternalCostPointer& anima::GaussianMCMVariableProjectionMultipleValuedCostFunction::GetInternalCost () const [virtual]
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::GetCostValue().
virtual const char* anima::GaussianMCMVariableProjectionMultipleValuedCostFunction::GetNameOfClass () const [virtual]
Run-time type information (and related methods).
unsigned int anima::GaussianMCMVariableProjectionMultipleValuedCostFunction::GetNumberOfParameters () const
Definition at line 8 of file animaGaussianMCMVariableProjectionMultipleValuedCostFunction.cxx.
unsigned int anima::GaussianMCMVariableProjectionMultipleValuedCostFunction::GetNumberOfValues () const
Definition at line 18 of file animaGaussianMCMVariableProjectionMultipleValuedCostFunction.cxx.
std::vector< double > & anima::GaussianMCMVariableProjectionMultipleValuedCostFunction::GetOptimalWeights ()
Definition at line 62 of file animaGaussianMCMVariableProjectionMultipleValuedCostFunction.cxx.
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::GetProfiledInformation().
double anima::GaussianMCMVariableProjectionMultipleValuedCostFunction::GetSigmaSquare ()
Definition at line 55 of file animaGaussianMCMVariableProjectionMultipleValuedCostFunction.cxx.
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::GetProfiledInformation().
GaussianMCMVariableProjectionMultipleValuedCostFunction::MeasureType anima::GaussianMCMVariableProjectionMultipleValuedCostFunction::GetValue (const ParametersType & parameters) const [virtual]
Definition at line 28 of file animaGaussianMCMVariableProjectionMultipleValuedCostFunction.cxx.
static Pointer anima::GaussianMCMVariableProjectionMultipleValuedCostFunction::New () [static]
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::CreateCostFunction().
virtual void anima::GaussianMCMVariableProjectionMultipleValuedCostFunction::SetInternalCost (InternalCostPointer _arg) [virtual]
The documentation for this class was generated from the following files:
animaGaussianMCMVariableProjectionMultipleValuedCostFunction.h
animaGaussianMCMVariableProjectionMultipleValuedCostFunction.cxx