ANIMA: anima::LowMemoryPatientToGroupODFComparisonBridge Class Reference
anima::LowMemoryPatientToGroupODFComparisonBridge Class Reference
#include <animaLowMemPatientToGroupODFComparisonBridge.h>
Public Types
typedef
anima::ImageDataSplitter
< InputImageType > ImageSplitterODFType
typedef
PatientToGroupODFComparisonImageFilter
< double >::InputImageType InputImageType
typedef
anima::PatientToGroupODFComparisonImageFilter
< double > MainFilterType
typedef itk::Image< unsigned
char, 3 > MaskImageType
typedef
PatientToGroupODFComparisonImageFilter
< double >::OutputImageType OutputImageType
typedef MainFilterType::TestType TestType
Public Member Functions
void BuildAndWrite (OutputImageType *tmpIm, std::string resName, OutputImageType::RegionType finalROI)
std::string GetNameOfClass ()
LowMemoryPatientToGroupODFComparisonBridge ()
void SetComputationMask (std::string &cMask)
void SetDataODFFileNames (std::string &fileList)
void SetExplainedRatio (double eRatio)
void SetNbSplits (unsigned int nbSplits)
void SetNumberOfThreads (unsigned int &nbT)
void SetNumEigenValuesPCA (unsigned int numEigen)
void SetOutputName (std::string &pref)
void SetOutputPValName (std::string &pref)
void SetSampleDirections (std::vector< std::vector< double > > &sampleDirections)
void SetStatisticalTestType (TestType type)
void SetTestODFFileName (std::string &fileName)
void Update (int specificSplitToDo=-1, bool genOutputDescriptionData=false)
~LowMemoryPatientToGroupODFComparisonBridge ()
Detailed Description
Definition at line 9 of file animaLowMemPatientToGroupODFComparisonBridge.h.
Member Typedef Documentation
typedef anima::ImageDataSplitter< InputImageType > anima::LowMemoryPatientToGroupODFComparisonBridge::ImageSplitterODFType
Definition at line 15 of file animaLowMemPatientToGroupODFComparisonBridge.h.
typedef PatientToGroupODFComparisonImageFilter<double>::InputImageType anima::LowMemoryPatientToGroupODFComparisonBridge::InputImageType
Definition at line 12 of file animaLowMemPatientToGroupODFComparisonBridge.h.
typedef anima::PatientToGroupODFComparisonImageFilter<double> anima::LowMemoryPatientToGroupODFComparisonBridge::MainFilterType
Definition at line 16 of file animaLowMemPatientToGroupODFComparisonBridge.h.
typedef itk::Image<unsigned char,3> anima::LowMemoryPatientToGroupODFComparisonBridge::MaskImageType
Definition at line 18 of file animaLowMemPatientToGroupODFComparisonBridge.h.
typedef PatientToGroupODFComparisonImageFilter<double>::OutputImageType anima::LowMemoryPatientToGroupODFComparisonBridge::OutputImageType
Definition at line 13 of file animaLowMemPatientToGroupODFComparisonBridge.h.
typedef MainFilterType::TestType anima::LowMemoryPatientToGroupODFComparisonBridge::TestType
Definition at line 17 of file animaLowMemPatientToGroupODFComparisonBridge.h.
Constructor & Destructor Documentation
anima::LowMemoryPatientToGroupODFComparisonBridge::LowMemoryPatientToGroupODFComparisonBridge ()
Definition at line 7 of file animaLowMemPatientToGroupODFComparisonBridge.cxx.
References anima::PatientToGroupComparisonImageFilter< PixelScalarType >::FISHER.
anima::LowMemoryPatientToGroupODFComparisonBridge::~LowMemoryPatientToGroupODFComparisonBridge ()
Definition at line 24 of file animaLowMemPatientToGroupODFComparisonBridge.cxx.
Member Function Documentation
void anima::LowMemoryPatientToGroupODFComparisonBridge::BuildAndWrite (OutputImageType * tmpIm, std::string resName, OutputImageType::RegionType finalROI)
Definition at line 171 of file animaLowMemPatientToGroupODFComparisonBridge.cxx.
Referenced by Update().
std::string anima::LowMemoryPatientToGroupODFComparisonBridge::GetNameOfClass () [inline]
Definition at line 23 of file animaLowMemPatientToGroupODFComparisonBridge.h.
void anima::LowMemoryPatientToGroupODFComparisonBridge::SetComputationMask (std::string & cMask)
Definition at line 33 of file animaLowMemPatientToGroupODFComparisonBridge.cxx.
References anima::ImageDataSplitter< TInputImage >::SetComputationMask().
Referenced by main().
void anima::LowMemoryPatientToGroupODFComparisonBridge::SetDataODFFileNames (std::string & fileList) [inline]
Definition at line 27 of file animaLowMemPatientToGroupODFComparisonBridge.h.
References anima::ImageDataSplitter< TInputImage >::SetFileNames().
void anima::LowMemoryPatientToGroupODFComparisonBridge::SetExplainedRatio (double eRatio) [inline]
Definition at line 44 of file animaLowMemPatientToGroupODFComparisonBridge.h.
void anima::LowMemoryPatientToGroupODFComparisonBridge::SetNbSplits (unsigned int nbSplits) [inline]
Definition at line 40 of file animaLowMemPatientToGroupODFComparisonBridge.h.
void anima::LowMemoryPatientToGroupODFComparisonBridge::SetNumberOfThreads (unsigned int & nbT) [inline]
Definition at line 41 of file animaLowMemPatientToGroupODFComparisonBridge.h.
void anima::LowMemoryPatientToGroupODFComparisonBridge::SetNumEigenValuesPCA (unsigned int numEigen) [inline]
Definition at line 45 of file animaLowMemPatientToGroupODFComparisonBridge.h.
void anima::LowMemoryPatientToGroupODFComparisonBridge::SetOutputName (std::string & pref) [inline]
Definition at line 37 of file animaLowMemPatientToGroupODFComparisonBridge.h.
void anima::LowMemoryPatientToGroupODFComparisonBridge::SetOutputPValName (std::string & pref) [inline]
Definition at line 38 of file animaLowMemPatientToGroupODFComparisonBridge.h.
void anima::LowMemoryPatientToGroupODFComparisonBridge::SetSampleDirections (std::vector< std::vector< double > > & sampleDirections) [inline]
Definition at line 47 of file animaLowMemPatientToGroupODFComparisonBridge.h.
void anima::LowMemoryPatientToGroupODFComparisonBridge::SetStatisticalTestType (TestType type) [inline]
Definition at line 43 of file animaLowMemPatientToGroupODFComparisonBridge.h.
void anima::LowMemoryPatientToGroupODFComparisonBridge::SetTestODFFileName (std::string & fileName) [inline]
Definition at line 32 of file animaLowMemPatientToGroupODFComparisonBridge.h.
References anima::ImageDataSplitter< TInputImage >::SetUniqueFileName().
void anima::LowMemoryPatientToGroupODFComparisonBridge::Update (int specificSplitToDo = -1, bool genOutputDescriptionData = false)
Definition at line 41 of file animaLowMemPatientToGroupODFComparisonBridge.cxx.
References BuildAndWrite(), anima::ImageDataSplitter< TInputImage >::EmptyMask(), anima::ImageDataSplitter< TInputImage >::GetBlockRegionInsideMargin(), anima::ImageDataSplitter< TInputImage >::GetNbImages(), anima::ImageDataSplitter< TInputImage >::GetOutput(), anima::ImageDataSplitter< TInputImage >::GetSmallMaskWithMargin(), anima::ImageDataSplitter< TInputImage >::GetSpecificBlockRegion(), anima::PatientToGroupODFComparisonImageFilter< PixelScalarType >::New(), anima::ImageDataSplitter< TInputImage >::SetBlockIndex(), anima::ImageDataSplitter< TInputImage >::SetNumberOfBlocks(), and anima::ImageDataSplitter< TInputImage >::Update().
The documentation for this class was generated from the following files:
animaLowMemPatientToGroupODFComparisonBridge.h
animaLowMemPatientToGroupODFComparisonBridge.cxx