ANIMA: anima::NLOPTOptimizers Class Reference
anima::NLOPTOptimizers Class Reference
Implements an ITK wrapper for the NLOPT library.
#include <animaNLOPTOptimizers.h>
Public Types
typedef itk::SmartPointer
< const Self > ConstPointer
typedef
anima::NLOPTParametersConstraintFunction ConstraintsFunctionType
typedef CostFunctionType::Pointer CostFunctionPointer
typedef
itk::SingleValuedCostFunction CostFunctionType
enum nlopt_algorithm {
NLOPT_GN_DIRECT = 0,
NLOPT_GN_DIRECT_L,
NLOPT_GN_DIRECT_L_RAND,
NLOPT_GN_DIRECT_NOSCAL,
NLOPT_GN_DIRECT_L_NOSCAL,
NLOPT_GN_DIRECT_L_RAND_NOSCAL,
NLOPT_GN_ORIG_DIRECT,
NLOPT_GN_ORIG_DIRECT_L,
NLOPT_GD_STOGO,
NLOPT_GD_STOGO_RAND,
NLOPT_LD_LBFGS_NOCEDAL,
NLOPT_LD_LBFGS,
NLOPT_LN_PRAXIS,
NLOPT_LD_VAR1,
NLOPT_LD_VAR2,
NLOPT_LD_TNEWTON,
NLOPT_LD_TNEWTON_RESTART,
NLOPT_LD_TNEWTON_PRECOND,
NLOPT_LD_TNEWTON_PRECOND_RESTART,
NLOPT_GN_CRS2_LM,
NLOPT_GN_MLSL,
NLOPT_GD_MLSL,
NLOPT_GN_MLSL_LDS,
NLOPT_GD_MLSL_LDS,
NLOPT_LD_MMA,
NLOPT_LN_COBYLA,
NLOPT_LN_NEWUOA,
NLOPT_LN_NEWUOA_BOUND,
NLOPT_LN_NELDERMEAD,
NLOPT_LN_SBPLX,
NLOPT_LN_AUGLAG,
NLOPT_LD_AUGLAG,
NLOPT_LN_AUGLAG_EQ,
NLOPT_LD_AUGLAG_EQ,
NLOPT_LN_BOBYQA,
NLOPT_GN_ISRES,
NLOPT_AUGLAG,
NLOPT_AUGLAG_EQ,
NLOPT_G_MLSL,
NLOPT_G_MLSL_LDS,
NLOPT_LD_SLSQP,
NLOPT_LD_CCSAQ,
NLOPT_GN_ESCH
}
Values that represent the nlopt_algorithm to use. Naming conventions:
enum nlopt_result {
NLOPT_FAILURE = -1,
NLOPT_INVALID_ARGS = -2,
NLOPT_OUT_OF_MEMORY = -3,
NLOPT_ROUNDOFF_LIMITED = -4,
NLOPT_FORCED_STOP = -5,
NLOPT_SUCCESS = 1,
NLOPT_STOPVAL_REACHED = 2,
NLOPT_FTOL_REACHED = 3,
NLOPT_XTOL_REACHED = 4,
NLOPT_MAXEVAL_REACHED = 5,
NLOPT_MAXTIME_REACHED = 6
}
Values that represent the result of a nlopt function.
typedef
SingleValuedNonLinearOptimizer::ParametersType ParametersType
typedef itk::SmartPointer< Self > Pointer
typedef NLOPTOptimizers Self
typedef
SingleValuedNonLinearOptimizer Superclass
Public Member Functions
void AddEqualityConstraint (ConstraintsFunctionType *constraint)
Adds a nonlinear equality constraint of the form \(h(x) = 0 \). The parameter tol is a tolerance that is used for the purpose of stopping criteria only: a point x is considered feasible for judging whether to stop the optimization if \(|h(x)| <= tol \). For equality constraints, a small positive tolerance is strongly advised in order to allow NLopt to converge even if the equality constraint is slightly nonzero.
void AddInequalityConstraint (ConstraintsFunctionType *constraint)
Adds a nonlinear inequality constraint of the form \(fc(x) <= 0 \). The parameter tol is a tolerance that is used for the purpose of stopping criteria only: a point x is considered feasible for judging whether to stop the optimization if \(fc(x) <= tol \). A tolerance of zero means that NLopt will try not to consider any x to be converged unless fc is strictly non-positive; generally, at least a small positive tolerance is advisable to reduce sensitivity to rounding errors.
void ClearEqualityConstraints ()
Clears all equality constraints.
void ClearInequalityConstraints ()
Clears all inequality constraints.
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const nlopt_algorithm & GetAlgorithm () const
virtual const MeasureType & GetCurrentCost () const
virtual const nlopt_result & GetErrorCode () const
std::string GetErrorCodeDescription () const
Gets the current error code description as a std::string.
virtual const double & GetFTolAbs () const
virtual const double & GetFTolRel () const
virtual const nlopt_algorithm & GetLocalOptimizer () const
virtual const ParametersType & GetLowerBoundParameters () const
virtual const int & GetMaxEval () const
virtual const bool & GetMaximize () const
virtual const double & GetMaxTime () const
virtual const char * GetNameOfClass () const
virtual const int & GetPopulationSize () const
virtual const double & GetStopVal () const
virtual const ParametersType & GetUpperBoundParameters () const
MeasureType GetValue () const
virtual const int & GetVectorStorageSize () const
virtual unsigned int GetVerboseLevel ()
virtual const double & GetXTolAbs () const
virtual const double & GetXTolRel () const
bool isSuccessful () const
Return true if the optimization was successful (ie the last error code was positive or equal to NLOPT_ROUNDOFF_LIMITED or NLOPT_FORCED_STOP)
virtual void SetAlgorithm (nlopt_algorithm _arg)
virtual void SetErrorCode (nlopt_result _arg)
virtual void SetFTolAbs (double _arg)
virtual void SetFTolRel (double _arg)
virtual void SetLocalOptimizer (nlopt_algorithm _arg)
void SetLowerBoundParameters (const ParametersType &p)
Set the lower bound parameters (not used by all algorithms)
virtual void SetMaxEval (int _arg)
virtual void SetMaximize (bool _arg)
virtual void SetMaxTime (double _arg)
virtual void SetPopulationSize (int _arg)
void SetStopVal (double stopval)
void SetUpperBoundParameters (const ParametersType &p)
Set the upper bound parameters (not used by all algorithms)
virtual void SetVectorStorageSize (int _arg)
virtual void SetVerboseLevel (unsigned int _arg)
virtual void SetXTolAbs (double _arg)
virtual void SetXTolRel (double _arg)
void StartOptimization () ITK_OVERRIDE
Starts the optimization.
void StopOptimization ()
Static Public Member Functions
static Pointer New ()
Protected Member Functions
NLOPTOptimizers ()
Default constructor.
NLOPTOptimizers (const NLOPTOptimizers &)
void PrintSelf (std::ostream &os, itk::Indent indent) const ITK_OVERRIDE
virtual void SetCurrentCost (double _arg)
virtual ~NLOPTOptimizers ()
Destructor.
Static Protected Member Functions
static double NloptFunctionWrapper (unsigned n, const double *x, double *grad, void *data)
NloptFunctionWrapper is called by nlopt to evaluate the function f to minimize. NloptFunctionWrapper converts the nlopt parameters to the SingleValuedCostFunction parameters, and call the SingleValuedCostFunction to actually compute the value of f.
Detailed Description
Implements an ITK wrapper for the NLOPT library.
Wrapper for the NLOPT library
Version 1.0.0
This code was graciously provided to us by the CRL at Boston.
Copyright (c) 2010-2011 Children's Hospital Boston.
Benoit Scherrer, CRL (Computational Radiology Laboratory), Harvard Medical School
Example
The wrapper is very easy to use. Here is an example of how to minimimze a function with MyCostFunction being a regular itk::SingleValuedCostFunction
        // Create the cost function
        itk::MyCostFunction::Pointer costFun = itk::MyCostFunction::New();
        // Create the optimizer
        itk::NLOPTOptimizers::Pointer optimizer = itk::NLOPTOptimizers::New();
        optimizer->SetCostFunction(costFun);
        // Set the parameters
        optimizer->SetMaxEval(500);
        optimizer->SetAlgorithm(itk::NLOPTOptimizers::NLOPT_LN_BOBYQA);
        // Set the initial position
        itk::NLOPTOptimizers::ParametersType pinit(2);
        pinit[0]=pinit[1] = 4;
        optimizer->SetInitialPosition(pinit);
        optimizer->StartOptimization();
        std::cout<<"Return code "<<(int)optimizer->GetErrorCode();
        std::cout<<" = "<<optimizer->GetErrorCodeDescription()<<endl;
        std::cout<<"Position = "<<optimizer->GetCurrentPosition()<<endl;
        std::cout<<"Value = "<<optimizer->GetCurrentCost()<<endl;
For more information about NLOPT and the available algorithms:
http://ab-initio.mit.edu/wiki/index.php/NLopt
License
This software is licensed by the copyright holder under the terms of the Open Software License version 3.0.
http://www.opensource.org/licenses/osl-3.0.php
Notice.
This research was carried out in the Computational Radiology Laboratory of Children's Hospital, Boston and Harvard Medical School.
http://www.crl.med.harvard.edu
For more information contact: simon.warfield@childrens.harvard.edu
This research work was made possible by Grant Number R01 RR021885 (Principal Investigator: Simon K. Warfield, Ph.D.) to Children's Hospital, Boston from the National Center for Research Resources (NCRR), a component of the National Institutes of Health (NIH).
NLopt is a free/open-source library for nonlinear optimization, providing a common interface for a number of different free optimization routines available online as well as original implementations of various other algorithms.
WEBSITE: http://ab-initio.mit.edu/wiki/index.php/NLopt
AUTHOR: Steven G. Johnson
This ITK wrapper was created by:
Benoit Scherrer, CRL, Harvard Medical School.
Copyright (c) 2010-2011 Children's Hospital Boston
Author:
Benoit Scherrer
Date:
July 2010
Definition at line 94 of file animaNLOPTOptimizers.h.
Member Typedef Documentation
typedef itk::SmartPointer<const Self> anima::NLOPTOptimizers::ConstPointer
Standard ITK "ConstPointer" typedef.
Definition at line 102 of file animaNLOPTOptimizers.h.
typedef anima::NLOPTParametersConstraintFunction anima::NLOPTOptimizers::ConstraintsFunctionType
Base constraints (for inequality and equality)
Definition at line 105 of file animaNLOPTOptimizers.h.
typedef CostFunctionType::Pointer anima::NLOPTOptimizers::CostFunctionPointer
Definition at line 219 of file animaNLOPTOptimizers.h.
typedef itk::SingleValuedCostFunction anima::NLOPTOptimizers::CostFunctionType
Type of the Cost Function
Definition at line 215 of file animaNLOPTOptimizers.h.
typedef SingleValuedNonLinearOptimizer::ParametersType anima::NLOPTOptimizers::ParametersType
Parameter type
Definition at line 104 of file animaNLOPTOptimizers.h.
typedef itk::SmartPointer<Self> anima::NLOPTOptimizers::Pointer
Standard ITK "Pointer" typedef.
Definition at line 101 of file animaNLOPTOptimizers.h.
typedef NLOPTOptimizers anima::NLOPTOptimizers::Self
Standard ITK "Self" typedef.
Definition at line 99 of file animaNLOPTOptimizers.h.
typedef SingleValuedNonLinearOptimizer anima::NLOPTOptimizers::Superclass
Standard ITK "Superclass" typedef.
Definition at line 100 of file animaNLOPTOptimizers.h.
Member Enumeration Documentation
enum anima::NLOPTOptimizers::nlopt_algorithm
Values that represent the nlopt_algorithm to use. Naming conventions:
NLOPT_{G/L}{D/N}_ : global/local derivative/no-derivative optimization, respectively
_RAND : algorithms involve some randomization.
*_NOSCAL : algorithms are *not* scaled to a unit hypercube (i.e. they are sensitive to the units of x)
Enumerator:
NLOPT_GN_DIRECT
NLOPT_GN_DIRECT_L
NLOPT_GN_DIRECT_L_RAND
NLOPT_GN_DIRECT_NOSCAL
NLOPT_GN_DIRECT_L_NOSCAL
NLOPT_GN_DIRECT_L_RAND_NOSCAL
NLOPT_GN_ORIG_DIRECT
NLOPT_GN_ORIG_DIRECT_L
NLOPT_GD_STOGO
NLOPT_GD_STOGO_RAND
NLOPT_LD_LBFGS_NOCEDAL
NLOPT_LD_LBFGS
NLOPT_LN_PRAXIS
NLOPT_LD_VAR1
NLOPT_LD_VAR2
NLOPT_LD_TNEWTON
NLOPT_LD_TNEWTON_RESTART
NLOPT_LD_TNEWTON_PRECOND
NLOPT_LD_TNEWTON_PRECOND_RESTART
NLOPT_GN_CRS2_LM
NLOPT_GN_MLSL
NLOPT_GD_MLSL
NLOPT_GN_MLSL_LDS
NLOPT_GD_MLSL_LDS
NLOPT_LD_MMA
NLOPT_LN_COBYLA
NLOPT_LN_NEWUOA
NLOPT_LN_NEWUOA_BOUND
NLOPT_LN_NELDERMEAD
NLOPT_LN_SBPLX
NLOPT_LN_AUGLAG
NLOPT_LD_AUGLAG
NLOPT_LN_AUGLAG_EQ
NLOPT_LD_AUGLAG_EQ
NLOPT_LN_BOBYQA
NLOPT_GN_ISRES
NLOPT_AUGLAG
NLOPT_AUGLAG_EQ
NLOPT_G_MLSL
NLOPT_G_MLSL_LDS
NLOPT_LD_SLSQP
NLOPT_LD_CCSAQ
NLOPT_GN_ESCH
Definition at line 120 of file animaNLOPTOptimizers.h.
enum anima::NLOPTOptimizers::nlopt_result
Values that represent the result of a nlopt function.
Enumerator:
NLOPT_FAILURE
generic failure code
NLOPT_INVALID_ARGS
Invalid arguments (eg lower bounds bigger than upper bounds, unknown algorithm, etc)
NLOPT_OUT_OF_MEMORY
Ran out of memory
NLOPT_ROUNDOFF_LIMITED
Halted because roundoff errors limited progress
NLOPT_FORCED_STOP
Halted because of a forced termination
See also:
StopOptimization
NLOPT_SUCCESS
generic success code
NLOPT_STOPVAL_REACHED
Optimization stopped because 'stopval' was reached
NLOPT_FTOL_REACHED
Optimization stopped because 'ftol_rel' or 'ftol_abs' was reached
NLOPT_XTOL_REACHED
Optimization stopped because 'xtol_rel' or 'xtol_abs' was reached
NLOPT_MAXEVAL_REACHED
Optimization stopped because 'maxeval' was reached.
NLOPT_MAXTIME_REACHED
Optimization stopped because 'maxtime' was reached.
Definition at line 196 of file animaNLOPTOptimizers.h.
Constructor & Destructor Documentation
anima::NLOPTOptimizers::NLOPTOptimizers () [protected]
Default constructor.
Author:
Benoit Scherrer
Date:
July 2010
Definition at line 45 of file animaNLOPTOptimizers.cxx.
anima::NLOPTOptimizers::NLOPTOptimizers (const NLOPTOptimizers &) [protected]
anima::NLOPTOptimizers::~NLOPTOptimizers () [protected, virtual]
Destructor.
Author:
Benoit Scherrer
Date:
July 2010
Definition at line 74 of file animaNLOPTOptimizers.cxx.
Member Function Documentation
void anima::NLOPTOptimizers::AddEqualityConstraint (ConstraintsFunctionType * constraint)
Adds a nonlinear equality constraint of the form \(h(x) = 0 \). The parameter tol is a tolerance that is used for the purpose of stopping criteria only: a point x is considered feasible for judging whether to stop the optimization if \(|h(x)| <= tol \). For equality constraints, a small positive tolerance is strongly advised in order to allow NLopt to converge even if the equality constraint is slightly nonzero.
(For any algorithm listed as "derivative-free" below, the grad argument to fc or h will always be NULL and need never be computed.)
Author:
Benoit Scherrer
Date:
July 2010
Parameters:
constraint The constraint function containing all details
Definition at line 381 of file animaNLOPTOptimizers.cxx.
void anima::NLOPTOptimizers::AddInequalityConstraint (ConstraintsFunctionType * constraint)
Adds a nonlinear inequality constraint of the form \(fc(x) <= 0 \). The parameter tol is a tolerance that is used for the purpose of stopping criteria only: a point x is considered feasible for judging whether to stop the optimization if \(fc(x) <= tol \). A tolerance of zero means that NLopt will try not to consider any x to be converged unless fc is strictly non-positive; generally, at least a small positive tolerance is advisable to reduce sensitivity to rounding errors.
Author:
Benoit Scherrer
Date:
July 2010
Parameters:
constraint The constraint function containing all details
Definition at line 346 of file animaNLOPTOptimizers.cxx.
void anima::NLOPTOptimizers::ClearEqualityConstraints ()
Clears all equality constraints.
Author:
Benoit Scherrer
Date:
July 2010
Definition at line 394 of file animaNLOPTOptimizers.cxx.
void anima::NLOPTOptimizers::ClearInequalityConstraints ()
Clears all inequality constraints.
Author:
Benoit Scherrer
Date:
July 2010
Definition at line 359 of file animaNLOPTOptimizers.cxx.
virtual::itk::LightObject::Pointer anima::NLOPTOptimizers::CreateAnother (void) const
virtual const nlopt_algorithm& anima::NLOPTOptimizers::GetAlgorithm () const [virtual]
virtual const MeasureType& anima::NLOPTOptimizers::GetCurrentCost () const [virtual]
Returns the current value
virtual const nlopt_result& anima::NLOPTOptimizers::GetErrorCode () const [virtual]
std::string anima::NLOPTOptimizers::GetErrorCodeDescription () const
Gets the current error code description as a std::string.
Author:
Benoit Scherrer
Date:
July 2010
Returns:
The error code description.
Definition at line 295 of file animaNLOPTOptimizers.cxx.
virtual const double& anima::NLOPTOptimizers::GetFTolAbs () const [virtual]
virtual const double& anima::NLOPTOptimizers::GetFTolRel () const [virtual]
virtual const nlopt_algorithm& anima::NLOPTOptimizers::GetLocalOptimizer () const [virtual]
virtual const ParametersType& anima::NLOPTOptimizers::GetLowerBoundParameters () const [virtual]
virtual const int& anima::NLOPTOptimizers::GetMaxEval () const [virtual]
virtual const bool& anima::NLOPTOptimizers::GetMaximize () const [virtual]
virtual const double& anima::NLOPTOptimizers::GetMaxTime () const [virtual]
virtual const char* anima::NLOPTOptimizers::GetNameOfClass () const [virtual]
Run-time type information (and related methods).
virtual const int& anima::NLOPTOptimizers::GetPopulationSize () const [virtual]
virtual const double& anima::NLOPTOptimizers::GetStopVal () const [virtual]
virtual const ParametersType& anima::NLOPTOptimizers::GetUpperBoundParameters () const [virtual]
MeasureType anima::NLOPTOptimizers::GetValue () const [inline]
Returns the current value
Definition at line 237 of file animaNLOPTOptimizers.h.
Referenced by NloptFunctionWrapper().
virtual const int& anima::NLOPTOptimizers::GetVectorStorageSize () const [virtual]
virtual unsigned int anima::NLOPTOptimizers::GetVerboseLevel () [virtual]
virtual const double& anima::NLOPTOptimizers::GetXTolAbs () const [virtual]
virtual const double& anima::NLOPTOptimizers::GetXTolRel () const [virtual]
bool anima::NLOPTOptimizers::isSuccessful () const
Return true if the optimization was successful (ie the last error code was positive or equal to NLOPT_ROUNDOFF_LIMITED or NLOPT_FORCED_STOP)
Author:
Benoit Scherrer
Date:
July 2010
Returns:
true if successful, false if not.
Definition at line 275 of file animaNLOPTOptimizers.cxx.
static Pointer anima::NLOPTOptimizers::New () [static]
Method for creation through the object factory.
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::CreateOptimizer().
double anima::NLOPTOptimizers::NloptFunctionWrapper (unsigned n, const double * x, double * grad, void * data) [static, protected]
NloptFunctionWrapper is called by nlopt to evaluate the function f to minimize. NloptFunctionWrapper converts the nlopt parameters to the SingleValuedCostFunction parameters, and call the SingleValuedCostFunction to actually compute the value of f.
Author:
Benoit Scherrer
Date:
July 2010
Parameters:
n The.
x The x coordinate.
[in,out] grad If non-null, the graduated.
[in,out] data If non-null, the data.
Returns:
.
Definition at line 95 of file animaNLOPTOptimizers.cxx.
References GetValue().
void anima::NLOPTOptimizers::PrintSelf (std::ostream & os, itk::Indent indent) const [protected]
Definition at line 436 of file animaNLOPTOptimizers.cxx.
virtual void anima::NLOPTOptimizers::SetAlgorithm (nlopt_algorithm _arg) [virtual]
NLOPT Algorithm to use
virtual void anima::NLOPTOptimizers::SetCurrentCost (double _arg) [protected, virtual]
virtual void anima::NLOPTOptimizers::SetErrorCode (nlopt_result _arg) [virtual]
Returns the last error code of NLOPT
virtual void anima::NLOPTOptimizers::SetFTolAbs (double _arg) [virtual]
Stopping criteria: Set absolute tolerance on function value: stop when an optimization step (or an estimate of the optimum) changes the function value by less than tol. Criterion is disabled if tol is non-positive.
Note:
Multiple stopping criteria for the optimization are supported. The optimization halts whenever any one of these criteria is satisfied. In some cases, the precise interpretation of the stopping criterion depends on the optimization algorithm above (although NLopt try to make them as consistent as reasonably possible), and some algorithms do not support all of the stopping criteria.
You do not need to use all of the stopping criteria! In most cases, you only need one or two, and can omit the remainder (all criteria are disabled by default).
virtual void anima::NLOPTOptimizers::SetFTolRel (double _arg) [virtual]
Stopping criteria: Set relative tolerance on function value: stop when an optimization step (or an estimate of the optimum) changes the objective function value by less than tol multiplied by the absolute value of the function value. (If there is any chance that your optimum function value is close to zero, you might want to set an absolute tolerance with nlopt_set_ftol_abs as well.) Criterion is disabled if tol is non-positive.
Note:
Multiple stopping criteria for the optimization are supported. The optimization halts whenever any one of these criteria is satisfied. In some cases, the precise interpretation of the stopping criterion depends on the optimization algorithm above (although NLopt try to make them as consistent as reasonably possible), and some algorithms do not support all of the stopping criteria.
You do not need to use all of the stopping criteria! In most cases, you only need one or two, and can omit the remainder (all criteria are disabled by default).
virtual void anima::NLOPTOptimizers::SetLocalOptimizer (nlopt_algorithm _arg) [virtual]
Set local optimizer for AUGLAG and MLSL algos
void anima::NLOPTOptimizers::SetLowerBoundParameters (const ParametersType & p)
Set the lower bound parameters (not used by all algorithms)
Author:
Benoit Scherrer
Date:
July 2010
Parameters:
p The lower bound parameters.
Definition at line 409 of file animaNLOPTOptimizers.cxx.
virtual void anima::NLOPTOptimizers::SetMaxEval (int _arg) [virtual]
Stopping criteria: Stop when the number of function evaluations exceeds maxeval. (This is not a strict maximum: the number of function evaluations may exceed maxeval slightly, depending upon the algorithm.) Criterion is disabled if maxeval is non-positive.
Note:
Multiple stopping criteria for the optimization are supported. The optimization halts whenever any one of these criteria is satisfied. In some cases, the precise interpretation of the stopping criterion depends on the optimization algorithm above (although NLopt try to make them as consistent as reasonably possible), and some algorithms do not support all of the stopping criteria.
You do not need to use all of the stopping criteria! In most cases, you only need one or two, and can omit the remainder (all criteria are disabled by default).
virtual void anima::NLOPTOptimizers::SetMaximize (bool _arg) [virtual]
Set if the Optimizer should Maximize the metric
virtual void anima::NLOPTOptimizers::SetMaxTime (double _arg) [virtual]
Stopping criteria: Stop when the optimization time (in seconds) exceeds maxtime. (This is not a strict maximum: the time may exceed maxtime slightly, depending upon the algorithm and on how slow your function evaluation is.) Criterion is disabled if maxtime is non-positive
Note:
Multiple stopping criteria for the optimization are supported. The optimization halts whenever any one of these criteria is satisfied. In some cases, the precise interpretation of the stopping criterion depends on the optimization algorithm above (although NLopt try to make them as consistent as reasonably possible), and some algorithms do not support all of the stopping criteria.
You do not need to use all of the stopping criteria! In most cases, you only need one or two, and can omit the remainder (all criteria are disabled by default).
virtual void anima::NLOPTOptimizers::SetPopulationSize (int _arg) [virtual]
Stochastic population size: This is for random global optimization. It sets the number of random particles to propagate from.
void anima::NLOPTOptimizers::SetStopVal (double stopval) [inline]
Stopping criteria: Stop when an objective value of at least stopval is found: stop minimizing when an objective value <= stopval is found, or stop maximizing a value >= stopval is found. (Setting stopval to -HUGE_VAL for minimizing or +HUGE_VAL for maximizing disables this stopping criterion.)
Note:
Multiple stopping criteria for the optimization are supported. The optimization halts whenever any one of these criteria is satisfied. In some cases, the precise interpretation of the stopping criterion depends on the optimization algorithm above (although NLopt try to make them as consistent as reasonably possible), and some algorithms do not support all of the stopping criteria.
You do not need to use all of the stopping criteria! In most cases, you only need one or two, and can omit the remainder (all criteria are disabled by default).
Definition at line 265 of file animaNLOPTOptimizers.h.
void anima::NLOPTOptimizers::SetUpperBoundParameters (const ParametersType & p)
Set the upper bound parameters (not used by all algorithms)
Author:
Benoit Scherrer
Date:
July 2010
Parameters:
p The upper bound parameters.
Definition at line 426 of file animaNLOPTOptimizers.cxx.
virtual void anima::NLOPTOptimizers::SetVectorStorageSize (int _arg) [virtual]
Vector storage size: number of gradients to "remember" from previous optimization steps: increasing it increases the memory requirements but speeds convergence.
virtual void anima::NLOPTOptimizers::SetVerboseLevel (unsigned int _arg) [virtual]
virtual void anima::NLOPTOptimizers::SetXTolAbs (double _arg) [virtual]
Stopping criteria: Set the absolute tolerance on optimization parameters.
Todo:
Set the absolute tolerances for each parameter separately by using nlopt_set_xtol_abs(nlopt_opt opt, const double* tol)
Note:
Multiple stopping criteria for the optimization are supported. The optimization halts whenever any one of these criteria is satisfied. In some cases, the precise interpretation of the stopping criterion depends on the optimization algorithm above (although NLopt try to make them as consistent as reasonably possible), and some algorithms do not support all of the stopping criteria.
You do not need to use all of the stopping criteria! In most cases, you only need one or two, and can omit the remainder (all criteria are disabled by default).
virtual void anima::NLOPTOptimizers::SetXTolRel (double _arg) [virtual]
Stopping criteria: Set relative tolerance on optimization parameters: stop when an optimization step (or an estimate of the optimum) changes every parameter by less than tol multiplied by the absolute value of the parameter. (If there is any chance that an optimal parameter is close to zero, you might want to set an absolute tolerance with nlopt_set_xtol_abs as well.) Criterion is disabled if tol is non-positive.
Note:
Multiple stopping criteria for the optimization are supported. The optimization halts whenever any one of these criteria is satisfied. In some cases, the precise interpretation of the stopping criterion depends on the optimization algorithm above (although NLopt try to make them as consistent as reasonably possible), and some algorithms do not support all of the stopping criteria.
You do not need to use all of the stopping criteria! In most cases, you only need one or two, and can omit the remainder (all criteria are disabled by default).
void anima::NLOPTOptimizers::StartOptimization ()
Starts the optimization.
Author:
Benoit Scherrer
Date:
July 2010
Exceptions:
itk::ExceptionObject Thrown when exception.
Definition at line 134 of file animaNLOPTOptimizers.cxx.
void anima::NLOPTOptimizers::StopOptimization () [inline]
Tells Nlopt to stop the optimization at the next iteration and to returns the best point found so far.
Definition at line 402 of file animaNLOPTOptimizers.h.
The documentation for this class was generated from the following files:
animaNLOPTOptimizers.h
animaNLOPTOptimizers.cxx