ANIMA: anima::BaseBlockMatcher< TInputImageType > Class Template Reference
anima::BaseBlockMatcher< TInputImageType > Class Template Reference
#include <animaBaseBlockMatcher.h>
Classes
struct ThreadedMatchData
Public Types
typedef
anima::BaseTransformAgregator
< TInputImageType::ImageDimension > AgregatorType
typedef
BaseInputTransformType::Pointer BaseInputTransformPointer
typedef
AgregatorType::BaseInputTransformType BaseInputTransformType
typedef
DamWeightsImageType::Pointer DamWeightsImagePointer
typedef itk::Image
< InternalScalarType,
TInputImageType::ImageDimension > DamWeightsImageType
typedef InputImageType::RegionType ImageRegionType
typedef InputImageType::Pointer InputImagePointer
typedef TInputImageType InputImageType
typedef
AgregatorType::InternalScalarType InternalScalarType
typedef MaskImageType::Pointer MaskImagePointer
typedef itk::Image< unsigned
char,
TInputImageType::ImageDimension > MaskImageType
typedef MetricType::Pointer MetricPointer
typedef
itk::SingleValuedCostFunction MetricType
enum OptimizerDefinition {
Exhaustive = 0,
Bobyqa
}
typedef OptimizerType::Pointer OptimizerPointer
typedef
itk::SingleValuedNonLinearOptimizer OptimizerType
typedef InputImageType::PointType PointType
typedef BaseBlockMatcher Self
Public Member Functions
BaseBlockMatcher ()
virtual
AgregatorType::TRANSFORM_TYPE GetAgregatorInputTransformType ()=0
DamWeightsImagePointer & GetBlockDamWeights ()
MaskImagePointer & GetBlockGenerationMask ()
double GetBlockPercentageKept ()
std::vector< PointType > & GetBlockPositions ()
ImageRegionType & GetBlockRegion (unsigned int i)
std::vector< ImageRegionType > & GetBlockRegions ()
unsigned int GetBlockSize ()
unsigned int GetBlockSpacing ()
BaseInputTransformPointer & GetBlockTransformPointer (unsigned int i)
std::vector
< BaseInputTransformPointer > & GetBlockTransformPointers ()
double GetBlockVarianceThreshold ()
const std::vector< double > & GetBlockWeights ()
double GetDamDistance ()
virtual bool GetMaximizedMetric ()=0
InputImagePointer & GetMovingImage ()
unsigned int GetNumberOfThreads ()
OptimizerDefinition GetOptimizerType ()
InputImagePointer & GetReferenceImage ()
double GetSearchRadius ()
bool GetUseTransformationDam ()
bool GetVerbose ()
void SetBlockDamWeights (DamWeightsImagePointer &damWeights)
void SetBlockGenerationMask (MaskImageType *image)
void SetBlockPercentageKept (double val)
void SetBlockSize (unsigned int val)
void SetBlockSpacing (unsigned int val)
void SetBlockVarianceThreshold (double val)
void SetDamDistance (double val)
void SetFinalRadius (double val)
void SetForceComputeBlocks (bool val)
void SetMovingImage (InputImageType *image)
void SetNumberOfThreads (unsigned int val)
void SetOptimizerMaximumIterations (unsigned int val)
void SetOptimizerType (OptimizerDefinition val)
void SetReferenceImage (InputImageType *image)
void SetSearchRadius (double val)
void SetStepSize (double val)
void SetUseTransformationDam (bool val)
void SetVerbose (bool value)
void Update ()
virtual ~BaseBlockMatcher ()
Protected Member Functions
void BlockMatch (unsigned int startIndex, unsigned int endIndex)
virtual void BlockMatchingSetup (MetricPointer &metric, unsigned int block)=0
virtual double ComputeBlockWeight (double val, unsigned int block)=0
virtual BaseInputTransformPointer GetNewBlockTransform (PointType &blockCenter)=0
virtual void InitializeBlocks ()
void ProcessBlockMatch ()
void SetBlockPositions (std::vector< PointType > &val)
void SetBlockRegions (std::vector< ImageRegionType > &val)
void SetBlockWeights (std::vector< double > &val)
void SetDBlockDamWeights (DamWeightsImagePointer &val)
virtual MetricPointer SetupMetric ()=0
virtual OptimizerPointer SetupOptimizer ()
virtual void TransformDependantOptimizerSetup (OptimizerPointer &optimizer)=0
Static Protected Member Functions
static ITK_THREAD_RETURN_TYPE ThreadedMatching (void *arg)
Detailed Description
template<typename TInputImageType>
class anima::BaseBlockMatcher< TInputImageType >
Definition at line 12 of file animaBaseBlockMatcher.h.
Member Typedef Documentation
template<typename TInputImageType> typedef anima::BaseTransformAgregator<TInputImageType::ImageDimension> anima::BaseBlockMatcher< TInputImageType >::AgregatorType
Reimplemented in anima::TensorBlockMatcher< TInputImageType >, anima::DistortionCorrectionBlockMatcher< TInputImageType >, anima::BaseAffineBlockMatcher< TInputImageType >, and anima::AnatomicalBlockMatcher< TInputImageType >.
Definition at line 30 of file animaBaseBlockMatcher.h.
template<typename TInputImageType> typedef BaseInputTransformType::Pointer anima::BaseBlockMatcher< TInputImageType >::BaseInputTransformPointer
Reimplemented in anima::TensorBlockMatcher< TInputImageType >, anima::DistortionCorrectionBlockMatcher< TInputImageType >, anima::BaseAffineBlockMatcher< TInputImageType >, and anima::AnatomicalBlockMatcher< TInputImageType >.
Definition at line 35 of file animaBaseBlockMatcher.h.
template<typename TInputImageType> typedef AgregatorType::BaseInputTransformType anima::BaseBlockMatcher< TInputImageType >::BaseInputTransformType
Definition at line 34 of file animaBaseBlockMatcher.h.
template<typename TInputImageType> typedef DamWeightsImageType::Pointer anima::BaseBlockMatcher< TInputImageType >::DamWeightsImagePointer
Definition at line 33 of file animaBaseBlockMatcher.h.
template<typename TInputImageType> typedef itk::Image<InternalScalarType,TInputImageType::ImageDimension> anima::BaseBlockMatcher< TInputImageType >::DamWeightsImageType
Definition at line 32 of file animaBaseBlockMatcher.h.
template<typename TInputImageType> typedef InputImageType::RegionType anima::BaseBlockMatcher< TInputImageType >::ImageRegionType
Definition at line 27 of file animaBaseBlockMatcher.h.
template<typename TInputImageType> typedef InputImageType::Pointer anima::BaseBlockMatcher< TInputImageType >::InputImagePointer
Definition at line 26 of file animaBaseBlockMatcher.h.
template<typename TInputImageType> typedef TInputImageType anima::BaseBlockMatcher< TInputImageType >::InputImageType
Reimplemented in anima::TensorBlockMatcher< TInputImageType >, anima::DistortionCorrectionBlockMatcher< TInputImageType >, anima::BaseAffineBlockMatcher< TInputImageType >, and anima::AnatomicalBlockMatcher< TInputImageType >.
Definition at line 25 of file animaBaseBlockMatcher.h.
template<typename TInputImageType> typedef AgregatorType::InternalScalarType anima::BaseBlockMatcher< TInputImageType >::InternalScalarType
Definition at line 31 of file animaBaseBlockMatcher.h.
template<typename TInputImageType> typedef MaskImageType::Pointer anima::BaseBlockMatcher< TInputImageType >::MaskImagePointer
Definition at line 38 of file animaBaseBlockMatcher.h.
template<typename TInputImageType> typedef itk::Image<unsigned char, TInputImageType::ImageDimension> anima::BaseBlockMatcher< TInputImageType >::MaskImageType
Definition at line 37 of file animaBaseBlockMatcher.h.
template<typename TInputImageType> typedef MetricType::Pointer anima::BaseBlockMatcher< TInputImageType >::MetricPointer
Reimplemented in anima::TensorBlockMatcher< TInputImageType >, anima::DistortionCorrectionBlockMatcher< TInputImageType >, anima::BaseAffineBlockMatcher< TInputImageType >, and anima::AnatomicalBlockMatcher< TInputImageType >.
Definition at line 46 of file animaBaseBlockMatcher.h.
template<typename TInputImageType> typedef itk::SingleValuedCostFunction anima::BaseBlockMatcher< TInputImageType >::MetricType
Type of the metric.
Definition at line 45 of file animaBaseBlockMatcher.h.
template<typename TInputImageType> typedef OptimizerType::Pointer anima::BaseBlockMatcher< TInputImageType >::OptimizerPointer
Reimplemented in anima::TensorBlockMatcher< TInputImageType >, anima::DistortionCorrectionBlockMatcher< TInputImageType >, anima::BaseAffineBlockMatcher< TInputImageType >, and anima::AnatomicalBlockMatcher< TInputImageType >.
Definition at line 42 of file animaBaseBlockMatcher.h.
template<typename TInputImageType> typedef itk::SingleValuedNonLinearOptimizer anima::BaseBlockMatcher< TInputImageType >::OptimizerType
Type of the optimizer.
Definition at line 41 of file animaBaseBlockMatcher.h.
template<typename TInputImageType> typedef InputImageType::PointType anima::BaseBlockMatcher< TInputImageType >::PointType
Reimplemented in anima::TensorBlockMatcher< TInputImageType >, anima::DistortionCorrectionBlockMatcher< TInputImageType >, anima::BaseAffineBlockMatcher< TInputImageType >, and anima::AnatomicalBlockMatcher< TInputImageType >.
Definition at line 28 of file animaBaseBlockMatcher.h.
template<typename TInputImageType> typedef BaseBlockMatcher anima::BaseBlockMatcher< TInputImageType >::Self
Definition at line 15 of file animaBaseBlockMatcher.h.
Member Enumeration Documentation
template<typename TInputImageType> enum anima::BaseBlockMatcher::OptimizerDefinition
Enumerator:
Exhaustive
Bobyqa
Definition at line 19 of file animaBaseBlockMatcher.h.
Constructor & Destructor Documentation
template<typename TInputImageType > anima::BaseBlockMatcher< TInputImageType >::BaseBlockMatcher ()
Definition at line 14 of file animaBaseBlockMatcher.hxx.
References Bobyqa.
template<typename TInputImageType> virtual anima::BaseBlockMatcher< TInputImageType >::~BaseBlockMatcher () [inline, virtual]
Definition at line 17 of file animaBaseBlockMatcher.h.
Member Function Documentation
template<typename TInputImageType > void anima::BaseBlockMatcher< TInputImageType >::BlockMatch (unsigned int startIndex, unsigned int endIndex) [protected]
Definition at line 217 of file animaBaseBlockMatcher.hxx.
template<typename TInputImageType> virtual void anima::BaseBlockMatcher< TInputImageType >::BlockMatchingSetup (MetricPointer & metric, unsigned int block) [protected, pure virtual]
Implemented in anima::DistortionCorrectionBlockMatcher< TInputImageType >, and anima::BaseAffineBlockMatcher< TInputImageType >.
template<typename TInputImageType> virtual double anima::BaseBlockMatcher< TInputImageType >::ComputeBlockWeight (double val, unsigned int block) [protected, pure virtual]
Implemented in anima::DistortionCorrectionBlockMatcher< TInputImageType >, anima::TensorBlockMatcher< TInputImageType >, and anima::AnatomicalBlockMatcher< TInputImageType >.
template<typename TInputImageType> virtual AgregatorType::TRANSFORM_TYPE anima::BaseBlockMatcher< TInputImageType >::GetAgregatorInputTransformType () [pure virtual]
Implemented in anima::DistortionCorrectionBlockMatcher< TInputImageType >, and anima::BaseAffineBlockMatcher< TInputImageType >.
template<typename TInputImageType> DamWeightsImagePointer& anima::BaseBlockMatcher< TInputImageType >::GetBlockDamWeights () [inline]
Definition at line 88 of file animaBaseBlockMatcher.h.
template<typename TInputImageType> MaskImagePointer& anima::BaseBlockMatcher< TInputImageType >::GetBlockGenerationMask () [inline]
Definition at line 101 of file animaBaseBlockMatcher.h.
template<typename TInputImageType> double anima::BaseBlockMatcher< TInputImageType >::GetBlockPercentageKept () [inline]
Definition at line 62 of file animaBaseBlockMatcher.h.
template<typename TInputImageType> std::vector<PointType>& anima::BaseBlockMatcher< TInputImageType >::GetBlockPositions () [inline]
Definition at line 85 of file animaBaseBlockMatcher.h.
template<typename TInputImageType> ImageRegionType& anima::BaseBlockMatcher< TInputImageType >::GetBlockRegion (unsigned int i) [inline]
Definition at line 87 of file animaBaseBlockMatcher.h.
template<typename TInputImageType> std::vector<ImageRegionType>& anima::BaseBlockMatcher< TInputImageType >::GetBlockRegions () [inline]
Definition at line 86 of file animaBaseBlockMatcher.h.
template<typename TInputImageType> unsigned int anima::BaseBlockMatcher< TInputImageType >::GetBlockSize () [inline]
Definition at line 65 of file animaBaseBlockMatcher.h.
template<typename TInputImageType> unsigned int anima::BaseBlockMatcher< TInputImageType >::GetBlockSpacing () [inline]
Definition at line 68 of file animaBaseBlockMatcher.h.
template<typename TInputImageType> BaseInputTransformPointer& anima::BaseBlockMatcher< TInputImageType >::GetBlockTransformPointer (unsigned int i) [inline]
Definition at line 92 of file animaBaseBlockMatcher.h.
template<typename TInputImageType> std::vector<BaseInputTransformPointer>& anima::BaseBlockMatcher< TInputImageType >::GetBlockTransformPointers () [inline]
Definition at line 91 of file animaBaseBlockMatcher.h.
template<typename TInputImageType> double anima::BaseBlockMatcher< TInputImageType >::GetBlockVarianceThreshold () [inline]
Definition at line 59 of file animaBaseBlockMatcher.h.
template<typename TInputImageType> const std::vector<double>& anima::BaseBlockMatcher< TInputImageType >::GetBlockWeights () [inline]
Definition at line 94 of file animaBaseBlockMatcher.h.
template<typename TInputImageType> double anima::BaseBlockMatcher< TInputImageType >::GetDamDistance () [inline]
Definition at line 74 of file animaBaseBlockMatcher.h.
template<typename TInputImageType> virtual bool anima::BaseBlockMatcher< TInputImageType >::GetMaximizedMetric () [pure virtual]
Implemented in anima::DistortionCorrectionBlockMatcher< TInputImageType >, anima::TensorBlockMatcher< TInputImageType >, and anima::AnatomicalBlockMatcher< TInputImageType >.
template<typename TInputImageType> InputImagePointer& anima::BaseBlockMatcher< TInputImageType >::GetMovingImage () [inline]
Definition at line 100 of file animaBaseBlockMatcher.h.
template<typename TInputImageType> virtual BaseInputTransformPointer anima::BaseBlockMatcher< TInputImageType >::GetNewBlockTransform (PointType & blockCenter) [protected, pure virtual]
Implemented in anima::DistortionCorrectionBlockMatcher< TInputImageType >, and anima::BaseAffineBlockMatcher< TInputImageType >.
template<typename TInputImageType> unsigned int anima::BaseBlockMatcher< TInputImageType >::GetNumberOfThreads () [inline]
Definition at line 56 of file animaBaseBlockMatcher.h.
template<typename TInputImageType> OptimizerDefinition anima::BaseBlockMatcher< TInputImageType >::GetOptimizerType () [inline]
Definition at line 97 of file animaBaseBlockMatcher.h.
template<typename TInputImageType> InputImagePointer& anima::BaseBlockMatcher< TInputImageType >::GetReferenceImage () [inline]
Definition at line 99 of file animaBaseBlockMatcher.h.
template<typename TInputImageType> double anima::BaseBlockMatcher< TInputImageType >::GetSearchRadius () [inline]
Definition at line 77 of file animaBaseBlockMatcher.h.
template<typename TInputImageType> bool anima::BaseBlockMatcher< TInputImageType >::GetUseTransformationDam () [inline]
Definition at line 71 of file animaBaseBlockMatcher.h.
template<typename TInputImageType> bool anima::BaseBlockMatcher< TInputImageType >::GetVerbose () [inline]
Definition at line 106 of file animaBaseBlockMatcher.h.
template<typename TInputImageType > void anima::BaseBlockMatcher< TInputImageType >::InitializeBlocks () [protected, virtual]
Definition at line 41 of file animaBaseBlockMatcher.hxx.
template<typename TInputImageType > void anima::BaseBlockMatcher< TInputImageType >::ProcessBlockMatch () [protected]
Definition at line 181 of file animaBaseBlockMatcher.hxx.
Referenced by anima::BaseBlockMatcher< TInputImageType >::ThreadedMatching().
template<typename TInputImageType> void anima::BaseBlockMatcher< TInputImageType >::SetBlockDamWeights (DamWeightsImagePointer & damWeights) [inline]
Definition at line 89 of file animaBaseBlockMatcher.h.
template<typename TInputImageType> void anima::BaseBlockMatcher< TInputImageType >::SetBlockGenerationMask (MaskImageType * image) [inline]
Definition at line 50 of file animaBaseBlockMatcher.h.
template<typename TInputImageType> void anima::BaseBlockMatcher< TInputImageType >::SetBlockPercentageKept (double val) [inline]
Definition at line 61 of file animaBaseBlockMatcher.h.
Referenced by anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::Update(), anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::Update(), anima::PyramidalBlockMatchingBridge< ImageDimension >::Update(), and anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::Update().
template<typename TInputImageType> void anima::BaseBlockMatcher< TInputImageType >::SetBlockPositions (std::vector< PointType > & val) [inline, protected]
Definition at line 135 of file animaBaseBlockMatcher.h.
template<typename TInputImageType> void anima::BaseBlockMatcher< TInputImageType >::SetBlockRegions (std::vector< ImageRegionType > & val) [inline, protected]
Definition at line 134 of file animaBaseBlockMatcher.h.
template<typename TInputImageType> void anima::BaseBlockMatcher< TInputImageType >::SetBlockSize (unsigned int val) [inline]
Definition at line 64 of file animaBaseBlockMatcher.h.
template<typename TInputImageType> void anima::BaseBlockMatcher< TInputImageType >::SetBlockSpacing (unsigned int val) [inline]
Definition at line 67 of file animaBaseBlockMatcher.h.
template<typename TInputImageType> void anima::BaseBlockMatcher< TInputImageType >::SetBlockVarianceThreshold (double val) [inline]
Definition at line 58 of file animaBaseBlockMatcher.h.
template<typename TInputImageType> void anima::BaseBlockMatcher< TInputImageType >::SetBlockWeights (std::vector< double > & val) [inline, protected]
Definition at line 133 of file animaBaseBlockMatcher.h.
template<typename TInputImageType> void anima::BaseBlockMatcher< TInputImageType >::SetDamDistance (double val) [inline]
Definition at line 73 of file animaBaseBlockMatcher.h.
template<typename TInputImageType> void anima::BaseBlockMatcher< TInputImageType >::SetDBlockDamWeights (DamWeightsImagePointer & val) [inline, protected]
Definition at line 136 of file animaBaseBlockMatcher.h.
template<typename TInputImageType> void anima::BaseBlockMatcher< TInputImageType >::SetFinalRadius (double val) [inline]
Definition at line 78 of file animaBaseBlockMatcher.h.
template<typename TInputImageType> void anima::BaseBlockMatcher< TInputImageType >::SetForceComputeBlocks (bool val) [inline]
Definition at line 54 of file animaBaseBlockMatcher.h.
template<typename TInputImageType> void anima::BaseBlockMatcher< TInputImageType >::SetMovingImage (InputImageType * image) [inline]
Definition at line 49 of file animaBaseBlockMatcher.h.
template<typename TInputImageType> void anima::BaseBlockMatcher< TInputImageType >::SetNumberOfThreads (unsigned int val) [inline]
Definition at line 55 of file animaBaseBlockMatcher.h.
Referenced by anima::BaseBlockMatcher< TInputImageType >::Update().
template<typename TInputImageType> void anima::BaseBlockMatcher< TInputImageType >::SetOptimizerMaximumIterations (unsigned int val) [inline]
Definition at line 81 of file animaBaseBlockMatcher.h.
template<typename TInputImageType> void anima::BaseBlockMatcher< TInputImageType >::SetOptimizerType (OptimizerDefinition val) [inline]
Definition at line 96 of file animaBaseBlockMatcher.h.
template<typename TInputImageType> void anima::BaseBlockMatcher< TInputImageType >::SetReferenceImage (InputImageType * image) [inline]
Definition at line 48 of file animaBaseBlockMatcher.h.
template<typename TInputImageType> void anima::BaseBlockMatcher< TInputImageType >::SetSearchRadius (double val) [inline]
Definition at line 76 of file animaBaseBlockMatcher.h.
template<typename TInputImageType> void anima::BaseBlockMatcher< TInputImageType >::SetStepSize (double val) [inline]
Definition at line 79 of file animaBaseBlockMatcher.h.
template<typename TInputImageType> virtual MetricPointer anima::BaseBlockMatcher< TInputImageType >::SetupMetric () [protected, pure virtual]
Implemented in anima::DistortionCorrectionBlockMatcher< TInputImageType >, anima::TensorBlockMatcher< TInputImageType >, and anima::AnatomicalBlockMatcher< TInputImageType >.
template<typename TInputImageType > BaseBlockMatcher< TInputImageType >::OptimizerPointer anima::BaseBlockMatcher< TInputImageType >::SetupOptimizer () [protected, virtual]
Definition at line 82 of file animaBaseBlockMatcher.hxx.
References Bobyqa, and Exhaustive.
template<typename TInputImageType> void anima::BaseBlockMatcher< TInputImageType >::SetUseTransformationDam (bool val) [inline]
Definition at line 70 of file animaBaseBlockMatcher.h.
template<typename TInputImageType> void anima::BaseBlockMatcher< TInputImageType >::SetVerbose (bool value) [inline]
Definition at line 105 of file animaBaseBlockMatcher.h.
template<typename TInputImageType > ITK_THREAD_RETURN_TYPE anima::BaseBlockMatcher< TInputImageType >::ThreadedMatching (void * arg) [static, protected]
Do the matching for a batch of regions (splited according to the thread id + nb threads)
Definition at line 169 of file animaBaseBlockMatcher.hxx.
References anima::BaseBlockMatcher< TInputImageType >::ThreadedMatchData::BlockMatch, and anima::BaseBlockMatcher< TInputImageType >::ProcessBlockMatch().
template<typename TInputImageType> virtual void anima::BaseBlockMatcher< TInputImageType >::TransformDependantOptimizerSetup (OptimizerPointer & optimizer) [protected, pure virtual]
Implemented in anima::DistortionCorrectionBlockMatcher< TInputImageType >, and anima::BaseAffineBlockMatcher< TInputImageType >.
template<typename TInputImageType > void anima::BaseBlockMatcher< TInputImageType >::Update ()
Definition at line 148 of file animaBaseBlockMatcher.hxx.
References anima::BaseBlockMatcher< TInputImageType >::ThreadedMatchData::BlockMatch, and anima::BaseBlockMatcher< TInputImageType >::SetNumberOfThreads().
The documentation for this class was generated from the following files:
animaBaseBlockMatcher.h
animaBaseBlockMatcher.hxx