ANIMA: anima::KissingSymmetricBMRegistrationMethod< TInputImageType > Class Template Reference
anima::KissingSymmetricBMRegistrationMethod< TInputImageType > Class Template Reference
#include <animaKissingSymmetricBMRegistrationMethod.h>
Public Types
typedef
Superclass::AffineTransformType AffineTransformType
typedef Superclass::AgregatorType AgregatorType
typedef
Superclass::BlockMatcherType BlockMatcherType
typedef itk::SmartPointer
< const Self > ConstPointer
typedef Superclass::InputImageType InputImageType
typedef itk::SmartPointer< Self > Pointer
typedef
KissingSymmetricBMRegistrationMethod Self
typedef
BaseBMRegistrationMethod
< TInputImageType > Superclass
typedef
Superclass::SVFTransformType SVFTransformType
typedef
Superclass::TransformPointer TransformPointer
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const char * GetNameOfClass () const
Static Public Member Functions
static Pointer New ()
Protected Member Functions
KissingSymmetricBMRegistrationMethod ()
virtual void PerformOneIteration (InputImageType *refImage, InputImageType *movingImage, TransformPointer &addOn) ITK_OVERRIDE
virtual ~KissingSymmetricBMRegistrationMethod ()
Detailed Description
template<typename TInputImageType>
class anima::KissingSymmetricBMRegistrationMethod< TInputImageType >
Definition at line 8 of file animaKissingSymmetricBMRegistrationMethod.h.
Member Typedef Documentation
template<typename TInputImageType > typedef Superclass::AffineTransformType anima::KissingSymmetricBMRegistrationMethod< TInputImageType >::AffineTransformType
Reimplemented from anima::BaseBMRegistrationMethod< TInputImageType >.
Definition at line 21 of file animaKissingSymmetricBMRegistrationMethod.h.
template<typename TInputImageType > typedef Superclass::AgregatorType anima::KissingSymmetricBMRegistrationMethod< TInputImageType >::AgregatorType
Type of Transform Agregator
Reimplemented from anima::BaseBMRegistrationMethod< TInputImageType >.
Definition at line 20 of file animaKissingSymmetricBMRegistrationMethod.h.
template<typename TInputImageType > typedef Superclass::BlockMatcherType anima::KissingSymmetricBMRegistrationMethod< TInputImageType >::BlockMatcherType
Reimplemented from anima::BaseBMRegistrationMethod< TInputImageType >.
Definition at line 19 of file animaKissingSymmetricBMRegistrationMethod.h.
template<typename TInputImageType > typedef itk::SmartPointer<const Self> anima::KissingSymmetricBMRegistrationMethod< TInputImageType >::ConstPointer
Reimplemented from anima::BaseBMRegistrationMethod< TInputImageType >.
Definition at line 15 of file animaKissingSymmetricBMRegistrationMethod.h.
template<typename TInputImageType > typedef Superclass::InputImageType anima::KissingSymmetricBMRegistrationMethod< TInputImageType >::InputImageType
Reimplemented from anima::BaseBMRegistrationMethod< TInputImageType >.
Definition at line 17 of file animaKissingSymmetricBMRegistrationMethod.h.
template<typename TInputImageType > typedef itk::SmartPointer<Self> anima::KissingSymmetricBMRegistrationMethod< TInputImageType >::Pointer
Reimplemented from anima::BaseBMRegistrationMethod< TInputImageType >.
Definition at line 14 of file animaKissingSymmetricBMRegistrationMethod.h.
template<typename TInputImageType > typedef KissingSymmetricBMRegistrationMethod anima::KissingSymmetricBMRegistrationMethod< TInputImageType >::Self
Standard class typedefs.
Reimplemented from anima::BaseBMRegistrationMethod< TInputImageType >.
Definition at line 12 of file animaKissingSymmetricBMRegistrationMethod.h.
template<typename TInputImageType > typedef BaseBMRegistrationMethod<TInputImageType> anima::KissingSymmetricBMRegistrationMethod< TInputImageType >::Superclass
Reimplemented from anima::BaseBMRegistrationMethod< TInputImageType >.
Definition at line 13 of file animaKissingSymmetricBMRegistrationMethod.h.
template<typename TInputImageType > typedef Superclass::SVFTransformType anima::KissingSymmetricBMRegistrationMethod< TInputImageType >::SVFTransformType
RPI specific types
Reimplemented from anima::BaseBMRegistrationMethod< TInputImageType >.
Definition at line 22 of file animaKissingSymmetricBMRegistrationMethod.h.
template<typename TInputImageType > typedef Superclass::TransformPointer anima::KissingSymmetricBMRegistrationMethod< TInputImageType >::TransformPointer
Reimplemented from anima::BaseBMRegistrationMethod< TInputImageType >.
Definition at line 18 of file animaKissingSymmetricBMRegistrationMethod.h.
Constructor & Destructor Documentation
template<typename TInputImageType > anima::KissingSymmetricBMRegistrationMethod< TInputImageType >::KissingSymmetricBMRegistrationMethod () [inline, protected]
Definition at line 30 of file animaKissingSymmetricBMRegistrationMethod.h.
template<typename TInputImageType > virtual anima::KissingSymmetricBMRegistrationMethod< TInputImageType >::~KissingSymmetricBMRegistrationMethod () [inline, protected, virtual]
Definition at line 31 of file animaKissingSymmetricBMRegistrationMethod.h.
Member Function Documentation
template<typename TInputImageType > virtual::itk::LightObject::Pointer anima::KissingSymmetricBMRegistrationMethod< TInputImageType >::CreateAnother (void) const
template<typename TInputImageType > virtual const char* anima::KissingSymmetricBMRegistrationMethod< TInputImageType >::GetNameOfClass () const [virtual]
Run-time type information (and related methods).
Reimplemented from anima::BaseBMRegistrationMethod< TInputImageType >.
template<typename TInputImageType > static Pointer anima::KissingSymmetricBMRegistrationMethod< TInputImageType >::New () [static]
template<typename TInputImageType > void anima::KissingSymmetricBMRegistrationMethod< TInputImageType >::PerformOneIteration (InputImageType * refImage, InputImageType * movingImage, TransformPointer & addOn) [protected, virtual]
Implements anima::BaseBMRegistrationMethod< TInputImageType >.
Definition at line 16 of file animaKissingSymmetricBMRegistrationMethod.hxx.
References anima::GetExponential(), anima::GetLogarithm(), anima::BalooSVFTransformAgregator< NDimensions >::SetBlockDamWeights(), and anima::DenseSVFTransformAgregator< NDimensions >::SetBlockDamWeights().
The documentation for this class was generated from the following files:
animaKissingSymmetricBMRegistrationMethod.h
animaKissingSymmetricBMRegistrationMethod.hxx