ANIMA: anima::GaussianMCMVariableProjectionCost Class Reference
anima::GaussianMCMVariableProjectionCost Class Reference
Class for computing variable projection costs and derivatives. Right now, it is only available for Gaussian noise. In the future, it could be extended to handle other noise configurations by creating a base class from this one. By the way, this is not thread safe at all so be sure to intantiate one per thread.
#include <animaGaussianMCMVariableProjectionCost.h>
Public Types
typedef itk::SmartPointer
< const Self > ConstPointer
typedef itk::Array2D< double > DerivativeMatrixType
typedef itk::Array< double > DerivativeType
typedef MCMType::ListType ListType
typedef MCMType::Pointer MCMPointer
typedef
anima::MultiCompartmentModel MCMType
typedef itk::Array< double > MeasureType
typedef
itk::OptimizerParameters
< double > ParametersType
typedef itk::SmartPointer< Self > Pointer
typedef
GaussianMCMVariableProjectionCost Self
typedef itk::LightObject Superclass
typedef MCMType::Vector3DType Vector3DType
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
double GetB0Value ()
double GetCurrentCostValue ()
For the current set of parameters, compute the cost function value, requires GetValues to be called first.
void GetCurrentDerivative (DerivativeMatrixType &derivativeMatrix, DerivativeType &derivative)
Get cost function derivatives from a derivative matrix obtained from GetDerivativeMatrix.
void GetDerivativeMatrix (const ParametersType &parameters, DerivativeMatrixType &derivative)
Get residual derivatives for a given set of parameters, returns a matrix of residuals derivatives.
MCMPointer & GetMCMStructure ()
virtual const char * GetNameOfClass () const
unsigned int GetNumberOfObservations () const
unsigned int GetNumberOfParameters () const
Returns number of optimized parameters.
std::vector< double > & GetOptimalWeights ()
double GetSigmaSquare ()
MeasureType GetValues (const ParametersType &parameters)
Get residual values for a given set of parameters, returns a vector of residuals.
void SetBValues (ListType &value)
void SetGradients (std::vector< Vector3DType > &value)
void SetMCMStructure (MCMType *model)
void SetObservedSignals (ListType &value)
void SetUseDerivative (bool derivative)
Static Public Member Functions
static Pointer New ()
Protected Member Functions
bool CheckBoundaryConditions ()
GaussianMCMVariableProjectionCost ()
void PrepareDataForLLS ()
void SolveLinearLeastSquaresOnBorders ()
Computes maximum likelihood estimates of weights and B0 on the borders of the domain (has to be used after SolveMaximumLikelihoodPDE)
void SolveUnconstrainedLinearLeastSquares ()
Computes maximum likelihood estimates of weights and B0.
virtual ~GaussianMCMVariableProjectionCost ()
Detailed Description
Class for computing variable projection costs and derivatives. Right now, it is only available for Gaussian noise. In the future, it could be extended to handle other noise configurations by creating a base class from this one. By the way, this is not thread safe at all so be sure to intantiate one per thread.
Definition at line 21 of file animaGaussianMCMVariableProjectionCost.h.
Member Typedef Documentation
typedef itk::SmartPointer<const Self> anima::GaussianMCMVariableProjectionCost::ConstPointer
Definition at line 28 of file animaGaussianMCMVariableProjectionCost.h.
typedef itk::Array2D<double> anima::GaussianMCMVariableProjectionCost::DerivativeMatrixType
Definition at line 35 of file animaGaussianMCMVariableProjectionCost.h.
typedef itk::Array<double> anima::GaussianMCMVariableProjectionCost::DerivativeType
Definition at line 37 of file animaGaussianMCMVariableProjectionCost.h.
typedef MCMType::ListType anima::GaussianMCMVariableProjectionCost::ListType
Definition at line 43 of file animaGaussianMCMVariableProjectionCost.h.
typedef MCMType::Pointer anima::GaussianMCMVariableProjectionCost::MCMPointer
Definition at line 41 of file animaGaussianMCMVariableProjectionCost.h.
typedef anima::MultiCompartmentModel anima::GaussianMCMVariableProjectionCost::MCMType
Definition at line 40 of file animaGaussianMCMVariableProjectionCost.h.
typedef itk::Array<double> anima::GaussianMCMVariableProjectionCost::MeasureType
Definition at line 36 of file animaGaussianMCMVariableProjectionCost.h.
typedef itk::OptimizerParameters<double> anima::GaussianMCMVariableProjectionCost::ParametersType
Definition at line 38 of file animaGaussianMCMVariableProjectionCost.h.
typedef itk::SmartPointer<Self> anima::GaussianMCMVariableProjectionCost::Pointer
Definition at line 27 of file animaGaussianMCMVariableProjectionCost.h.
typedef GaussianMCMVariableProjectionCost anima::GaussianMCMVariableProjectionCost::Self
Standard class typedefs.
Definition at line 25 of file animaGaussianMCMVariableProjectionCost.h.
typedef itk::LightObject anima::GaussianMCMVariableProjectionCost::Superclass
Definition at line 26 of file animaGaussianMCMVariableProjectionCost.h.
typedef MCMType::Vector3DType anima::GaussianMCMVariableProjectionCost::Vector3DType
Definition at line 42 of file animaGaussianMCMVariableProjectionCost.h.
Constructor & Destructor Documentation
anima::GaussianMCMVariableProjectionCost::GaussianMCMVariableProjectionCost () [inline, protected]
Definition at line 85 of file animaGaussianMCMVariableProjectionCost.h.
virtual anima::GaussianMCMVariableProjectionCost::~GaussianMCMVariableProjectionCost () [inline, protected, virtual]
Definition at line 92 of file animaGaussianMCMVariableProjectionCost.h.
Member Function Documentation
bool anima::GaussianMCMVariableProjectionCost::CheckBoundaryConditions () [protected]
Definition at line 96 of file animaGaussianMCMVariableProjectionCost.cxx.
Referenced by GetValues(), and SolveLinearLeastSquaresOnBorders().
virtual::itk::LightObject::Pointer anima::GaussianMCMVariableProjectionCost::CreateAnother (void) const
double anima::GaussianMCMVariableProjectionCost::GetB0Value () [inline]
Definition at line 78 of file animaGaussianMCMVariableProjectionCost.h.
double anima::GaussianMCMVariableProjectionCost::GetCurrentCostValue ()
For the current set of parameters, compute the cost function value, requires GetValues to be called first.
Definition at line 82 of file animaGaussianMCMVariableProjectionCost.cxx.
Referenced by SolveLinearLeastSquaresOnBorders().
void anima::GaussianMCMVariableProjectionCost::GetCurrentDerivative (DerivativeMatrixType & derivativeMatrix, DerivativeType & derivative)
Get cost function derivatives from a derivative matrix obtained from GetDerivativeMatrix.
Definition at line 611 of file animaGaussianMCMVariableProjectionCost.cxx.
void anima::GaussianMCMVariableProjectionCost::GetDerivativeMatrix (const ParametersType & parameters, DerivativeMatrixType & derivative)
Get residual derivatives for a given set of parameters, returns a matrix of residuals derivatives.
Definition at line 468 of file animaGaussianMCMVariableProjectionCost.cxx.
References GetValues().
MCMPointer& anima::GaussianMCMVariableProjectionCost::GetMCMStructure () [inline]
Definition at line 50 of file animaGaussianMCMVariableProjectionCost.h.
virtual const char* anima::GaussianMCMVariableProjectionCost::GetNameOfClass () const [virtual]
Run-time type information (and related methods).
unsigned int anima::GaussianMCMVariableProjectionCost::GetNumberOfObservations () const [inline]
Definition at line 73 of file animaGaussianMCMVariableProjectionCost.h.
unsigned int anima::GaussianMCMVariableProjectionCost::GetNumberOfParameters () const [inline]
Returns number of optimized parameters.
Definition at line 65 of file animaGaussianMCMVariableProjectionCost.h.
std::vector<double>& anima::GaussianMCMVariableProjectionCost::GetOptimalWeights () [inline]
Definition at line 79 of file animaGaussianMCMVariableProjectionCost.h.
double anima::GaussianMCMVariableProjectionCost::GetSigmaSquare () [inline]
Definition at line 80 of file animaGaussianMCMVariableProjectionCost.h.
GaussianMCMVariableProjectionCost::MeasureType anima::GaussianMCMVariableProjectionCost::GetValues (const ParametersType & parameters)
Get residual values for a given set of parameters, returns a vector of residuals.
Definition at line 12 of file animaGaussianMCMVariableProjectionCost.cxx.
References CheckBoundaryConditions(), PrepareDataForLLS(), SolveLinearLeastSquaresOnBorders(), and SolveUnconstrainedLinearLeastSquares().
Referenced by GetDerivativeMatrix().
static Pointer anima::GaussianMCMVariableProjectionCost::New () [static]
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::CreateCostFunction().
void anima::GaussianMCMVariableProjectionCost::PrepareDataForLLS () [protected]
Definition at line 392 of file animaGaussianMCMVariableProjectionCost.cxx.
Referenced by GetValues().
void anima::GaussianMCMVariableProjectionCost::SetBValues (ListType & value) [inline]
Definition at line 47 of file animaGaussianMCMVariableProjectionCost.h.
void anima::GaussianMCMVariableProjectionCost::SetGradients (std::vector< Vector3DType > & value) [inline]
Definition at line 46 of file animaGaussianMCMVariableProjectionCost.h.
void anima::GaussianMCMVariableProjectionCost::SetMCMStructure (MCMType * model) [inline]
Definition at line 49 of file animaGaussianMCMVariableProjectionCost.h.
void anima::GaussianMCMVariableProjectionCost::SetObservedSignals (ListType & value) [inline]
Definition at line 45 of file animaGaussianMCMVariableProjectionCost.h.
void anima::GaussianMCMVariableProjectionCost::SetUseDerivative (bool derivative) [inline]
Definition at line 82 of file animaGaussianMCMVariableProjectionCost.h.
void anima::GaussianMCMVariableProjectionCost::SolveLinearLeastSquaresOnBorders () [protected]
Computes maximum likelihood estimates of weights and B0 on the borders of the domain (has to be used after SolveMaximumLikelihoodPDE)
Definition at line 115 of file animaGaussianMCMVariableProjectionCost.cxx.
References CheckBoundaryConditions(), GetCurrentCostValue(), and SolveUnconstrainedLinearLeastSquares().
Referenced by GetValues().
void anima::GaussianMCMVariableProjectionCost::SolveUnconstrainedLinearLeastSquares () [protected]
Computes maximum likelihood estimates of weights and B0.
Definition at line 248 of file animaGaussianMCMVariableProjectionCost.cxx.
References anima::GetTensorPower().
Referenced by GetValues(), and SolveLinearLeastSquaresOnBorders().
The documentation for this class was generated from the following files:
animaGaussianMCMVariableProjectionCost.h
animaGaussianMCMVariableProjectionCost.cxx