ANIMA: anima Namespace Reference
anima Namespace Reference
Class performing lesion segmentation.
Namespaces
namespace mcm_utilities
Classes
class AnatomicalBlockMatcher
class AsymmetricBMRegistrationMethod
class AtlasInitializer
class AxisRotationTransform
class BalooSVFTransformAgregator
class BaseAffineBlockMatcher
class BaseBlockMatcher
class BaseBMRegistrationMethod
class BaseCompartment
class BaseIsotropicCompartment
class BaseMCMCostFunction
Base cost function class to handle maximum likelihood estimation with either marginal or profile estimation. Variable projection is too different and handled as a separate structure.
class BaseOrientedModelImageToImageMetric
class BaseProbabilisticTractographyImageFilter
class BaseTractographyImageFilter
class BaseTransformAgregator
class Block
class BlockMatchingInitializer
class BobyqaOptimizer
BOBYQA Optimizer.
class CheckStructureNeighborFilter
Class removing lesions that are not sufficiently in the white matter. Intensity rules may not be enough to discard false positives, therefore we also use localization information. Considering that MS lesions are typically located in WM, we remove the detected ones that do not sufficiently achieve this condition. This filter take two entries: a lesion mask and a white matter map.
class ClassificationStrategy
class ComputeMahalanobisImagesFilter
Compute the mahalanobis images from the NABT model.
class ComputeSolution
Class computing the 3-class GMM respresenting the NABT, where each Gaussian represents one of the brain tissues WM, GM and CSF. First a model initializer is launched, then the REM algorithm is performed using this initialization. The NABT model can be written in a csv file.
class ConcentrationUpperBoundSolverCostFunction
class DBlock
class DenseSVFTransformAgregator
class DirectionScaleSkewTransform
class DirectionScaleTransform
class DirectionTransform
class DistortionCorrectionBlockMatcher
class DistortionCorrectionBMRegistrationMethod
class DistortionCorrectionImageFilter
class DTIEstimationImageFilter
class DTIExtrapolateImageFilter
class DTIProbabilisticTractographyImageFilter
class DTIScalarMapsImageFilter
Applies an variance filter to an image.
class dtiTractographyImageFilter
class EPGSignalSimulator
struct errors_pair_comparator
class ExpTensorImageFilter
class FastCorrelationImageToImageMetric
class FastMeanSquaresImageToImageMetric
class FDRCorrectImageFilter
class FibersWriter
class FreeWaterCompartment
class GaussianEMEstimator
Gaussian Model estimator Class performing expectation-maximation algorithm.
class GaussianMCMCostFunction
class GaussianMCMVariableProjectionCost
Class for computing variable projection costs and derivatives. Right now, it is only available for Gaussian noise. In the future, it could be extended to handle other noise configurations by creating a base class from this one. By the way, this is not thread safe at all so be sure to intantiate one per thread.
class GaussianMCMVariableProjectionMultipleValuedCostFunction
class GaussianMCMVariableProjectionSingleValuedCostFunction
class GaussianNoiseGeneratorImageFilter
class GaussianREMEstimator
Class performing a robust expectation-maximation (REM) algorithm. Allow finding the 3-classes NABT model estimation.
class GcStremMsLesionsSegmentationFilter
class GeneralizedFAImageFilter
class GradientFileReader
class Graph
class Graph3DFilter
Class allowing the decimation of the images if necessary (if 3D graph size causes memory problems). This class just launchs NLinksFilter with appropriate image sizes.
class GraphCutFilter
Class performing grah cut segmentation. First the sources and sinks probabilities maps are computed using the TLinkFilter. Then the Graph3DFilter is called to perform the graph cut.
class HierarchicalInitializer
Class initializing a gaussian mixture with hierarchical information It uses 'a priori' knowledge of the sequences.
class ImageClassifierFilter
Classify each voxels into one of the given GMM classes.
class ImageDataSplitter
class IsotropicRestrictedWaterCompartment
class JacobianMatrixImageFilter
Compute the Jacobian matrix in real coordinates of a displacement field.
class KissingSymmetricBMRegistrationMethod
class KMeansFilter
class LocalPatchCovarianceDistanceImageFilter
class LocalPatchMeanDistanceImageFilter
class LogRigid3DTransform
class LogTensorImageFilter
class LowMemoryLocalPatchCovarianceDistanceBridge
class LowMemoryLocalPatchMeanDistanceBridge
class LowMemoryNLMeansPatientToGroupComparisonBridge
class LowMemoryPatientToGroupComparisonBridge
class LowMemoryPatientToGroupODFComparisonBridge
class LSWTransformAgregator
class LTSWTransformAgregator
class MaskedImageToImageFilter
class MatrixLoggerFilter
Class to compute many log-vectors in a multi-threaded way.
class MCMEstimatorImageFilter
class MCMFileReader
class MCMFileWriter
class MCMImage
class MCMWeightsInequalityConstraintFunction
class MeanAndVarianceImagesFilter
Applies an variance filter to an image.
class MEstimateSVFImageFilter
class MEstTransformAgregator
class ModelInitializer
Gaussian model initializers Model Initializer represents the processes computing a gaussian model that will be used as the model initialization in an EM process.
class MultiCompartmentModel
MultiCompartmentModel: holds several diffusion compartments, ordered by type It also handles weights of the different compartments. Although there are N weights in memory for N compartments, the parameters returned and set are considered to have one less weight in them, the first one being removed. This comes from the fact that they sum up to 1.
class MultiCompartmentModelCreator
Really this class is some simplified factory that creates the MCM that it knows.
class NDHaltonSequenceGenerator
class NewuoaOptimizer
Newuoa Optimizer.
class NLinksFilter
Class creating a 3D graph in a graph cut framework.
class NLMeansPatientToGroupComparisonImageFilter
class NLMeansVectorPatchSearcher
class NLOPTOptimizers
Implements an ITK wrapper for the NLOPT library.
class NLOPTParametersConstraintFunction
class NonCentralChiNoiseGeneratorImageFilter
class NonLocalMeansImageFilter
class NonLocalMeansPatchSearcher
class NonLocalMeansTemporalImageFilter
class NonLocalPatchBaseSearcher
class ODFEstimatorImageFilter
class ODFMaximaCostFunction
class ODFProbabilisticTractographyImageFilter
class ODFResampleImageFilter
class ODFSphericalHarmonicBasis
class OrientedModelBaseResampleImageFilter
struct pair_increasing_comparator
class PatientToGroupComparisonImageFilter
Implements patient to group comparison as in http://dx.doi.org/10.1007/978-3-540-85988-8_116.
class PatientToGroupODFComparisonImageFilter
class PyramidalBlockMatchingBridge
class PyramidalDenseSVFMatchingBridge
class PyramidalDenseTensorSVFMatchingBridge
class PyramidalDistortionCorrectionBlockMatchingBridge
class PyramidalSymmetryBridge
class PyramidalSymmetryConstrainedRegistrationBridge
class PyramidImageFilter
Computes a pyramid of images using the provided resampler to perform resampling.
class RandomInitializer
Class initializing ramdomly a gaussian model.
class RecursiveLineYvvGaussianImageFilter
class RemoveTouchingBorderFilter
Class selecting the connected components touching a given mask border. In MRI, external CSF may contain artifacts due to fluid flow. These effects can cause voxels in the cortex or external CSF to have intensities similar to MS lesions. In order to reduce the number of false positives due to these effects, we remove all candidate lesions that are contiguous to the brain mask border.
class ResampleImageFilter
class SimuBlochCoherentGRE
class SimuBlochGRE
class SimuBlochIRGRE
class SimuBlochIRSE
class SimuBlochSE
class SimuBlochSPGRE
class SmoothingRecursiveYvvGaussianImageFilter
class SphericalHarmonic
class SplitAffine3DTransform
class StationaryWaterCompartment
class StickCompartment
class StimulatedSpinEchoImageFilter
class SVFLieBracketImageFilter
Computes the Lie bracket between two fields u and v as expressed by Bossa et al. [u,v](x) = Jac(u)(x).v(x) - Jac(v)(x).u(x) M. Bossa et al. "Contributions to 3D diffeomorphic atlas estimation : application to brain images.", MICCAI 2007, p. 667–674.
class SymmetricBMRegistrationMethod
class SymmetryPlaneTransform
class T1RelaxometryEstimationImageFilter
class T2EPGRelaxometryCostFunction
class T2EPGRelaxometryEstimationImageFilter
class T2RelaxometryEstimationImageFilter
class TensorBlockMatcher
class TensorCompartment
class TensorCorrelationImageToImageMetric
class TensorGeneralizedCorrelationImageToImageMetric
class TensorMeanSquaresImageToImageMetric
class TensorResampleImageFilter
class TLinksFilter
Class computing the probability maps that are used to create the t-links.
class TransformSeriesReader
class VectorModelLinearInterpolateImageFunction
class VoxelExhaustiveOptimizer
class ZeppelinCompartment
Enumerations
enum DiffusionModelCompartmentType {
FreeWater = 0,
StationaryWater,
IsotropicRestrictedWater,
Stick,
Zeppelin,
Tensor,
DDI
}
Functions
double a0r_support (double x, unsigned int N)
Support function for besserl_ratio_i.
double ak_support (double x, unsigned int N, unsigned int k)
Support function for besserl_ratio_i.
double bessel_i_lower_bound (unsigned int N, double x)
Computes a lower bound of the modified Bessel function of the first kind: I_{N} (N >= 0)
double bessel_ratio_i (double x, unsigned int N, unsigned int approx_order=10)
Computes the ratio of modified Bessel functions of the first kind: I_{N} / I_{N-1} (N >= 1)
double bessel_ratio_i_lower_bound (double x, unsigned int N)
Computes a lower bound of the ratio of modified Bessel functions of the first kind: I_{N} / I_{N-1} (N >= 1)
void BHCorrection (std::vector< double > &pvalues, double qValue)
void BYCorrection (std::vector< double > &pvalues, double qValue)
template<class ScalarType , unsigned int NDimensions>
void composeDistortionCorrections (typename rpi::DisplacementFieldTransform< ScalarType, NDimensions >::Pointer &baseTrsf, typename rpi::DisplacementFieldTransform< ScalarType, NDimensions >::Pointer &positiveAddOn, typename rpi::DisplacementFieldTransform< ScalarType, NDimensions >::Pointer &negativeAddOn, unsigned int numThreads)
template<class ScalarType , unsigned int NDimensions>
void composeSVF (itk::StationaryVelocityFieldTransform< ScalarType, NDimensions > *baseTrsf, itk::StationaryVelocityFieldTransform< ScalarType, NDimensions > *addonTrsf, unsigned int numThreads, unsigned int bchOrder)
template<class TInput , class TScalarType , unsigned int NDimensions>
void computeAffineLSWFromTranslations (std::vector< itk::Point< TInput, NDimensions > > &inputOrigins, std::vector< itk::Point< TInput, NDimensions > > &inputTransformed, std::vector< TInput > &weights, typename itk::AffineTransform< TScalarType, NDimensions >::Pointer &resultTransform)
template<class VectorType >
double ComputeAngle (const VectorType &v1, const VectorType &v2)
template<class T1 , class T2 , unsigned int Dimension>
void computeAverageLocalCovariance (vnl_matrix< T2 > &resVariance, itk::VectorImage< T1, Dimension > *inputImage, itk::Image< unsigned char, Dimension > *maskImage, const itk::ImageRegion< Dimension > &averagingRegion, int localNeighborhood)
Noise estimation for a patch of a vector image.
template<class VectorType >
void ComputeCrossProduct (const VectorType &v1, const VectorType &v2, const unsigned int NDimension, VectorType &resVec)
template<class ScalarType , unsigned int NDimension>
void ComputeCrossProduct (const itk::Vector< ScalarType, NDimension > &v1, const itk::Vector< ScalarType, NDimension > &v2, itk::Vector< ScalarType, NDimension > &resVec)
template<class ScalarType >
void ComputeCrossProduct (const itk::VariableLengthVector< ScalarType > &v1, const itk::VariableLengthVector< ScalarType > &v2, itk::VariableLengthVector< ScalarType > &resVec)
template<class ScalarType , unsigned int NDimension>
void ComputeCrossProduct (const itk::Point< ScalarType, NDimension > &v1, const itk::Point< ScalarType, NDimension > &v2, itk::Point< ScalarType, NDimension > &resVec)
template<class ScalarType >
void ComputeCrossProduct (const vnl_vector< ScalarType > &v1, const vnl_vector< ScalarType > &v2, vnl_vector< ScalarType > &resVec)
template<class ScalarType , unsigned int NDimension>
void ComputeCrossProduct (const vnl_vector_fixed< ScalarType, NDimension > &v1, const vnl_vector_fixed< ScalarType, NDimension > &v2, vnl_vector_fixed< ScalarType, NDimension > &resVec)
template<class ScalarType >
void ComputeCrossProduct (const std::vector< ScalarType > &v1, const std::vector< ScalarType > &v2, std::vector< ScalarType > &resVec)
template<class VectorType >
double ComputeDirectedHausdorffDistance (const std::vector< VectorType > &s1, const std::vector< VectorType > &s2)
template<class VectorType >
double ComputeEuclideanDistance (const VectorType &x1, const VectorType &x2, const unsigned int NDimension)
template<class ScalarType , unsigned int NDimension>
double ComputeEuclideanDistance (const itk::Vector< ScalarType, NDimension > &x1, const itk::Vector< ScalarType, NDimension > &x2)
template<class ScalarType >
double ComputeEuclideanDistance (const itk::VariableLengthVector< ScalarType > &x1, const itk::VariableLengthVector< ScalarType > &x2)
template<class ScalarType , unsigned int NDimension>
double ComputeEuclideanDistance (const itk::Point< ScalarType, NDimension > &x1, const itk::Point< ScalarType, NDimension > &x2)
template<class ScalarType >
double ComputeEuclideanDistance (const vnl_vector< ScalarType > &x1, const vnl_vector< ScalarType > &x2)
template<class ScalarType , unsigned int NDimension>
double ComputeEuclideanDistance (const vnl_vector_fixed< ScalarType, NDimension > &x1, const vnl_vector_fixed< ScalarType, NDimension > &x2)
template<class ScalarType >
double ComputeEuclideanDistance (const std::vector< ScalarType > &x1, const std::vector< ScalarType > &x2)
template<class VectorType >
double ComputeHausdorffDistance (const std::vector< VectorType > &s1, const std::vector< VectorType > &s2)
template<class TInput , class TScalarType , unsigned int NDimensions>
void computeLogEuclideanAverage (std::vector< vnl_matrix< TInput > > &inputTransforms, std::vector< TInput > &weights, typename itk::AffineTransform< TScalarType, NDimensions >::Pointer &resultTransform)
template<class VectorType >
double ComputeModifiedDirectedHausdorffDistance (const std::vector< VectorType > &s1, const std::vector< VectorType > &s2)
template<class VectorType >
double ComputeModifiedHausdorffDistance (const std::vector< VectorType > &s1, const std::vector< VectorType > &s2)
template<class VectorType >
double ComputeNorm (const VectorType &v)
template<class VectorType >
double ComputeOrientationAngle (const VectorType &v1, const VectorType &v2)
template<class T1 , class T2 , unsigned int Dimension>
unsigned int computePatchMeanAndCovariance (const itk::VectorImage< T1, Dimension > *inputImage, const itk::ImageRegion< Dimension > &patchRegion, itk::VariableLengthVector< T2 > &patchMean, vnl_matrix< T2 > &patchCov)
Computes the average and covariance matrix from a patch of a vector image.
template<class VectorType >
double ComputePointToSetDistance (const VectorType &x, const std::vector< VectorType > &s)
template<class TInput , class TScalarType , unsigned int NDimensions>
void computeRigidLSWFromTranslations (std::vector< itk::Point< TInput, NDimensions > > &inputOrigins, std::vector< itk::Point< TInput, NDimensions > > &inputTransformed, std::vector< TInput > &weights, typename itk::AffineTransform< TScalarType, NDimensions >::Pointer &resultTransform)
template<class TInput , class TOutput >
vnl_matrix< TOutput > computeRotationFromQuaternion (vnl_vector< TInput > eigenVector)
template<class VectorType >
double ComputeScalarProduct (const VectorType &v1, const VectorType &v2, const unsigned int NDimension)
template<class ScalarType , unsigned int NDimension>
double ComputeScalarProduct (const itk::Vector< ScalarType, NDimension > &v1, const itk::Vector< ScalarType, NDimension > &v2)
template<class ScalarType >
double ComputeScalarProduct (const itk::VariableLengthVector< ScalarType > &v1, const itk::VariableLengthVector< ScalarType > &v2)
template<class ScalarType , unsigned int NDimension>
double ComputeScalarProduct (const itk::Point< ScalarType, NDimension > &v1, const itk::Point< ScalarType, NDimension > &v2)
template<class ScalarType >
double ComputeScalarProduct (const vnl_vector< ScalarType > &v1, const vnl_vector< ScalarType > &v2)
template<class ScalarType , unsigned int NDimension>
double ComputeScalarProduct (const vnl_vector_fixed< ScalarType, NDimension > &v1, const vnl_vector_fixed< ScalarType, NDimension > &v2)
template<class ScalarType >
double ComputeScalarProduct (const std::vector< ScalarType > &v1, const std::vector< ScalarType > &v2)
template<class TInput , class TScalarType , unsigned int NDimensions>
void computeTranslationLSWFromTranslations (std::vector< itk::Point< TInput, NDimensions > > &inputOrigins, std::vector< itk::Point< TInput, NDimensions > > &inputTransformed, std::vector< TInput > &weights, typename itk::AffineTransform< TScalarType, NDimensions >::Pointer &resultTransform)
template<class VectorType , class ScalarType >
double ComputeVMFPdf (const VectorType &v, const VectorType &meanDirection, const ScalarType &kappa)
template<class T >
T Cubic (T x0, T x1, T x2, T x3, T y0, T y1, T y2, T y3, T x)
template<class T >
void CubicInterpolator (std::vector< T > &transfVect, std::vector< T > &scale, std::vector< T > &outputVect, T LengthLine)
void EstimateLocalODFRotationMatrix (vnl_matrix< double > &resVal, unsigned int l, double alpha, double beta, double gamma)
double EvaluateDawsonFunction (double x)
compute Dawson(x) = sqrt(pi)/2 * exp(-x^2) * erfi(x)
double EvaluateDawsonFunctionNR (double x)
Numerical recipes implementation of Dawson integral.
template<class VectorType , class ScalarType >
double EvaluateWatsonPDF (const VectorType &v, const VectorType &meanAxis, const ScalarType &kappa)
template<class ScalarType >
double EvaluateWatsonPDF (const vnl_vector_fixed< ScalarType, 3 > &v, const vnl_vector_fixed< ScalarType, 3 > &meanAxis, const ScalarType &kappa)
template<class ScalarType >
double EvaluateWatsonPDF (const itk::Point< ScalarType, 3 > &v, const itk::Point< ScalarType, 3 > &meanAxis, const ScalarType &kappa)
template<class ScalarType >
double EvaluateWatsonPDF (const itk::Vector< ScalarType, 3 > &v, const itk::Vector< ScalarType, 3 > &meanAxis, const ScalarType &kappa)
double EvaluateWImFunction (double x)
double EvaluateWImY100Function (double y100, double x)
template<class VectorType >
double ExponentialSum (const VectorType &x, const unsigned int NDimension)
template<class ScalarType , unsigned int NDimension>
double ExponentialSum (const itk::Vector< ScalarType, NDimension > &x)
template<class ScalarType >
double ExponentialSum (const itk::VariableLengthVector< ScalarType > &x)
template<class ScalarType , unsigned int NDimension>
double ExponentialSum (const itk::Point< ScalarType, NDimension > &x)
template<class ScalarType >
double ExponentialSum (const vnl_vector< ScalarType > &x)
template<class ScalarType , unsigned int NDimension>
double ExponentialSum (const vnl_vector_fixed< ScalarType, NDimension > &x)
template<class ScalarType >
double ExponentialSum (const std::vector< ScalarType > &x)
template<typename RealType , typename MatrixType >
void ExtractPPDRotationFromJacobianMatrix (vnl_matrix< RealType > &jacobianMatrix, vnl_matrix< RealType > &rotationMatrix, MatrixType &eigenVectors)
template<typename RealType >
void ExtractRotationFromJacobianMatrix (vnl_matrix< RealType > &jacobianMatrix, vnl_matrix< RealType > &rotationMatrix, vnl_matrix< RealType > &tmpMat)
template<class ScalarType , unsigned int NDimensions, unsigned int NDegreesOfFreedom>
void filterInputs (itk::Image< ScalarType, NDimensions > *weights, typename itk::Image< itk::Vector< ScalarType, NDegreesOfFreedom >, NDimensions >::Pointer &output, std::vector< itk::Vector< ScalarType, NDegreesOfFreedom > > &curTrsfs, std::vector< typename itk::Image< itk::Vector< ScalarType, NDegreesOfFreedom >, NDimensions >::IndexType > &posIndexes, BalooSVFTransformAgregator< NDimensions > *filterPtr)
double gammaHalfMinusN (unsigned int n)
double gammaHalfPlusN (unsigned int n)
double GetDValue (unsigned int l, int m, int mp, double angle)
void GetEulerAnglesFromRotationMatrix (vnl_matrix< double > &R, std::vector< double > &resVal)
template<class T >
vnl_matrix< T > GetExponential (const vnl_matrix< T > &m, const int numApprox=1)
Computation of the matrix exponential. Algo: classical scaling and squaring, as in Matlab. See Higham, SIAM Matr. Anal., 2004.
template<class InputImageType , class OutputImageType >
std::vector< itk::SmartPointer
< OutputImageType > > getImagesFromHigherDimensionImage (InputImageType *inputImage)
Get a vector of input images from a higher dimensional image.
template<class T >
vnl_matrix< T > GetLogarithm (const vnl_matrix< T > &m, const double precision=0.00000000001, const int numApprox=1)
Computation of the matrix logarithm. Algo: inverse scaling and squaring, variant proposed by Cheng et al., SIAM Matrix Anal., 2001.
itk::ImageIOBase::IOComponentType
ANIMAMCM_EXPORT GetMCMComponentType (std::string fileName)
template<class T >
vnl_matrix< T > GetPadeLogarithm (const vnl_matrix< double > &m, const int numApprox)
Final part of the computation of the log. Estimates the log with a Pade approximation for a matrix m such that \|m-Id\| <= 0.5.
template<class T >
vnl_matrix< T > GetPadeLogarithm (const vnl_matrix< T > &m, const int numApprox)
template<class VectorType >
itk::Matrix< double, 3, 3 > GetRotationMatrixFromVectors (const VectorType &first_direction, const VectorType &second_direction, const unsigned int dimension)
template<class ScalarType >
itk::Matrix< double, 3, 3 > GetRotationMatrixFromVectors (const itk::Point< ScalarType > &first_direction, const itk::Point< ScalarType > &second_direction)
template<class ScalarType , unsigned int NDimension>
itk::Matrix< double, 3, 3 > GetRotationMatrixFromVectors (const itk::Vector< ScalarType, NDimension > &first_direction, const itk::Vector< ScalarType, NDimension > &second_direction)
template<class ScalarType , unsigned int NDimension>
itk::Matrix< double, 3, 3 > GetRotationMatrixFromVectors (const vnl_vector_fixed< ScalarType, NDimension > &first_direction, const vnl_vector_fixed< ScalarType, NDimension > &second_direction)
template<class T >
vnl_matrix< T > GetSquareRoot (const vnl_matrix< T > &m, const double precision, vnl_matrix< T > &resultM)
Gets the square root of matrix m.
template<class ScalarType , unsigned int NDimensions>
void GetSVFExponential (itk::StationaryVelocityFieldTransform< ScalarType, NDimensions > *baseTrsf, rpi::DisplacementFieldTransform< ScalarType, NDimensions > *resultTransform, bool invert)
template<class T >
void GetTensorExponential (const vnl_matrix< T > &log_tensor, vnl_matrix< T > &tensor)
template<class T1 , class T2 >
void GetTensorFromVectorRepresentation (const itk::VariableLengthVector< T1 > &vector, vnl_matrix< T2 > &tensor, unsigned int tensDim=0, bool scale=false)
template<class T >
void GetTensorLogarithm (const vnl_matrix< T > &tensor, vnl_matrix< T > &log_tensor)
template<class T >
void GetTensorPower (const vnl_matrix< T > &tensor, vnl_matrix< T > &outputTensor, double powerValue)
template<class T1 , class T2 >
void GetVectorRepresentation (const vnl_matrix< T1 > &tensor, itk::VariableLengthVector< T2 > &vector, unsigned int vecDim=0, bool scale=false)
std::vector< std::vector
< double > > InitializeSampleDirections (unsigned int nbTheta, unsigned int nbPhi, std::string sampleDirFileName)
template<class T >
void InverseCubicInterpolator (std::vector< T > &inputVect, std::vector< T > &outputVect, T step)
template<class T >
double jfour (const T &k)
template<class T >
double jtwo (const T &k)
double legendre_first_derivative (int L, int M, double value)
double legendre_second_derivative (int L, int M, double value)
double log_bessel_i (unsigned int N, double x)
Computes the log of modified Bessel function of the first kind: I_{N} (N >= 0)
double log_bessel_i_lower_bound (unsigned int N, double x)
Computes a lower bound of the log of modified Bessel function of the first kind: I_{N} (N >= 0)
double log_bessel_order_derivative_i (double x, unsigned int order, double emc, unsigned int approx_order=50)
Computes the derivative of the log of modified Bessel function of the first kind w.r.t. its order (emc is the Euler-Mascheroni constant)
template<class VectorType >
void Normalize (const VectorType &v, const unsigned int NDimension, VectorType &resVec)
template<class ScalarType , unsigned int NDimension>
void Normalize (const itk::Vector< ScalarType, NDimension > &v, itk::Vector< ScalarType, NDimension > &resVec)
template<class ScalarType >
void Normalize (const itk::VariableLengthVector< ScalarType > &v, itk::VariableLengthVector< ScalarType > &resVec)
template<class ScalarType , unsigned int NDimension>
void Normalize (const itk::Point< ScalarType, NDimension > &v, itk::Point< ScalarType, NDimension > &resVec)
template<class ScalarType >
void Normalize (const vnl_vector< ScalarType > &v, vnl_vector< ScalarType > &resVec)
template<class ScalarType , unsigned int NDimension>
void Normalize (const vnl_vector_fixed< ScalarType, NDimension > &v, vnl_vector_fixed< ScalarType, NDimension > &resVec)
template<class ScalarType >
void Normalize (const std::vector< ScalarType > &v, std::vector< ScalarType > &resVec)
template<class T1 >
double ovlScore (vnl_diag_matrix< T1 > &eigsX, vnl_matrix< T1 > &eigVecsX, vnl_diag_matrix< T1 > &eigsY, vnl_matrix< T1 > &eigVecsY)
template<class TInput , class TOutput , unsigned int NDimensions>
void pairingToQuaternion (const vnl_vector_fixed< TInput, NDimensions > &inputPoint, const vnl_vector_fixed< TInput, NDimensions > &inputTransformedPoint, vnl_matrix< TOutput > &outputMatrix)
template<class TInput , class TOutput , unsigned int NDimensions>
void pairingToQuaternion (const itk::Vector< TInput, NDimensions > &inputPoint, const itk::Vector< TInput, NDimensions > &inputTransformedPoint, vnl_matrix< TOutput > &outputMatrix)
template<class PointType , class TOutput >
void pairingToQuaternion (const PointType &inputPoint, const PointType &inputTransformedPoint, vnl_matrix< TOutput > &outputMatrix, unsigned int ndim)
template<class T1 , class T2 , class T3 >
void ProjectOnOrthogonalPlane (const std::vector< T1 > &v, const std::vector< T2 > &normalVec, std::vector< T3 > &resVec)
template<class T >
void ProjectOnTensorSpace (const vnl_matrix< T > &matrix, vnl_matrix< T > &tensor)
double psi_function (unsigned int n, double emc)
template<class ImageType >
itk::SmartPointer< ImageType > readImage (std::string filename)
template<class T1 , class T2 >
void RecomposeTensor (vnl_diag_matrix< T1 > &eigs, vnl_matrix< T1 > &eigVecs, vnl_matrix< T2 > &resMatrix)
Recompose tensor from values extracted using SymmetricEigenAnalysis (vnl_symmetric_eigensystem transposes all this)
template<class ImageType >
itk::SmartPointer< ImageType > reorient3DImage (typename itk::SmartPointer< ImageType > input, itk::SpatialOrientation::ValidCoordinateOrientationFlags orientation)
template<class ImageType >
itk::SmartPointer< ImageType > reorientImage (typename itk::SmartPointer< ImageType > input, itk::SpatialOrientation::ValidCoordinateOrientationFlags orientation)
template<class ImageType , class GradientType >
itk::SmartPointer< ImageType > reorientImageAndGradient (typename itk::SmartPointer< ImageType > input, itk::SpatialOrientation::ValidCoordinateOrientationFlags orientation, std::vector< GradientType > &gradients)
template<class VectorType >
void Revert (const VectorType &v, const unsigned int vSize, VectorType &resVec)
template<class ScalarType >
void Revert (const std::vector< ScalarType > &v, std::vector< ScalarType > &resVec)
template<class ScalarType >
void Revert (const itk::Point< ScalarType > &v, itk::Point< ScalarType > &resVec)
template<class ScalarType , unsigned int NDimension>
void Revert (const vnl_vector_fixed< ScalarType, NDimension > &v, vnl_vector_fixed< ScalarType, NDimension > &resVec)
template<class T1 , class T2 , class T3 , class T4 >
void RotateAroundAxis (const std::vector< T1 > &v, const T2 &phi, const std::vector< T3 > &normalVec, std::vector< T4 > &resVec)
template<class Vector3DType , class ScalarType >
void RotateAroundAxis (const Vector3DType &v, const ScalarType &phi, const Vector3DType &normalVec, Vector3DType &resVec)
template<class T1 , class T2 , class T3 >
void RotateSymmetricMatrix (T1 &tensor, T2 &rotationMatrix, T3 &rotated_tensor, unsigned int tensorDim)
template<class T1 , class T2 >
void RotateSymmetricMatrix (vnl_matrix< T1 > &tensor, vnl_matrix< T2 > &rotationMatrix, vnl_matrix< T2 > &rotated_tensor)
template<class T1 , class T2 , unsigned int NDim>
void RotateSymmetricMatrix (itk::Matrix< T1, NDim, NDim > &tensor, itk::Matrix< T2, NDim, NDim > &rotationMatrix, itk::Matrix< T2, NDim, NDim > &rotated_tensor)
template<class ScalarType >
double safe_log (const ScalarType x)
template<class T >
unsigned int SampleFromBernoulliDistribution (const T &p, std::mt19937 &generator)
template<class T >
double SampleFromGaussianDistribution (const T &mean, const T &std, std::mt19937 &generator)
template<class VectorType , class ScalarType >
void SampleFromMultivariateGaussianDistribution (const VectorType &mean, const vnl_matrix< ScalarType > &mat, VectorType &resVec, std::mt19937 &generator, bool isMatCovariance=true)
template<class T >
double SampleFromUniformDistribution (const T &a, const T &b, std::mt19937 &generator)
template<class VectorType >
void SampleFromUniformDistributionOn2Sphere (std::mt19937 &generator, VectorType &resVec)
template<class VectorType , class ScalarType >
void SampleFromVMFDistribution (const ScalarType &kappa, const VectorType &meanDirection, VectorType &resVec, std::mt19937 &generator)
template<class VectorType , class ScalarType >
void SampleFromVMFDistributionNumericallyStable (const ScalarType &kappa, const VectorType &meanDirection, VectorType &resVec, std::mt19937 &generator)
template<class ScalarType , class VectorType >
void SampleFromWatsonDistribution (const ScalarType &kappa, const VectorType &meanDirection, VectorType &resVec, unsigned int DataDimension, std::mt19937 &generator)
template<class ScalarType , unsigned int DataDimension>
void SampleFromWatsonDistribution (const ScalarType &kappa, const vnl_vector_fixed< ScalarType, DataDimension > &meanDirection, vnl_vector_fixed< ScalarType, DataDimension > &resVec, std::mt19937 &generator)
template<class ScalarType , unsigned int DataDimension>
void SampleFromWatsonDistribution (const ScalarType &kappa, const itk::Point< ScalarType, DataDimension > &meanDirection, itk::Point< ScalarType, DataDimension > &resVec, std::mt19937 &generator)
template<class ScalarType , unsigned int DataDimension>
void SampleFromWatsonDistribution (const ScalarType &kappa, const itk::Vector< ScalarType, DataDimension > &meanDirection, itk::Vector< ScalarType, DataDimension > &resVec, std::mt19937 &generator)
template<class InputImageType , class ImageFilterType >
unsigned int setMultipleImageFilterInputsFromFileName (std::string &fileName, ImageFilterType *filter)
Set inputs of an image to image filter from a file name containing either a list of files or a higher dimensional image.
template<class T >
double ShOverId (const T &x)
template<class T1 , class T2 , class T3 >
double ShRatio (const T1 &k, const T2 &alpha, const T3 &beta)
template<class T >
double SinOverId (const T &x)
template<class VectorType >
void TransformCartesianToSphericalCoordinates (const VectorType &v, VectorType &resVec)
template<class VectorType >
void TransformSphericalToCartesianCoordinates (const VectorType &v, VectorType &resVec)
template<class VectorType >
void TransformSphericalToCartesianCoordinates (double theta, double phi, double vectorNorm, VectorType &resVec)
template<class T >
double VectorCovarianceTest (vnl_matrix< T > &logRefPatchCov, vnl_matrix< T > &movingPatchCov)
Test if covariance matrices are different (returns distance)
template<class T >
double VectorMeansTest (itk::VariableLengthVector< T > &refPatchMean, itk::VariableLengthVector< T > &movingPatchMean, const unsigned int &refPatchNumElts, const unsigned int &movingPatchNumElts, vnl_matrix< T > &refPatchCov, vnl_matrix< T > &movingPatchCov)
Test if vector means are different (returns distance)
template<class ScalarType , unsigned int Dimension>
double VMFDistance (const itk::Point< ScalarType, Dimension > &muFirst, const double &kappaFirst, const itk::Point< ScalarType, Dimension > &muSec, const double &kappaSec)
template<class OutputImageType >
void writeImage (std::string filename, OutputImageType *img)
template<class T >
double xi (const T &k)
Variables
const double zeroWeight = 0
Detailed Description
Class performing lesion segmentation.
The segmentation method has three steps:
1) Estimation of the NABT model: The NABT model computation requires strictly 3 sequences: T1-w and two sequences among T2-w, DP and FLAIR.
2) Detection of candidate lesions: The lesion detection can be done two different ways:
applying a simple threshold after computing the mahalanobis distances on each one of the healthy tissues. (LesionSegmentationType == strem)
applying a graph cut segmentation. (LesionSegmentationType == gcem) The automatic graph cut segmentation requires a sources and a sink probabilities maps that are computed from the mahalanobis images. The sources map is computed using also fuzzy weights between 0 and 1, based on T2-w, DP and FLAIR hyper-intensities. Additionally, binary sources and sinks masks can be added as entries of the graph cut.(LesionSegmentationType == gcemAndManualGC) Their information will be mixed with the automatic sources and sinks probabilities map. This option simulates the lesion segmentation correction done by a user that adds/removes seeds for the graph cut computation.
The last segmentation type option (LesionSegmentationType == manualGC) just uses manual binary sources and sinks masks as entries of the graph cut. This option does not perform the estimation of the NABT model.
3) Application of a priori heuristic rules to extract the MS lesions from others outliers: The heuritic rules that can be used to refine the segmentation are:
the size rule to remove small lesions
the border rule to remove lesions touching the border of the brain mask if the NABT model has being computed, the following rules can be applied:
hyper-intensity rule to remove voxels that are not hyper-intense comparing to the white matter in T2, DP and FLAIR sequence.
white matter neighbor rule to remove lesions that are not in white matter.
Additionally to the lesions segmentation, the filter provides a segmentation of the healthy tissues based on the NABT estimation.
Enumeration Type Documentation
enum anima::DiffusionModelCompartmentType
Enumerator:
FreeWater
StationaryWater
IsotropicRestrictedWater
Stick
Zeppelin
Tensor
DDI
Definition at line 16 of file animaBaseCompartment.h.
Function Documentation
ANIMASPECIALFUNCTIONS_EXPORT double anima::a0r_support (double x, unsigned int N)
Support function for besserl_ratio_i.
Definition at line 135 of file animaBesselFunctions.cxx.
Referenced by bessel_ratio_i().
ANIMASPECIALFUNCTIONS_EXPORT double anima::ak_support (double x, unsigned int N, unsigned int k)
Support function for besserl_ratio_i.
Definition at line 140 of file animaBesselFunctions.cxx.
Referenced by bessel_ratio_i().
ANIMASPECIALFUNCTIONS_EXPORT double anima::bessel_i_lower_bound (unsigned int N, double x)
Computes a lower bound of the modified Bessel function of the first kind: I_{N} (N >= 0)
Definition at line 50 of file animaBesselFunctions.cxx.
ANIMASPECIALFUNCTIONS_EXPORT double anima::bessel_ratio_i (double x, unsigned int N, unsigned int approx_order)
Computes the ratio of modified Bessel functions of the first kind: I_{N} / I_{N-1} (N >= 1)
Definition at line 76 of file animaBesselFunctions.cxx.
References a0r_support(), and ak_support().
Referenced by log_bessel_i().
ANIMASPECIALFUNCTIONS_EXPORT double anima::bessel_ratio_i_lower_bound (double x, unsigned int N)
Computes a lower bound of the ratio of modified Bessel functions of the first kind: I_{N} / I_{N-1} (N >= 1)
Definition at line 103 of file animaBesselFunctions.cxx.
ANIMASTATISTICALTESTS_EXPORT void anima::BHCorrection (std::vector< double > & pvalues, double qValue)
In place correction of p-values according to Benjamini Hochberg FDR method Output is a thresholded list at the specified q-value Eq. (1) of Y. Benjamini and Y. Hochberg. Controlling the False Discovery Rate: A Practical and Powerful Approach to Multiple Testing. Journal of the Royal Statistical Society. Series B (Methodological) Vol. 57, No. 1 (1995), pp. 289-300
Definition at line 8 of file animaFDRCorrection.cxx.
Referenced by anima::FDRCorrectImageFilter< PixelScalarType >::GenerateData().
ANIMASTATISTICALTESTS_EXPORT void anima::BYCorrection (std::vector< double > & pvalues, double qValue)
Definition at line 33 of file animaFDRCorrection.cxx.
Referenced by anima::FDRCorrectImageFilter< PixelScalarType >::GenerateData().
template<class ScalarType , unsigned int NDimensions> void anima::composeDistortionCorrections (typename rpi::DisplacementFieldTransform< ScalarType, NDimensions >::Pointer & baseTrsf, typename rpi::DisplacementFieldTransform< ScalarType, NDimensions >::Pointer & positiveAddOn, typename rpi::DisplacementFieldTransform< ScalarType, NDimensions >::Pointer & negativeAddOn, unsigned int numThreads)
Compose distortion correction opposite updates, ensures opposite symmetry baseTrsf is replaced by the result !
Definition at line 261 of file animaVelocityUtils.hxx.
template<class ScalarType , unsigned int NDimensions> void anima::composeSVF (itk::StationaryVelocityFieldTransform< ScalarType, NDimensions > * baseTrsf, itk::StationaryVelocityFieldTransform< ScalarType, NDimensions > * addonTrsf, unsigned int numThreads, unsigned int bchOrder)
Performs BCH approximation to composition of exp(baseTrsf) and exp(addonTrsf). As explained in M. Bossa et al. "Contributions to 3D diffeomorphic atlas estimation : application to brain images.", MICCAI 2007, p. 667–674.
Definition at line 14 of file animaVelocityUtils.hxx.
Referenced by anima::BaseBMRegistrationMethod< TInputImageType >::ComposeAddOnWithTransform().
template<class TInput , class TScalarType , unsigned int NDimensions> void anima::computeAffineLSWFromTranslations (std::vector< itk::Point< TInput, NDimensions > > & inputOrigins, std::vector< itk::Point< TInput, NDimensions > > & inputTransformed, std::vector< TInput > & weights, typename itk::AffineTransform< TScalarType, NDimensions >::Pointer & resultTransform)
Definition at line 165 of file animaLinearTransformEstimationTools.hxx.
template<class VectorType > double anima::ComputeAngle (const VectorType & v1, const VectorType & v2)
Definition at line 373 of file animaVectorOperations.hxx.
References ComputeNorm(), and ComputeScalarProduct().
template<class T1 , class T2 , unsigned int Dimension> void anima::computeAverageLocalCovariance (vnl_matrix< T2 > & resVariance, itk::VectorImage< T1, Dimension > * inputImage, itk::Image< unsigned char, Dimension > * maskImage, const itk::ImageRegion< Dimension > & averagingRegion, int localNeighborhood)
Noise estimation for a patch of a vector image.
Definition at line 65 of file animaVectorImagePatchStatistics.hxx.
Referenced by anima::NLMeansVectorPatchSearcher< ImageScalarType, DataImageType >::ComputeInputProperties().
template<class VectorType > void anima::ComputeCrossProduct (const VectorType & v1, const VectorType & v2, const unsigned int NDimension, VectorType & resVec)
Definition at line 254 of file animaVectorOperations.hxx.
Referenced by ComputeCrossProduct(), and SampleFromWatsonDistribution().
template<class ScalarType , unsigned int NDimension> void anima::ComputeCrossProduct (const itk::Vector< ScalarType, NDimension > & v1, const itk::Vector< ScalarType, NDimension > & v2, itk::Vector< ScalarType, NDimension > & resVec)
Definition at line 264 of file animaVectorOperations.hxx.
References ComputeCrossProduct().
template<class ScalarType > void anima::ComputeCrossProduct (const itk::VariableLengthVector< ScalarType > & v1, const itk::VariableLengthVector< ScalarType > & v2, itk::VariableLengthVector< ScalarType > & resVec)
Definition at line 269 of file animaVectorOperations.hxx.
References ComputeCrossProduct().
template<class ScalarType , unsigned int NDimension> void anima::ComputeCrossProduct (const itk::Point< ScalarType, NDimension > & v1, const itk::Point< ScalarType, NDimension > & v2, itk::Point< ScalarType, NDimension > & resVec)
Definition at line 280 of file animaVectorOperations.hxx.
References ComputeCrossProduct().
template<class ScalarType > void anima::ComputeCrossProduct (const vnl_vector< ScalarType > & v1, const vnl_vector< ScalarType > & v2, vnl_vector< ScalarType > & resVec)
Definition at line 285 of file animaVectorOperations.hxx.
References ComputeCrossProduct().
template<class ScalarType , unsigned int NDimension> void anima::ComputeCrossProduct (const vnl_vector_fixed< ScalarType, NDimension > & v1, const vnl_vector_fixed< ScalarType, NDimension > & v2, vnl_vector_fixed< ScalarType, NDimension > & resVec)
Definition at line 296 of file animaVectorOperations.hxx.
References ComputeCrossProduct().
template<class ScalarType > void anima::ComputeCrossProduct (const std::vector< ScalarType > & v1, const std::vector< ScalarType > & v2, std::vector< ScalarType > & resVec)
Definition at line 301 of file animaVectorOperations.hxx.
References ComputeCrossProduct().
template<class VectorType > double anima::ComputeDirectedHausdorffDistance (const std::vector< VectorType > & s1, const std::vector< VectorType > & s2)
Definition at line 92 of file animaVectorOperations.hxx.
References ComputePointToSetDistance().
Referenced by ComputeHausdorffDistance().
template<class VectorType > double anima::ComputeEuclideanDistance (const VectorType & x1, const VectorType & x2, const unsigned int NDimension)
Definition at line 14 of file animaVectorOperations.hxx.
Referenced by ComputeEuclideanDistance(), ComputePointToSetDistance(), and anima::BaseProbabilisticTractographyImageFilter::UpdateClassesMemberships().
template<class ScalarType , unsigned int NDimension> double anima::ComputeEuclideanDistance (const itk::Vector< ScalarType, NDimension > & x1, const itk::Vector< ScalarType, NDimension > & x2)
Definition at line 26 of file animaVectorOperations.hxx.
References ComputeEuclideanDistance().
template<class ScalarType > double anima::ComputeEuclideanDistance (const itk::VariableLengthVector< ScalarType > & x1, const itk::VariableLengthVector< ScalarType > & x2)
Definition at line 31 of file animaVectorOperations.hxx.
References ComputeEuclideanDistance().
template<class ScalarType , unsigned int NDimension> double anima::ComputeEuclideanDistance (const itk::Point< ScalarType, NDimension > & x1, const itk::Point< ScalarType, NDimension > & x2)
Definition at line 41 of file animaVectorOperations.hxx.
References ComputeEuclideanDistance().
template<class ScalarType > double anima::ComputeEuclideanDistance (const vnl_vector< ScalarType > & x1, const vnl_vector< ScalarType > & x2)
Definition at line 46 of file animaVectorOperations.hxx.
References ComputeEuclideanDistance().
template<class ScalarType , unsigned int NDimension> double anima::ComputeEuclideanDistance (const vnl_vector_fixed< ScalarType, NDimension > & x1, const vnl_vector_fixed< ScalarType, NDimension > & x2)
Definition at line 57 of file animaVectorOperations.hxx.
References ComputeEuclideanDistance().
template<class ScalarType > double anima::ComputeEuclideanDistance (const std::vector< ScalarType > & x1, const std::vector< ScalarType > & x2)
Definition at line 62 of file animaVectorOperations.hxx.
References ComputeEuclideanDistance().
template<class VectorType > double anima::ComputeHausdorffDistance (const std::vector< VectorType > & s1, const std::vector< VectorType > & s2)
Definition at line 110 of file animaVectorOperations.hxx.
References ComputeDirectedHausdorffDistance().
template<class TInput , class TScalarType , unsigned int NDimensions> void anima::computeLogEuclideanAverage (std::vector< vnl_matrix< TInput > > & inputTransforms, std::vector< TInput > & weights, typename itk::AffineTransform< TScalarType, NDimensions >::Pointer & resultTransform)
Definition at line 130 of file animaLinearTransformEstimationTools.hxx.
References GetExponential().
template<class VectorType > double anima::ComputeModifiedDirectedHausdorffDistance (const std::vector< VectorType > & s1, const std::vector< VectorType > & s2)
Definition at line 119 of file animaVectorOperations.hxx.
References ComputePointToSetDistance().
Referenced by ComputeModifiedHausdorffDistance(), and anima::BaseProbabilisticTractographyImageFilter::UpdateClassesMemberships().
template<class VectorType > double anima::ComputeModifiedHausdorffDistance (const std::vector< VectorType > & s1, const std::vector< VectorType > & s2)
Definition at line 132 of file animaVectorOperations.hxx.
References ComputeModifiedDirectedHausdorffDistance().
template<class VectorType > double anima::ComputeNorm (const VectorType & v)
Definition at line 314 of file animaVectorOperations.hxx.
References ComputeScalarProduct().
Referenced by ComputeAngle(), anima::ODFProbabilisticTractographyImageFilter::ComputeLogWeightUpdate(), anima::ODFProbabilisticTractographyImageFilter::ComputeModelEstimation(), ComputeOrientationAngle(), ComputeVMFPdf(), Normalize(), anima::ODFProbabilisticTractographyImageFilter::PrepareTractography(), SampleFromWatsonDistribution(), TransformCartesianToSphericalCoordinates(), and anima::GradientFileReader< GradientType, BValueScalarType >::Update().
template<class VectorType > double anima::ComputeOrientationAngle (const VectorType & v1, const VectorType & v2)
Definition at line 388 of file animaVectorOperations.hxx.
References ComputeNorm(), and ComputeScalarProduct().
Referenced by anima::BaseTractographyImageFilter::ComputeFiber(), and anima::ODFProbabilisticTractographyImageFilter::FindODFMaxima().
template<class T1 , class T2 , unsigned int Dimension> unsigned int anima::computePatchMeanAndCovariance (const itk::VectorImage< T1, Dimension > * inputImage, const itk::ImageRegion< Dimension > & patchRegion, itk::VariableLengthVector< T2 > & patchMean, vnl_matrix< T2 > & patchCov)
Computes the average and covariance matrix from a patch of a vector image.
Definition at line 11 of file animaVectorImagePatchStatistics.hxx.
Referenced by anima::NLMeansVectorPatchSearcher< ImageScalarType, DataImageType >::ComputeComparisonProperties(), anima::NLMeansVectorPatchSearcher< ImageScalarType, DataImageType >::ComputeInputProperties(), anima::LocalPatchCovarianceDistanceImageFilter< PixelScalarType >::ThreadedGenerateData(), and anima::LocalPatchMeanDistanceImageFilter< PixelScalarType >::ThreadedGenerateData().
template<class VectorType > double anima::ComputePointToSetDistance (const VectorType & x, const std::vector< VectorType > & s)
Definition at line 74 of file animaVectorOperations.hxx.
References ComputeEuclideanDistance().
Referenced by ComputeDirectedHausdorffDistance(), ComputeModifiedDirectedHausdorffDistance(), and anima::BaseProbabilisticTractographyImageFilter::UpdateClassesMemberships().
template<class TInput , class TScalarType , unsigned int NDimensions> void anima::computeRigidLSWFromTranslations (std::vector< itk::Point< TInput, NDimensions > > & inputOrigins, std::vector< itk::Point< TInput, NDimensions > > & inputTransformed, std::vector< TInput > & weights, typename itk::AffineTransform< TScalarType, NDimensions >::Pointer & resultTransform)
Definition at line 62 of file animaLinearTransformEstimationTools.hxx.
References pairingToQuaternion().
template<class TInput , class TOutput > vnl_matrix< TOutput > anima::computeRotationFromQuaternion (vnl_vector< TInput > eigenVector)
Definition at line 230 of file animaLinearTransformEstimationTools.hxx.
template<class VectorType > double anima::ComputeScalarProduct (const VectorType & v1, const VectorType & v2, const unsigned int NDimension)
Definition at line 196 of file animaVectorOperations.hxx.
Referenced by ComputeAngle(), anima::BaseTractographyImageFilter::ComputeFiber(), anima::DTIProbabilisticTractographyImageFilter::ComputeLogWeightUpdate(), ComputeNorm(), ComputeOrientationAngle(), ComputeScalarProduct(), ComputeVMFPdf(), EvaluateWatsonPDF(), anima::StickCompartment::GetLogDiffusionProfile(), anima::ZeppelinCompartment::GetLogDiffusionProfile(), anima::dtiTractographyImageFilter::GetNextDirection(), anima::TensorCompartment::GetSignalAttenuationJacobian(), anima::ODFProbabilisticTractographyImageFilter::InitializeFirstIterationFromModel(), anima::DTIProbabilisticTractographyImageFilter::InitializeFirstIterationFromModel(), anima::BaseCompartment::IsEqual(), ProjectOnOrthogonalPlane(), anima::ODFProbabilisticTractographyImageFilter::ProposeNewDirection(), and anima::DTIProbabilisticTractographyImageFilter::ProposeNewDirection().
template<class ScalarType , unsigned int NDimension> double anima::ComputeScalarProduct (const itk::Vector< ScalarType, NDimension > & v1, const itk::Vector< ScalarType, NDimension > & v2)
Definition at line 206 of file animaVectorOperations.hxx.
References ComputeScalarProduct().
template<class ScalarType > double anima::ComputeScalarProduct (const itk::VariableLengthVector< ScalarType > & v1, const itk::VariableLengthVector< ScalarType > & v2)
Definition at line 211 of file animaVectorOperations.hxx.
References ComputeScalarProduct().
template<class ScalarType , unsigned int NDimension> double anima::ComputeScalarProduct (const itk::Point< ScalarType, NDimension > & v1, const itk::Point< ScalarType, NDimension > & v2)
Definition at line 221 of file animaVectorOperations.hxx.
References ComputeScalarProduct().
template<class ScalarType > double anima::ComputeScalarProduct (const vnl_vector< ScalarType > & v1, const vnl_vector< ScalarType > & v2)
Definition at line 226 of file animaVectorOperations.hxx.
References ComputeScalarProduct().
template<class ScalarType , unsigned int NDimension> double anima::ComputeScalarProduct (const vnl_vector_fixed< ScalarType, NDimension > & v1, const vnl_vector_fixed< ScalarType, NDimension > & v2)
Definition at line 236 of file animaVectorOperations.hxx.
References ComputeScalarProduct().
template<class ScalarType > double anima::ComputeScalarProduct (const std::vector< ScalarType > & v1, const std::vector< ScalarType > & v2)
Definition at line 241 of file animaVectorOperations.hxx.
References ComputeScalarProduct().
template<class TInput , class TScalarType , unsigned int NDimensions> void anima::computeTranslationLSWFromTranslations (std::vector< itk::Point< TInput, NDimensions > > & inputOrigins, std::vector< itk::Point< TInput, NDimensions > > & inputTransformed, std::vector< TInput > & weights, typename itk::AffineTransform< TScalarType, NDimensions >::Pointer & resultTransform)
Definition at line 16 of file animaLinearTransformEstimationTools.hxx.
template<class VectorType , class ScalarType > double anima::ComputeVMFPdf (const VectorType & v, const VectorType & meanDirection, const ScalarType & kappa)
Definition at line 15 of file animaVMFDistribution.hxx.
References ComputeNorm(), and ComputeScalarProduct().
template<class T > T anima::Cubic (T x0, T x1, T x2, T x3, T y0, T y1, T y2, T y3, T x)
Definition at line 9 of file animaCubicInterpolation.hxx.
Referenced by InverseCubicInterpolator().
template<class T > void anima::CubicInterpolator (std::vector< T > & transfVect, std::vector< T > & scale, std::vector< T > & outputVect, T LengthLine)
Definition at line 81 of file animaCubicInterpolation.hxx.
ANIMASHTOOLS_EXPORT void anima::EstimateLocalODFRotationMatrix (vnl_matrix< double > & resVal, unsigned int l, double alpha, double beta, double gamma)
Definition at line 152 of file animaODFFunctions.cxx.
References GetDValue().
Referenced by anima::ODFResampleImageFilter< TImageType, TInterpolatorPrecisionType >::ReorientInterpolatedModel().
ANIMASPECIALFUNCTIONS_EXPORT double anima::EvaluateDawsonFunction (double x)
compute Dawson(x) = sqrt(pi)/2 * exp(-x^2) * erfi(x)
Definition at line 48 of file animaErrorFunctions.cxx.
References EvaluateWImFunction().
ANIMASPECIALFUNCTIONS_EXPORT double anima::EvaluateDawsonFunctionNR (double x)
Numerical recipes implementation of Dawson integral.
Definition at line 11 of file animaErrorFunctions.cxx.
Referenced by EvaluateWatsonPDF().
template<class VectorType , class ScalarType > double anima::EvaluateWatsonPDF (const VectorType & v, const VectorType & meanAxis, const ScalarType & kappa)
Definition at line 15 of file animaWatsonDistribution.hxx.
References ComputeScalarProduct(), and EvaluateDawsonFunctionNR().
Referenced by anima::ODFProbabilisticTractographyImageFilter::ProposeNewDirection(), and anima::DTIProbabilisticTractographyImageFilter::ProposeNewDirection().
template<class ScalarType > double anima::EvaluateWatsonPDF (const vnl_vector_fixed< ScalarType, 3 > & v, const vnl_vector_fixed< ScalarType, 3 > & meanAxis, const ScalarType & kappa)
Definition at line 54 of file animaWatsonDistribution.hxx.
template<class ScalarType > double anima::EvaluateWatsonPDF (const itk::Point< ScalarType, 3 > & v, const itk::Point< ScalarType, 3 > & meanAxis, const ScalarType & kappa)
Definition at line 63 of file animaWatsonDistribution.hxx.
template<class ScalarType > double anima::EvaluateWatsonPDF (const itk::Vector< ScalarType, 3 > & v, const itk::Vector< ScalarType, 3 > & meanAxis, const ScalarType & kappa)
Definition at line 72 of file animaWatsonDistribution.hxx.
ANIMASPECIALFUNCTIONS_EXPORT double anima::EvaluateWImFunction (double x)
Definition at line 54 of file animaErrorFunctions.cxx.
References EvaluateWImY100Function().
Referenced by EvaluateDawsonFunction().
ANIMASPECIALFUNCTIONS_EXPORT double anima::EvaluateWImY100Function (double y100, double x)
Definition at line 87 of file animaErrorFunctions.cxx.
Referenced by EvaluateWImFunction().
template<class VectorType > double anima::ExponentialSum (const VectorType & x, const unsigned int NDimension)
Definition at line 142 of file animaVectorOperations.hxx.
Referenced by anima::BaseProbabilisticTractographyImageFilter::ComputeFiber(), and ExponentialSum().
template<class ScalarType , unsigned int NDimension> double anima::ExponentialSum (const itk::Vector< ScalarType, NDimension > & x)
Definition at line 160 of file animaVectorOperations.hxx.
References ExponentialSum().
template<class ScalarType > double anima::ExponentialSum (const itk::VariableLengthVector< ScalarType > & x)
Definition at line 165 of file animaVectorOperations.hxx.
References ExponentialSum().
template<class ScalarType , unsigned int NDimension> double anima::ExponentialSum (const itk::Point< ScalarType, NDimension > & x)
Definition at line 171 of file animaVectorOperations.hxx.
References ExponentialSum().
template<class ScalarType > double anima::ExponentialSum (const vnl_vector< ScalarType > & x)
Definition at line 176 of file animaVectorOperations.hxx.
References ExponentialSum().
template<class ScalarType , unsigned int NDimension> double anima::ExponentialSum (const vnl_vector_fixed< ScalarType, NDimension > & x)
Definition at line 182 of file animaVectorOperations.hxx.
References ExponentialSum().
template<class ScalarType > double anima::ExponentialSum (const std::vector< ScalarType > & x)
Definition at line 187 of file animaVectorOperations.hxx.
References ExponentialSum().
template<typename RealType , typename MatrixType > void anima::ExtractPPDRotationFromJacobianMatrix (vnl_matrix< RealType > & jacobianMatrix, vnl_matrix< RealType > & rotationMatrix, MatrixType & eigenVectors)
Definition at line 182 of file animaBaseTensorTools.hxx.
References GetRotationMatrixFromVectors(), and Normalize().
Referenced by anima::TensorMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::GetValue(), anima::TensorCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::GetValue(), anima::TensorGeneralizedCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::GetValue(), anima::TensorCompartment::Reorient(), and anima::TensorResampleImageFilter< TImageType, TInterpolatorPrecisionType >::ReorientInterpolatedModel().
template<typename RealType > void anima::ExtractRotationFromJacobianMatrix (vnl_matrix< RealType > & jacobianMatrix, vnl_matrix< RealType > & rotationMatrix, vnl_matrix< RealType > & tmpMat)
Definition at line 149 of file animaBaseTensorTools.hxx.
References RecomposeTensor().
Referenced by anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::ComputeRotationParametersFromReorientationMatrix(), and anima::BaseOrientedModelImageToImageMetric< TFixedImage, TMovingImage >::SetTransformParameters().
template<class ScalarType , unsigned int NDimensions, unsigned int NDegreesOfFreedom> void anima::filterInputs (itk::Image< ScalarType, NDimensions > * weights, typename itk::Image< itk::Vector< ScalarType, NDegreesOfFreedom >, NDimensions >::Pointer & output, std::vector< itk::Vector< ScalarType, NDegreesOfFreedom > > & curTrsfs, std::vector< typename itk::Image< itk::Vector< ScalarType, NDegreesOfFreedom >, NDimensions >::IndexType > & posIndexes, BalooSVFTransformAgregator< NDimensions > * filterPtr)
Definition at line 400 of file animaBalooSVFTransformAgregator.hxx.
References anima::BalooSVFTransformAgregator< NDimensions >::GetBlockDamWeights(), anima::BalooSVFTransformAgregator< NDimensions >::GetExtrapolationSigma(), anima::BaseTransformAgregator< NDimensions >::GetInputRegions(), anima::BalooSVFTransformAgregator< NDimensions >::GetNumberOfThreads(), anima::BalooSVFTransformAgregator< NDimensions >::GetOutlierRejectionSigma(), and zeroWeight.
ANIMASPECIALFUNCTIONS_EXPORT double anima::gammaHalfMinusN (unsigned int n)
Definition at line 33 of file animaGammaFunctions.cxx.
ANIMASPECIALFUNCTIONS_EXPORT double anima::gammaHalfPlusN (unsigned int n)
Definition at line 23 of file animaGammaFunctions.cxx.
ANIMASHTOOLS_EXPORT double anima::GetDValue (unsigned int l, int m, int mp, double angle)
Definition at line 97 of file animaODFFunctions.cxx.
Referenced by EstimateLocalODFRotationMatrix().
ANIMASHTOOLS_EXPORT void anima::GetEulerAnglesFromRotationMatrix (vnl_matrix< double > & R, std::vector< double > & resVal)
Definition at line 72 of file animaODFFunctions.cxx.
Referenced by anima::ODFResampleImageFilter< TImageType, TInterpolatorPrecisionType >::ReorientInterpolatedModel().
template<class T > vnl_matrix< T > anima::GetExponential (const vnl_matrix< T > & m, const int numApprox = 1)
Computation of the matrix exponential. Algo: classical scaling and squaring, as in Matlab. See Higham, SIAM Matr. Anal., 2004.
Definition at line 197 of file animaMatrixLogExp.hxx.
Referenced by computeLogEuclideanAverage(), anima::LogRigid3DTransform< TScalarType >::ComputeMatrix(), anima::DirectionScaleSkewTransform< TScalarType >::ComputeMatrix(), main(), anima::KissingSymmetricBMRegistrationMethod< TInputImageType >::PerformOneIteration(), and anima::SymmetricBMRegistrationMethod< TInputImageType >::PerformOneIteration().
template<class InputImageType , class OutputImageType > std::vector< itk::SmartPointer <OutputImageType> > anima::getImagesFromHigherDimensionImage (InputImageType * inputImage)
Get a vector of input images from a higher dimensional image.
Definition at line 42 of file animaReadWriteFunctions.h.
template<class T > vnl_matrix< T > anima::GetLogarithm (const vnl_matrix< T > & m, const double precision = 0.00000000001, const int numApprox = 1)
Computation of the matrix logarithm. Algo: inverse scaling and squaring, variant proposed by Cheng et al., SIAM Matrix Anal., 2001.
Definition at line 144 of file animaMatrixLogExp.hxx.
References GetPadeLogarithm(), and GetSquareRoot().
Referenced by anima::MatrixLoggerFilter< TInputScalarType, TOutputScalarType, NDimensions, NDegreesOfFreedom >::InternalLogger(), main(), anima::KissingSymmetricBMRegistrationMethod< TInputImageType >::PerformOneIteration(), and anima::SymmetricBMRegistrationMethod< TInputImageType >::PerformOneIteration().
itk::ImageIOBase::IOComponentType ANIMAMCMBASE_EXPORT anima::GetMCMComponentType (std::string fileName)
Definition at line 8 of file animaMCMFileReader.cxx.
template<class T > vnl_matrix<T> anima::GetPadeLogarithm (const vnl_matrix< double > & m, const int numApprox)
Final part of the computation of the log. Estimates the log with a Pade approximation for a matrix m such that \|m-Id\| <= 0.5.
Referenced by GetLogarithm().
template<class T > vnl_matrix<T> anima::GetPadeLogarithm (const vnl_matrix< T > & m, const int numApprox)
Definition at line 64 of file animaMatrixLogExp.hxx.
template<class VectorType > itk::Matrix< double, 3, 3 > anima::GetRotationMatrixFromVectors (const VectorType & first_direction, const VectorType & second_direction, const unsigned int dimension)
Definition at line 13 of file animaMatrixOperations.hxx.
References pairingToQuaternion().
Referenced by anima::ODFProbabilisticTractographyImageFilter::ComputeLogWeightUpdate(), ExtractPPDRotationFromJacobianMatrix(), GetRotationMatrixFromVectors(), SampleFromVMFDistribution(), SampleFromVMFDistributionNumericallyStable(), anima::AxisRotationTransform< TScalarType >::SetReferencePlaneNormal(), and anima::PyramidalSymmetryConstrainedRegistrationBridge< ScalarType >::SetupPyramids().
template<class ScalarType > itk::Matrix< double, 3, 3 > anima::GetRotationMatrixFromVectors (const itk::Point< ScalarType > & first_direction, const itk::Point< ScalarType > & second_direction)
Definition at line 54 of file animaMatrixOperations.hxx.
References GetRotationMatrixFromVectors().
template<class ScalarType , unsigned int NDimension> itk::Matrix< double, 3, 3 > anima::GetRotationMatrixFromVectors (const itk::Vector< ScalarType, NDimension > & first_direction, const itk::Vector< ScalarType, NDimension > & second_direction)
Definition at line 62 of file animaMatrixOperations.hxx.
References GetRotationMatrixFromVectors().
template<class ScalarType , unsigned int NDimension> itk::Matrix< double, 3, 3 > anima::GetRotationMatrixFromVectors (const vnl_vector_fixed< ScalarType, NDimension > & first_direction, const vnl_vector_fixed< ScalarType, NDimension > & second_direction)
Definition at line 69 of file animaMatrixOperations.hxx.
References GetRotationMatrixFromVectors().
template<class T > vnl_matrix< T > anima::GetSquareRoot (const vnl_matrix< T > & m, const double precision, vnl_matrix< T > & resultM)
Gets the square root of matrix m.
Definition at line 12 of file animaMatrixLogExp.hxx.
Referenced by GetLogarithm().
template<class ScalarType , unsigned int NDimensions> void anima::GetSVFExponential (itk::StationaryVelocityFieldTransform< ScalarType, NDimensions > * baseTrsf, rpi::DisplacementFieldTransform< ScalarType, NDimensions > * resultTransform, bool invert)
Definition at line 242 of file animaVelocityUtils.hxx.
Referenced by anima::TransformSeriesReader< TScalarType, NDimensions >::addSVFTransformation(), anima::DistortionCorrectionBMRegistrationMethod< TInputImageType >::ComposeAddOnWithTransform(), anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::GetOutputDisplacementFieldTransform(), main(), anima::BaseBMRegistrationMethod< TInputImageType >::ResampleImages(), anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::Update(), and anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::Update().
template<class T > void anima::GetTensorExponential (const vnl_matrix< T > & log_tensor, vnl_matrix< T > & tensor)
Definition at line 56 of file animaBaseTensorTools.hxx.
References RecomposeTensor().
Referenced by anima::dtiTractographyImageFilter::ComputeAdditionalScalarMaps(), anima::DTIExtrapolateImageFilter< PixelScalarType >::ThreadedGenerateData(), and anima::ExpTensorImageFilter< TScalarType, NDimensions >::ThreadedGenerateData().
template<class T1 , class T2 > void anima::GetTensorFromVectorRepresentation (const itk::VariableLengthVector< T1 > & vector, vnl_matrix< T2 > & tensor, unsigned int tensDim = 0, bool scale = false)
Definition at line 99 of file animaBaseTensorTools.hxx.
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::BeforeThreadedGenerateData(), anima::dtiTractographyImageFilter::ComputeAdditionalScalarMaps(), anima::dtiTractographyImageFilter::GetNextDirection(), anima::TensorMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::GetValue(), anima::TensorCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::GetValue(), anima::TensorGeneralizedCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::GetValue(), anima::TensorResampleImageFilter< TImageType, TInterpolatorPrecisionType >::ReorientInterpolatedModel(), anima::TensorCompartment::SetCompartmentVector(), anima::DTIExtrapolateImageFilter< PixelScalarType >::ThreadedGenerateData(), anima::ExpTensorImageFilter< TScalarType, NDimensions >::ThreadedGenerateData(), anima::LogTensorImageFilter< TScalarType, NDimensions >::ThreadedGenerateData(), anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::ThreadedGenerateData(), and anima::DTIScalarMapsImageFilter< ImageDimension >::ThreadedGenerateData().
template<class T > void anima::GetTensorLogarithm (const vnl_matrix< T > & tensor, vnl_matrix< T > & log_tensor)
Definition at line 13 of file animaBaseTensorTools.hxx.
References RecomposeTensor().
Referenced by anima::DTIExtrapolateImageFilter< PixelScalarType >::ThreadedGenerateData(), and anima::LogTensorImageFilter< TScalarType, NDimensions >::ThreadedGenerateData().
template<class T > void anima::GetTensorPower (const vnl_matrix< T > & tensor, vnl_matrix< T > & outputTensor, double powerValue)
Definition at line 37 of file animaBaseTensorTools.hxx.
References RecomposeTensor().
Referenced by anima::TensorCompartment::SetCompartmentVector(), anima::GaussianMCMVariableProjectionCost::SolveUnconstrainedLinearLeastSquares(), and anima::TensorCompartment::UpdateDiffusionTensor().
template<class T1 , class T2 > void anima::GetVectorRepresentation (const vnl_matrix< T1 > & tensor, itk::VariableLengthVector< T2 > & vector, unsigned int vecDim = 0, bool scale = false)
Definition at line 75 of file animaBaseTensorTools.hxx.
Referenced by anima::dtiTractographyImageFilter::ComputeAdditionalScalarMaps(), anima::TensorCompartment::GetCompartmentVector(), anima::TensorMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::GetValue(), anima::TensorGeneralizedCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::GetValue(), anima::TensorCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::GetValue(), anima::TensorCompartment::Reorient(), anima::TensorResampleImageFilter< TImageType, TInterpolatorPrecisionType >::ReorientInterpolatedModel(), anima::DTIExtrapolateImageFilter< PixelScalarType >::ThreadedGenerateData(), anima::LogTensorImageFilter< TScalarType, NDimensions >::ThreadedGenerateData(), anima::ExpTensorImageFilter< TScalarType, NDimensions >::ThreadedGenerateData(), and anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::ThreadedGenerateData().
ANIMASHTOOLS_EXPORT std::vector< std::vector< double > > anima::InitializeSampleDirections (unsigned int nbTheta, unsigned int nbPhi, std::string sampleDirFileName)
Definition at line 15 of file animaODFFunctions.cxx.
References TransformCartesianToSphericalCoordinates().
Referenced by main().
template<class T > void anima::InverseCubicInterpolator (std::vector< T > & inputVect, std::vector< T > & outputVect, T step)
Definition at line 30 of file animaCubicInterpolation.hxx.
References Cubic().
Referenced by anima::DistortionCorrectionImageFilter< TInputImage >::ThreadedGenerateData().
template<class T > double anima::jfour (const T & k)
Definition at line 53 of file animaHyperbolicFunctions.hxx.
template<class T > double anima::jtwo (const T & k)
Definition at line 41 of file animaHyperbolicFunctions.hxx.
ANIMASPECIALFUNCTIONS_EXPORT double anima::legendre_first_derivative (int L, int M, double value)
Definition at line 9 of file animaLegendreDerivatives.cxx.
Referenced by anima::SphericalHarmonic::getThetaFirstDerivative(), anima::SphericalHarmonic::getThetaPhiDerivative(), and anima::SphericalHarmonic::getThetaSecondDerivative().
ANIMASPECIALFUNCTIONS_EXPORT double anima::legendre_second_derivative (int L, int M, double value)
Definition at line 45 of file animaLegendreDerivatives.cxx.
Referenced by anima::SphericalHarmonic::getThetaSecondDerivative().
ANIMASPECIALFUNCTIONS_EXPORT double anima::log_bessel_i (unsigned int N, double x)
Computes the log of modified Bessel function of the first kind: I_{N} (N >= 0)
Definition at line 12 of file animaBesselFunctions.cxx.
References bessel_ratio_i().
ANIMASPECIALFUNCTIONS_EXPORT double anima::log_bessel_i_lower_bound (unsigned int N, double x)
Computes a lower bound of the log of modified Bessel function of the first kind: I_{N} (N >= 0)
Definition at line 63 of file animaBesselFunctions.cxx.
ANIMASPECIALFUNCTIONS_EXPORT double anima::log_bessel_order_derivative_i (double x, unsigned int order, double emc, unsigned int approx_order)
Computes the derivative of the log of modified Bessel function of the first kind w.r.t. its order (emc is the Euler-Mascheroni constant)
Definition at line 110 of file animaBesselFunctions.cxx.
References psi_function().
template<class VectorType > void anima::Normalize (const VectorType & v, const unsigned int NDimension, VectorType & resVec)
Definition at line 326 of file animaVectorOperations.hxx.
References ComputeNorm().
Referenced by ExtractPPDRotationFromJacobianMatrix(), anima::dtiTractographyImageFilter::GetNextDirection(), Normalize(), ProjectOnOrthogonalPlane(), SampleFromWatsonDistribution(), TransformCartesianToSphericalCoordinates(), and anima::GradientFileReader< GradientType, BValueScalarType >::Update().
template<class ScalarType , unsigned int NDimension> void anima::Normalize (const itk::Vector< ScalarType, NDimension > & v, itk::Vector< ScalarType, NDimension > & resVec)
Definition at line 339 of file animaVectorOperations.hxx.
References Normalize().
template<class ScalarType > void anima::Normalize (const itk::VariableLengthVector< ScalarType > & v, itk::VariableLengthVector< ScalarType > & resVec)
Definition at line 344 of file animaVectorOperations.hxx.
References Normalize().
template<class ScalarType , unsigned int NDimension> void anima::Normalize (const itk::Point< ScalarType, NDimension > & v, itk::Point< ScalarType, NDimension > & resVec)
Definition at line 350 of file animaVectorOperations.hxx.
References Normalize().
template<class ScalarType > void anima::Normalize (const vnl_vector< ScalarType > & v, vnl_vector< ScalarType > & resVec)
Definition at line 355 of file animaVectorOperations.hxx.
References Normalize().
template<class ScalarType , unsigned int NDimension> void anima::Normalize (const vnl_vector_fixed< ScalarType, NDimension > & v, vnl_vector_fixed< ScalarType, NDimension > & resVec)
Definition at line 361 of file animaVectorOperations.hxx.
References Normalize().
template<class ScalarType > void anima::Normalize (const std::vector< ScalarType > & v, std::vector< ScalarType > & resVec)
Definition at line 366 of file animaVectorOperations.hxx.
References Normalize().
template<class T1 > double anima::ovlScore (vnl_diag_matrix< T1 > & eigsX, vnl_matrix< T1 > & eigVecsX, vnl_diag_matrix< T1 > & eigsY, vnl_matrix< T1 > & eigVecsY)
Definition at line 299 of file animaBaseTensorTools.hxx.
Referenced by anima::TensorGeneralizedCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::GetValue().
template<class TInput , class TOutput , unsigned int NDimensions> void anima::pairingToQuaternion (const vnl_vector_fixed< TInput, NDimensions > & inputPoint, const vnl_vector_fixed< TInput, NDimensions > & inputTransformedPoint, vnl_matrix< TOutput > & outputMatrix)
Definition at line 255 of file animaLinearTransformEstimationTools.hxx.
Referenced by computeRigidLSWFromTranslations(), GetRotationMatrixFromVectors(), and pairingToQuaternion().
template<class TInput , class TOutput , unsigned int NDimensions> void anima::pairingToQuaternion (const itk::Vector< TInput, NDimensions > & inputPoint, const itk::Vector< TInput, NDimensions > & inputTransformedPoint, vnl_matrix< TOutput > & outputMatrix)
Definition at line 262 of file animaLinearTransformEstimationTools.hxx.
References pairingToQuaternion().
template<class PointType , class TOutput > void anima::pairingToQuaternion (const PointType & inputPoint, const PointType & inputTransformedPoint, vnl_matrix< TOutput > & outputMatrix, unsigned int ndim)
Definition at line 269 of file animaLinearTransformEstimationTools.hxx.
template<class T1 , class T2 , class T3 > void anima::ProjectOnOrthogonalPlane (const std::vector< T1 > & v, const std::vector< T2 > & normalVec, std::vector< T3 > & resVec)
Definition at line 479 of file animaVectorOperations.hxx.
References ComputeScalarProduct(), and Normalize().
template<class T > void anima::ProjectOnTensorSpace (const vnl_matrix< T > & matrix, vnl_matrix< T > & tensor)
Definition at line 127 of file animaBaseTensorTools.hxx.
References RecomposeTensor().
Referenced by anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::ThreadedGenerateData().
ANIMASPECIALFUNCTIONS_EXPORT double anima::psi_function (unsigned int n, double emc)
Definition at line 11 of file animaGammaFunctions.cxx.
Referenced by log_bessel_order_derivative_i().
template<class ImageType > itk::SmartPointer<ImageType> anima::readImage (std::string filename)
Definition at line 12 of file animaReadWriteFunctions.h.
Referenced by main().
template<class T1 , class T2 > void anima::RecomposeTensor (vnl_diag_matrix< T1 > & eigs, vnl_matrix< T1 > & eigVecs, vnl_matrix< T2 > & resMatrix)
Recompose tensor from values extracted using SymmetricEigenAnalysis (vnl_symmetric_eigensystem transposes all this)
Definition at line 240 of file animaBaseTensorTools.hxx.
Referenced by ExtractRotationFromJacobianMatrix(), GetTensorExponential(), GetTensorLogarithm(), GetTensorPower(), anima::TensorGeneralizedCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::GetValue(), anima::TensorGeneralizedCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::PreComputeFixedValues(), ProjectOnTensorSpace(), SampleFromMultivariateGaussianDistribution(), and anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SampleStickModelCompartmentsFromDTI().
template<class ImageType > itk::SmartPointer<ImageType> anima::reorient3DImage (typename itk::SmartPointer< ImageType > input, itk::SpatialOrientation::ValidCoordinateOrientationFlags orientation)
Definition at line 12 of file animaReorientation.h.
template<class ImageType > itk::SmartPointer<ImageType> anima::reorientImage (typename itk::SmartPointer< ImageType > input, itk::SpatialOrientation::ValidCoordinateOrientationFlags orientation)
Definition at line 31 of file animaReorientation.h.
template<class ImageType , class GradientType > itk::SmartPointer<ImageType> anima::reorientImageAndGradient (typename itk::SmartPointer< ImageType > input, itk::SpatialOrientation::ValidCoordinateOrientationFlags orientation, std::vector< GradientType > & gradients)
Definition at line 140 of file animaReorientation.h.
Referenced by convert().
template<class VectorType > void anima::Revert (const VectorType & v, const unsigned int vSize, VectorType & resVec)
Definition at line 401 of file animaVectorOperations.hxx.
Referenced by anima::BaseTractographyImageFilter::ComputeFiber(), anima::dtiTractographyImageFilter::GetNextDirection(), and Revert().
template<class ScalarType > void anima::Revert (const std::vector< ScalarType > & v, std::vector< ScalarType > & resVec)
Definition at line 407 of file animaVectorOperations.hxx.
References Revert().
template<class ScalarType > void anima::Revert (const itk::Point< ScalarType > & v, itk::Point< ScalarType > & resVec)
Definition at line 413 of file animaVectorOperations.hxx.
References Revert().
template<class ScalarType , unsigned int NDimension> void anima::Revert (const vnl_vector_fixed< ScalarType, NDimension > & v, vnl_vector_fixed< ScalarType, NDimension > & resVec)
Definition at line 420 of file animaVectorOperations.hxx.
References Revert().
template<class T1 , class T2 , class T3 , class T4 > void anima::RotateAroundAxis (const std::vector< T1 > & v, const T2 & phi, const std::vector< T3 > & normalVec, std::vector< T4 > & resVec)
Definition at line 496 of file animaVectorOperations.hxx.
Referenced by SampleFromWatsonDistribution().
template<class Vector3DType , class ScalarType > void anima::RotateAroundAxis (const Vector3DType & v, const ScalarType & phi, const Vector3DType & normalVec, Vector3DType & resVec)
Definition at line 532 of file animaVectorOperations.hxx.
template<class T1 , class T2 , class T3 > void anima::RotateSymmetricMatrix (T1 & tensor, T2 & rotationMatrix, T3 & rotated_tensor, unsigned int tensorDim)
Definition at line 260 of file animaBaseTensorTools.hxx.
Referenced by anima::TensorMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::GetValue(), anima::TensorCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::GetValue(), anima::TensorGeneralizedCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::GetValue(), anima::TensorCompartment::Reorient(), anima::TensorResampleImageFilter< TImageType, TInterpolatorPrecisionType >::ReorientInterpolatedModel(), and RotateSymmetricMatrix().
template<class T1 , class T2 > void anima::RotateSymmetricMatrix (vnl_matrix< T1 > & tensor, vnl_matrix< T2 > & rotationMatrix, vnl_matrix< T2 > & rotated_tensor)
Definition at line 282 of file animaBaseTensorTools.hxx.
References RotateSymmetricMatrix().
template<class T1 , class T2 , unsigned int NDim> void anima::RotateSymmetricMatrix (itk::Matrix< T1, NDim, NDim > & tensor, itk::Matrix< T2, NDim, NDim > & rotationMatrix, itk::Matrix< T2, NDim, NDim > & rotated_tensor)
Definition at line 291 of file animaBaseTensorTools.hxx.
References RotateSymmetricMatrix().
template<class ScalarType > double anima::safe_log (const ScalarType x)
Definition at line 7 of file animaLogarithmFunctions.hxx.
Referenced by anima::BaseProbabilisticTractographyImageFilter::ComputeFiber(), anima::DTIProbabilisticTractographyImageFilter::ComputeModelEstimation(), anima::ODFProbabilisticTractographyImageFilter::ProposeNewDirection(), anima::DTIProbabilisticTractographyImageFilter::ProposeNewDirection(), SampleFromVMFDistribution(), SampleFromVMFDistributionNumericallyStable(), anima::BaseProbabilisticTractographyImageFilter::UpdateClassesMemberships(), and VMFDistance().
template<class T > unsigned int anima::SampleFromBernoulliDistribution (const T & p, std::mt19937 & generator)
Definition at line 45 of file animaDistributionSampling.hxx.
template<class T > double anima::SampleFromGaussianDistribution (const T & mean, const T & std, std::mt19937 & generator)
Definition at line 52 of file animaDistributionSampling.hxx.
Referenced by SampleFromMultivariateGaussianDistribution(), anima::GaussianNoiseGeneratorImageFilter< Dimension >::TreatRegionWithNoiseVariance(), and anima::NonCentralChiNoiseGeneratorImageFilter< Dimension >::TreatRegionWithNoiseVariance().
template<class VectorType , class ScalarType > void anima::SampleFromMultivariateGaussianDistribution (const VectorType & mean, const vnl_matrix< ScalarType > & mat, VectorType & resVec, std::mt19937 & generator, bool isMatCovariance = true)
Definition at line 59 of file animaDistributionSampling.hxx.
References RecomposeTensor(), and SampleFromGaussianDistribution().
template<class T > double anima::SampleFromUniformDistribution (const T & a, const T & b, std::mt19937 & generator)
Definition at line 18 of file animaDistributionSampling.hxx.
Referenced by SampleFromVMFDistribution(), SampleFromVMFDistributionNumericallyStable(), and SampleFromWatsonDistribution().
template<class VectorType > void anima::SampleFromUniformDistributionOn2Sphere (std::mt19937 & generator, VectorType & resVec)
Definition at line 26 of file animaDistributionSampling.hxx.
template<class VectorType , class ScalarType > void anima::SampleFromVMFDistribution (const ScalarType & kappa, const VectorType & meanDirection, VectorType & resVec, std::mt19937 & generator)
Definition at line 93 of file animaDistributionSampling.hxx.
References GetRotationMatrixFromVectors(), safe_log(), SampleFromUniformDistribution(), and TransformCartesianToSphericalCoordinates().
template<class VectorType , class ScalarType > void anima::SampleFromVMFDistributionNumericallyStable (const ScalarType & kappa, const VectorType & meanDirection, VectorType & resVec, std::mt19937 & generator)
Definition at line 143 of file animaDistributionSampling.hxx.
References GetRotationMatrixFromVectors(), safe_log(), SampleFromUniformDistribution(), TransformCartesianToSphericalCoordinates(), and xi().
template<class ScalarType , class VectorType > void anima::SampleFromWatsonDistribution (const ScalarType & kappa, const VectorType & meanDirection, VectorType & resVec, unsigned int DataDimension, std::mt19937 & generator)
void SampleFromWatsonDistribution(const ScalarType &kappa, const VectorType &meanDirection, VectorType &resVec, unsigned int DataDimension, std::mt19937 &generator)
Sample from the Watson distribution using the procedure described in Fisher et al., Statistical Analysis of Spherical Data, 1993, p.59.
Author:
Aymeric Stamm
Date:
October 2013
Parameters:
kappa Concentration parameter of the Watson distribution.
meanDirection Mean direction of the Watson distribution.
resVec Resulting sample.
DataDimension Dimension of the sphere + 1.
generator Pseudo-random number generator.
Definition at line 177 of file animaDistributionSampling.hxx.
References ComputeCrossProduct(), ComputeNorm(), Normalize(), RotateAroundAxis(), SampleFromUniformDistribution(), and TransformCartesianToSphericalCoordinates().
Referenced by anima::ODFProbabilisticTractographyImageFilter::ProposeNewDirection(), anima::DTIProbabilisticTractographyImageFilter::ProposeNewDirection(), and SampleFromWatsonDistribution().
template<class ScalarType , unsigned int DataDimension> void anima::SampleFromWatsonDistribution (const ScalarType & kappa, const vnl_vector_fixed< ScalarType, DataDimension > & meanDirection, vnl_vector_fixed< ScalarType, DataDimension > & resVec, std::mt19937 & generator)
void SampleFromWatsonDistribution(const ScalarType &kappa, const vnl_vector_fixed < ScalarType, DataDimension > &meanDirection, vnl_vector_fixed < ScalarType, DataDimension > &resVec, std::mt19937 &generator)
Sample from the Watson distribution using the procedure described in Fisher et al., Statistical Analysis of Spherical Data, 1993, p.59.
Author:
Aymeric Stamm
Date:
October 2013
Parameters:
kappa Concentration parameter of the Watson distribution.
meanDirection Mean direction of the Watson distribution.
resVec Resulting sample.
generator Pseudo-random number generator.
Definition at line 292 of file animaDistributionSampling.hxx.
References SampleFromWatsonDistribution().
template<class ScalarType , unsigned int DataDimension> void anima::SampleFromWatsonDistribution (const ScalarType & kappa, const itk::Point< ScalarType, DataDimension > & meanDirection, itk::Point< ScalarType, DataDimension > & resVec, std::mt19937 & generator)
void SampleFromWatsonDistribution(const ScalarType &kappa, const itk::Point < ScalarType, DataDimension > &meanDirection, itk::Point < ScalarType, DataDimension > &resVec, std::mt19937 &generator)
Sample from the Watson distribution using the procedure described in Fisher et al., Statistical Analysis of Spherical Data, 1993, p.59.
Author:
Aymeric Stamm
Date:
October 2013
Parameters:
kappa Concentration parameter of the Watson distribution.
meanDirection Mean direction of the Watson distribution.
resVec Resulting sample.
generator Pseudo-random number generator.
Definition at line 320 of file animaDistributionSampling.hxx.
References SampleFromWatsonDistribution().
template<class ScalarType , unsigned int DataDimension> void anima::SampleFromWatsonDistribution (const ScalarType & kappa, const itk::Vector< ScalarType, DataDimension > & meanDirection, itk::Vector< ScalarType, DataDimension > & resVec, std::mt19937 & generator)
void SampleFromWatsonDistribution(const ScalarType &kappa, const itk::Vector < ScalarType, DataDimension > &meanDirection, itk::Vector < ScalarType, DataDimension > &resVec, std::mt19937 &generator)
Sample from the Watson distribution using the procedure described in Fisher et al., Statistical Analysis of Spherical Data, 1993, p.59.
Author:
Aymeric Stamm
Date:
October 2013
Parameters:
kappa Concentration parameter of the Watson distribution.
meanDirection Mean direction of the Watson distribution.
resVec Resulting sample.
generator Pseudo-random number generator.
Definition at line 348 of file animaDistributionSampling.hxx.
References SampleFromWatsonDistribution().
template<class InputImageType , class ImageFilterType > unsigned int anima::setMultipleImageFilterInputsFromFileName (std::string & fileName, ImageFilterType * filter)
Set inputs of an image to image filter from a file name containing either a list of files or a higher dimensional image.
Definition at line 79 of file animaReadWriteFunctions.h.
template<class T > double anima::ShOverId (const T & x)
Definition at line 8 of file animaHyperbolicFunctions.hxx.
template<class T1 , class T2 , class T3 > double anima::ShRatio (const T1 & k, const T2 & alpha, const T3 & beta)
Definition at line 20 of file animaHyperbolicFunctions.hxx.
template<class T > double anima::SinOverId (const T & x)
Definition at line 8 of file animaTrigonometricFunctions.hxx.
template<class VectorType > void anima::TransformCartesianToSphericalCoordinates (const VectorType & v, VectorType & resVec)
Definition at line 425 of file animaVectorOperations.hxx.
References ComputeNorm(), and Normalize().
Referenced by anima::ODFEstimatorImageFilter< TInputPixelType, TOutputPixelType >::AddGradientDirection(), anima::ODFEstimatorImageFilter< TInputPixelType, TOutputPixelType >::BeforeThreadedGenerateData(), anima::ODFProbabilisticTractographyImageFilter::ComputeLogWeightUpdate(), anima::ODFProbabilisticTractographyImageFilter::FindODFMaxima(), InitializeSampleDirections(), anima::ODFProbabilisticTractographyImageFilter::PrepareTractography(), anima::ODFProbabilisticTractographyImageFilter::ProposeNewDirection(), anima::BaseCompartment::Reorient(), SampleFromVMFDistribution(), SampleFromVMFDistributionNumericallyStable(), SampleFromWatsonDistribution(), anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SampleStickModelCompartmentsFromDTI(), anima::StickCompartment::SetCompartmentVector(), anima::ZeppelinCompartment::SetCompartmentVector(), anima::PyramidalSymmetryBridge< PixelType, ScalarType >::Update(), and anima::TensorCompartment::UpdateParametersFromTensor().
template<class VectorType > void anima::TransformSphericalToCartesianCoordinates (const VectorType & v, VectorType & resVec)
Definition at line 454 of file animaVectorOperations.hxx.
Referenced by anima::ODFProbabilisticTractographyImageFilter::FindODFMaxima(), anima::StickCompartment::GetCompartmentVector(), anima::ZeppelinCompartment::GetCompartmentVector(), anima::StickCompartment::GetDiffusionTensor(), anima::ZeppelinCompartment::GetDiffusionTensor(), anima::StickCompartment::GetLogDiffusionProfile(), anima::ZeppelinCompartment::GetLogDiffusionProfile(), anima::BaseCompartment::IsEqual(), anima::BaseCompartment::Reorient(), and anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SampleStickModelCompartmentsFromDTI().
template<class VectorType > void anima::TransformSphericalToCartesianCoordinates (double theta, double phi, double vectorNorm, VectorType & resVec)
Definition at line 459 of file animaVectorOperations.hxx.
template<class T > double anima::VectorCovarianceTest (vnl_matrix< T > & logRefPatchCov, vnl_matrix< T > & movingPatchCov)
Test if covariance matrices are different (returns distance)
Definition at line 147 of file animaVectorImagePatchStatistics.hxx.
Referenced by anima::NLMeansVectorPatchSearcher< ImageScalarType, DataImageType >::TestPatchConformity(), and anima::LocalPatchCovarianceDistanceImageFilter< PixelScalarType >::ThreadedGenerateData().
template<class T > double anima::VectorMeansTest (itk::VariableLengthVector< T > & refPatchMean, itk::VariableLengthVector< T > & movingPatchMean, const unsigned int & refPatchNumElts, const unsigned int & movingPatchNumElts, vnl_matrix< T > & refPatchCov, vnl_matrix< T > & movingPatchCov)
Test if vector means are different (returns distance)
Definition at line 179 of file animaVectorImagePatchStatistics.hxx.
Referenced by anima::NLMeansVectorPatchSearcher< ImageScalarType, DataImageType >::TestPatchConformity(), and anima::LocalPatchMeanDistanceImageFilter< PixelScalarType >::ThreadedGenerateData().
template<class ScalarType , unsigned int Dimension> double anima::VMFDistance (const itk::Point< ScalarType, Dimension > & muFirst, const double & kappaFirst, const itk::Point< ScalarType, Dimension > & muSec, const double & kappaSec)
Definition at line 46 of file animaVMFDistribution.hxx.
References safe_log().
template<class OutputImageType > void anima::writeImage (std::string filename, OutputImageType * img)
Definition at line 28 of file animaReadWriteFunctions.h.
Referenced by main().
template<class T > double anima::xi (const T & k)
Definition at line 29 of file animaHyperbolicFunctions.hxx.
Referenced by anima::GaussianREMEstimator< TInputImage, TMaskImage >::concentration(), anima::GaussianEMEstimator< TInputImage, TMaskImage >::expectation(), anima::ConcentrationUpperBoundSolverCostFunction::operator()(), and SampleFromVMFDistributionNumericallyStable().
Variable Documentation
const double anima::zeroWeight = 0
Definition at line 83 of file animaBalooSVFTransformAgregator.h.
Referenced by filterInputs().